rnpgp/rnp

build_macos.sh, src/lib/netpgp.c, src/lib/packet.h
I've included a (temporary) bug fix for an access violation caused by passing an empty keychain to `lib/netpgp.c:get_first_ring`. Exactly why that happens sometimes is the next issue to follow up. Also included is a newer version of `build_macos.sh`.
=> Some refactoring and a bug fix

src/lib/netpgp.c
As advertised. The code in and around it needs some work but this should be enough in the meantime.
=> Use .rnp instead of the key ID when selecting a --homedir subdirectory

build.sh, build_common.inc.sh, build_macos.sh, build_main.inc.sh
I rolled the common parts of `build_macos.sh` into `build_common.inc.mk` to be used by `build.sh` as well and expanded on macOS-specific script. Following that pattern it should be easy to fork off new scripts for other targets.
=> Updated the build shell scripts

.gitignore, configure.ac, src/Makefile.am, src/cmocka/Makefile.am, src/cmocka/rnp_tests.c
Current tests digests, ciphers, RSA keygen and encrypt/decrypt, and ElGamal encrypt/decrypt. Uses the cmocka library https://cmocka.org/
I'm not sure if there is a better way to integrate this into the build. Right now if cmocka is not available the build will fail, probably instead the cmocka subdir should just be skipped in that case.
=> Add some unit tests using cmocka

src/lib/packet-print.c, src/lib/packet-show.c, src/lib/ssh2pgp.c, src/rnpv/libverify.c
This contains:
* Replacements for all instances of asprintf as per #9 except the vasprintf() instance at rnpv/obuf_print:227, which I want to formulate a robust solution to.
* A bug fix for a bug that I introduced in my last PR causing 'uid' notices to be truncated - sorry about that.
I'm not happy with memory management in pgp_sprint_keydata and pgp_hkp_sprint_keydata. I'm going to have to familiarise myself better with the RFCs before I can re-work that section to be more predictable. In the meantime I'm going to move on to other pending issues and come back to this after some progress has been made in other areas. 👍
=> asprintf deprecation

README.md, src/cmocka/rnp_tests.c, src/lib/crypto.h, src/lib/openssl_crypto.c
* Reimplements `pgp_elgamal_private_decrypt' and `pgp_elgamal_public_encrypt'
- Botan is used instead of OpenSSL BN API
* Updates description of both function
* This patch depends on newer version of Botan (see changes to README.md)
=> Elgamal on botan conv

src/lib/pem.c
Tiny change that allows builds to succeed on macOS; clang is a bit more aware and detects that `privkey` could potentially be destroyed uninitialised.
=> Shuffled around key cleanup in lib/pem.c:openssl_read_pem_seckey.

ax_check_botan.m4, src/cmocka/rnp_tests.c, src/lib/crypto.h, src/lib/librnp.3, src/lib/pem.c, src/lib/ssh2pgp.c
Silly to leave these hanging around. 
@ronaldtse One thing you mentioned in the comment in #8 is `USE_BN_INTERFACE`, which controls if the BN function wrappers are exposed as `PGPV_BN_foo` or else `BN_foo`. What do you want to do here? Change all callers to `PGPV_BN_foo` [or some other prefix like `RNP_BN_foo`, easy to change this at the same time], or just remove the controlling macro and always have the `BN_foo` compatibility defines?
=> Remove remaining references to OpenSSL in the source

src/lib/dsa.c
It looks like there was a TODO in there for this particular part.
I'm not familiar with DSA at all, so would love confirmation that q/r/s are always equal in size.
Closes #84.
=> Fix DSA signature verification

src/lib/crypto.h, src/lib/rsa.c, src/lib/signature.c
Hopefully closes https://github.com/riboseinc/rnp/issues/79
I think the main piece I'm not sure on here is the removal of the legacy code, but it was necessary to get `rnp --verify` to agree with the other tools.
rnp/rnpv/gpg now all agree that the signatures are valid (and invalid when tampered with).
I think the crux of the issue here is a mismatch in parameter names in botan_privkey_load_rsa vs RSA_PrivateKey, so I filed a PR there: https://github.com/randombit/botan/pull/1045
=> Fix RSA signatures

src/cmocka/rnp_tests.c, src/lib/reader.c, src/lib/signature.c
This would have caught #79
Fixes two bugs I found along the way: in `pgp_getpassphrase` the password read from the file descriptor had its last character truncated. The library uses different codepaths to read the passphrase during keygen vs all other operations, so the result was that after generating a key with passphrase "abc" the decryption would fail because it would treat the entered passphrase as "ab" even though the pipe contained "abc". I think this doesn't come up in manual testing because `rnp` command line program doesn't use pass-fd. 
Also fix a bug in rsa_sign - if the requested hash is not SHA-1 or SHA-256 then it would just default to SHA-256, then be confused when the hash output a different length. Found because initially I was testing with MD5 also, which failed.
=> Add a test for RSA signature generation and verification

include/rnp.h, src/lib/librnp.3, src/lib/rnp.c, src/rnp/rnp.c, src/rnpkeys/rnpkeys.c
Introduced `rnp_set_keyring_format` to specified a keyring format for #33 
By default the keyring format is GPG, but when someone provides ssh-related option, it switched to SSH.
For example, list keys for different formats:
```
➜  rnp git:(abstract_keyring) ✗ ./src/rnpkeys/rnpkeys --list-keys
1 key found
signature  2048/RSA (Encrypt or Sign) 85af26f0509e9014 2017-05-18
Key fingerprint: 5b4f d40e 3c4f 5b20 b92c 61c0 85af 26f0 509e 9014
uid              RSA 2048-bit key <catap@localhost>
➜  rnp git:(abstract_keyring) ✗ ./src/rnpkeys/rnpkeys --keyring-format=GPG --list-keys
1 key found
signature  2048/RSA (Encrypt or Sign) 85af26f0509e9014 2017-05-18
Key fingerprint: 5b4f d40e 3c4f 5b20 b92c 61c0 85af 26f0 509e 9014
uid              RSA 2048-bit key <catap@localhost>
➜  rnp …
```
=> Introduced `rnp_set_keyring_format` to specified a keyring format for #33

src/lib/symmetric.c
Was confused that valgrind showed all clean until I realized cmocka runs the tests in a new process (that's how it catches SIGSEGVs and the like inside a test). With `valgrind --trace-children=yes` the error popped right out. Also found a couple of other bugs that I'll post either PRs or issues for momentarily.
=> Fix an invalid free in the block cipher code (GH #112)

.gitignore, configure.ac, src/Makefile.am, src/fuzzing/Makefile.am, src/fuzzing/fuzz_keys.c, src/lib/packet-parse.c, src/lib/rnp.c
I don't know if you necessarily want to merge this (but maybe you do). Adds a simple fuzzer for key parsing. Using just a single valid public key as initial input, AFL (http://lcamtuf.coredump.cx/afl/) found 38 unique crash bugs in about a minute and a half of runtime (I don't know if all of those are truly unique, sometimes a single bug can be reached by more than one path and that causes AFL to categorize them as different crashes).
Basic usage:
```
CC=afl-gcc ./configure
mkdir afl_in afl_out
cp <some keys> afl_in
afl-fuzz -i afl_in -o afl_out ./src/fuzzing/.libs/fuzz_keys @@ 
(look at the pretty screen until some crashes are found)
valgrind -v ./src/fuzzing/.libs/fuzz_keys < afl_out/crashes/...
```
Example issues
```
==2427== Invalid read of size 4
==2427==    at 0x4E5DAE7: …
```
=> Add a simple fuzzer for public keys

src/lib/create.c, src/lib/crypto.h, src/lib/rsa.c
Fixes #123 
The change is not actually very large but reindenting within the function + moving some lines caused the diff to kind of blow up.
Removes pgp_rsa_public_encrypt, unused since #50 was resolved.
=> Fix a memory leak in RSA key generation

src/cmocka/rnp_tests.c, src/lib/create.c, src/lib/crypto.h, src/lib/misc.c, src/lib/packet-parse.c, src/lib/reader.c, src/lib/ssh2pgp.c, src/lib/symmetric.c, src/lib/symmetric.h, src/lib/writer.c
I started by trying to make the structure completely opaque but kind of ran into a quagmire with that, so for now I limited the change to removing the function pointers from `pgp_crypt_t`. This alone greatly simplifies `symmetric.c`
While there implemented support for Blowfish/Twofish (#107), and also Camellia-192 which was missing.
At this point the only algorithm-specific code in `symmetric.c` are a handful of switch statements, so I'm not sure if breaking up the file (as suggested in #101) makes sense anymore - @ronaldtse your thoughts?
Changes to `src/lib` are done and ready for review, and there is even a test now.
=> Clean up symmetric cipher code

src/lib/create.c, src/lib/rnp.c
* Removes memory leaks from rnpkeys that occur on key generation
* Makes set_core_dumps more readable
=> Removes memory leaks from rnpkeys

configure.ac
The beset way is made it optional and don't try to build the code with json-c dependencies but stop at configure is better that pass it and crash at building.
=> This code can't be build without json-c, fix it

.clang-format, Developers Guide.md, git-hooks/enable.sh, git-hooks/pre-commit.sh
Feedback would be much appreciated.
There's mostly 2 things here:
This is just a simple introduction to some of the things we use (travis, codecov, coverity, ...), and some general guidelines, etc.
It can probably be expanded later on, and I guess we would want to add a link from the README.md.
The idea here is to introduce clang-format for keeping a consistent code base.
I basically pinned down the settings for the current code base, as closely as possible.
The only major change I added in here was using spaces, rather than tabs.
I think all of us have had issues with tabs and accidentally committed spaces.
Every editor seems to handle tabs differently, and I think we may be better off avoiding them.
I created a git pre-commit hook that works well for me. It looks like this:
```
$ git …
```
=> Developers guide and clang-format styling

src/cmocka/rnp_tests.c, src/common/utils.h, src/lib/create.c, src/lib/crypto.c, src/lib/crypto.h, src/lib/misc.c, src/lib/reader.c, src/lib/rsa.c
Few things I've found during EC implementation, but not really related to EC
* Remove DSA and Elgamal key serialization from RSA key generation
* User doesn't need to free memory after rsa_generate_keypair fails
* Fixes memory leaks that occure when RSA key generation fails in the middle
=> Cleanup in RSA key generation

src/lib/compress.c, src/lib/create.c, src/lib/crypto.h, src/lib/errors.h, src/lib/key_store_ssh.c, src/lib/misc.c, src/lib/packet-parse.c, src/lib/packet.h, src/lib/reader.c, src/lib/rnp.c, src/lib/signature.c, src/rnpv/b64.c, src/rnpv/libverify.c
clang-format 4.0.0 does not remove them inside commented-out code.
=> Purge tab characters from source.

.travis.yml, ci/main.sh
This just separates "sanitize" and "sanitize-leaks".
The "sanitize" run is no longer permitted to fail.
This way, we can still catch other things in the sanitize run, like heap overflows, but allow memory leaks for now.
=> ci: Add sanitize-leaks build to matrix (failure allowed for now).

Developers Guide.md, git-hooks/pre-commit.sh
It looks like clang-format 4.0.0 is the newest official stable version.
At some point we may want to look at google's stable branch of clang for a newer clang-format (I think - may have to check on that).
But for now it's probably safest for us all to stick to 4.0.0.
This just clarifies things in the Developer's Guide, and adds a version check to the pre-commit hook.
=> Specify clang-format version required as v4.0.0.

src/lib/rsa.c
No change in logic.
Apart from this no build issues on 32 bit.
=> fix build on 32 bit by avoiding using %zu for unsigned long, fixes #193

src/cmocka/rnp_tests.c, src/cmocka/rnp_tests.h, src/cmocka/rnp_tests_cipher.c, src/common/utils.h, src/lib/Makefile.am, src/lib/bn.c, src/lib/bn.h, src/lib/create.c, src/lib/crypto.c, src/lib/crypto.h, src/lib/dsa.c, src/lib/dsa.h, src/lib/eddsa.c, src/lib/eddsa.h, src/lib/elgamal.c, src/lib/elgamal.h, src/lib/misc.c, src/lib/packet-key.c, src/lib/packet-parse.c, src/lib/packet-print.c, src/lib/packet-show.c, src/lib/packet.h, src/lib/pem.c, src/lib/rnp.c, src/lib/rnpsdk.h, src/lib/rsa.c, src/lib/rsa.h, src/lib/signature.c, src/lib/types.h, src/rnpv/libverify.c
#109 
Currently keygen works by requesting a 255 bit key. It would be nice to clean this up by adding an algorithm identifier to `rnp_generate_key`. The underlying API `pgp_generate_keypair` does take an alg id now.
EdDSA keys are actually stored the same as ECC keys, so this helps towards #27 also.
Splits apart `crypto.h` a bit - adding `rsa.h`, `dsa.h`, `elgamal.h`, `eddsa.h`
Also extracts the function `rnp_strhexdump` out of `packet-print.c` because it's needed in `rnp.c` also now. Previously this function printed the key info then extracted the keyid at the expected offset in the string - this broke as soon as something other than RSA was used.
Tested by generating a key with `rnpkeys`, singing a file, exporting the public key to `gpg`, verifying the signature.
=> Add Ed25519 signatures

src/cmocka/rnp_tests.c
I've noticed this doesn't seem to be set in the travisci/ci-garnet image.
=> Set LOGNAME in cmocka tests if not already set

src/lib/packet-show.c, src/lib/packet.h, src/lib/symmetric.c
SM4 support is not quite landed in Botan master yet but will shortly. This allows it to be used for bulk encryption when available.
Also renumbers Camellia ciphers to use the values from RFC 5581. I looked and Camellia was assigned to the experimental/private range in the original NetPGP import I guess because the support in NetPGP predated the RFC.
=> Add support for SM4

src/lib/packet-key.c, src/lib/signature.c, src/lib/signature.h
Fixes #219 , mostly for better code readability.
=> Changed pgp_add_time to use enum instead of char* parameter.

README.md, include/rnp.h, src/cmocka/rnp_tests_cipher.c, src/cmocka/rnp_tests_exportkey.c, src/cmocka/rnp_tests_generatekey.c, src/common/utils.h, src/lib/bn.c, src/lib/create.c, src/lib/crypto.c, src/lib/crypto.h, src/lib/ecdsa.c, src/lib/ecdsa.h, src/lib/eddsa.h, src/lib/hash.h, src/lib/packet-parse.c, src/lib/packet-print.c, src/lib/packet-show.c, src/lib/packet.h, src/lib/rnp.c, src/lib/rsa.c, src/lib/rsa.h, src/lib/signature.c, src/rnpkeys/Makefile.am, src/rnpkeys/rnpkeys.c, src/rnpkeys/tui.c
Introduces --expert flag for rnpkeys. This flag can be used if user want's to generate key different than default (RSA/2048). In such case rnpkeys will ask user for kind of key/size he wants to generate. Currently only RSA, ECDSA and EDDSA is supported.
I propose we introduce structure that can be used for passing complete set of parameters needed for key generation (currently this structure is used to pass number of bits or curve name).
Patch contains also some small improvements for EC key generation (moves some function from ecdsa.c to crypto.c)
#130
=> Introduces --expert flag for rnpkeys (ex #241) 

src/cmocka/rnp_tests_cipher.c, src/lib/bn.c, src/lib/bn.h
Was a stub to allow OpenSSL compat, but not really used anymore.
It's kind of telling that almost no code changes were required to handle the removal of the BN_CTX args - it looks like (now that ElGamal and co are not implemented via BN) the only BN functions actually in use are `BN_bn2bin`, `BN_bin2bn`, `BN_num_bytes`, `BN_num_bits`, and maybe one or two others. So maybe there is more pruning that can occur here.
=> Remove the unused BN_CTX type

src/rnpkeys/tui.c
``rnpkeys`` uses wrong curve size for generating ECDSA keys
=> Fixes bug introduced in commit 8c3031d

.travis.yml, Developers Guide.md, ci/install.sh, ci/main.sh, configure.ac, m4/ax_check_jsonc.m4, src/cmocka/Makefile.am, src/fuzzing/Makefile.am, src/lib/Makefile.am, src/rnp/Makefile.am, src/rnpkeys/Makefile.am, src/rnpv/Makefile.am
With the introduction of AC_CHECK_HEADERS in 4cdd9b5 the configure script couldn't find out of the box
the headers of a standard json-c implementation. To save the user from the need of manually
tinkering with the CFLAGS and co. we (re-)introduce using pkg-config to get the proper
compiler- and linker flags, while keeping the CI build (with non-standard json-c install path)
functioning by passing a custom PKG_CONFIG_PATH envvar to ./configure.
=> use pkgconfig for getting json-c

src/lib/key_store_pgp.c
Two issues here:
- We are allocating a stream twice, and leaking one. Once with pgp_new
and once with pgp_setup_memory_read.
- We were calling pgp_parse_options on the unused stream, so effectively
signature subpkts would never be parsed.
Fixes #278.
=> Fix memory leak and sig subpkt parsing issue with pgp keyrings.

src/rnp/rnp.c
Note: I have not looked in-depth at whether a larger problem exists here.
I have only noticed that my compiler does not like this and that it does appear there's a chance to read uninitialized data.
Fixes #280.
=> Fix uninitialized variable read in rnp_cmd.

src/lib/key_store_pgp.c, src/lib/packet-print.c, src/lib/packet.h, src/lib/rnp.c
`rnpkeys --list-keys` (and some other commands) will now show something like "[SC]" (sign+certify), similar to gpg.
This also adds key flags to the pgp_key_t structure. These are not currently used beyond loading them from
signature packets and printing them out.
list-packets already handles key flags, so no update there.
The JSON produced is like `{"flags": 3, "usage": "SC"}`. So the raw flags value is available as well as our interpretation of them.
**Known Issues**:
* With subkeys, this will typically show the flags for the wrong key. This will be fixed after https://github.com/riboseinc/rnp/issues/277. Since this has no effect, other than printing some output, I think it's OK for the moment.
* Key flags are not set during key generation, are not persisted to disk, etc. (ongoing …
=> Add key flag loading/printing in listed keys.

Developers Guide.md
Proposed changes:
* Added a few links to riboseinc:guides.
* Completely flipped the guideline on single-line conditionals. I *thought* modern compilers were good at warning about things like:
```c
if (something)
do_thing();
do_other_thing(); // sleepily added this line later, intending for it to be part of the if block
```
But apparently not, as I did actually get bit by this recently in this code base. GCC does seem to warn in *some* cases, but not all. So I think it's probably safest to *always* use braces for if/while/etc.
* Added an exception for constant local static variable declarations. These are perfectly OK when all data is constant, and I neglected to mention this previously. Also added some code to demonstrate.
* Removed maheitsec.
=> Update Developers Guide.md

src/rnpkeys/rnpkeys.c
I've found this during ECDH implementation.
Unfortunately recent refactoring completely breaks key generation when expert mode is requested.``rnpkeys`` will ask user for details regarding key to generate, ``rnp_generate_key_expert_mode`` returns with success and then default parameters (RSA/2048) for key to be generated are set as code is wrongly implemented.
Key generation in "expert mode" can be requested from command line and we don't have much tests for TUI. 
I haven't checked if any other command line option is broken.
=> Fixes key generation in expert mode

src/lib/packet-print.c
=> Fix expiration time printing in psubkeybinding.

src/lib/rnp.c, src/rnp/rnp.c
For the rnp utility, during the signing/encryption/whatever else, --output option worked only for file input, i.e. when input filename is specified, and was ignored when input is stdin. Now it should work for stdin as well.
=> Fixes #210: --output option doesn't work when input is stdin

src/lib/create.c, src/lib/crypto.c, src/lib/key_store.c, src/lib/key_store.h, src/lib/key_store_ssh.c, src/lib/misc.c, src/lib/packet.h, src/lib/signature.c
This PR fixes usage of rnp_keyid and rnp_fingerprint functions by removing hashtype parameter.
Also it was removed from the keyring.
The only purpose of these parameters was support for custom ssh fingerprint calculation.
So I added ssh_keyid and ssh_fingerprint static functions as this code is used only in ssh_keystore.c, and cleaned up main pgp code.
Waiting for approval of the PR #299 since it includes some more changes to ssh_keystore making it compilable.
=> Correct usage of rnp_keyid and rnp_fingerprint functions

src/lib/misc.c, src/lib/packet.h
Found during ECDH development - hash algorithm was not set when fingerprint is calculated.
=> Set hash algorithm while calculating fingerprint

src/lib/create.c, src/lib/key_store.c, src/lib/packet.h
When key is loaded then all packets are saved into the sub packets array. Then, when keyring is re-saved all those packets were written together with public key packet + user id, causing duplication of key + user id packets on output. I changed this behavior that now for loaded key pub key and userid are saved from records only for non-loaded keys. This also have another meaning : already existing packets should written as they were to not break to the signature.
This solution is quick and dirty since within current implementation of key data structures it is hard to imagine correct working of multiple user ids, subkeys, signatures, direct key signatures and so on. 
@dewyatt I will write separate post about it somewhere, since it is closely related to what you are doing now.
=> Fixes #256: duplication of keys in keyring after the new key generation

src/lib/crypto.c
Found during ECDH development.
We display wrong name of the curve
=> Don't mix Edwards and Bernstein curves

src/lib/key_store.c, src/lib/key_store_pgp.c, src/lib/packet-parse.c, src/lib/packet-print.c, src/lib/packet.h, src/lib/pgp-key.c, src/lib/pgp-key.h
* Rename pgp_subpacket_t to pgp_rawpacket_t. The naming on this is very misleading and it confuses me every time I see it.
This structure never had anything to do with signature subpackets, it's just a raw chunk of data. 
In OpenPGP-SDK this was called ops_packet_t, which probably made more sense. Unfortunately, we use pgp_packet_t to refer to what OpenPGP-SDK called ops_parser_content_t (parsed pkts).
* Add tag field to pgp_rawpacket_t
I have plans to use this and I think it makes sense to toss it into the structure since it's already been parsed out.
=> Rename pgp_subpacket_t and add tag field

src/tests/Makefile.am, tests/Makefile.am, tests/rnp_tests.at, tests/testsuite.at
Hey,
I just:
- removed from `make install` test program;
- added runs this test program to `make check`.
for https://github.com/riboseinc/rnp/pull/327 and https://github.com/riboseinc/rnp/pull/328
But `make check` is broken right now:
```
1: tests with no default userid in gpg.conf        ok
2: init                                            ok
3: attached signature and verification             ok
4: encryption and decryption                       FAILED (crypt.at:13)
5: detached signature and verification             ok
6: simple signature and verification               ok
7: run rnp_tests                                   ok
``` 
But it was broken at https://github.com/riboseinc/rnp/commit/551a1c8e5220da8e82da2e38c0755413070a1727
```
1: tests with no default userid in gpg.conf        ok …
```
=> #328 autohell

src/lib/crypto.c, src/lib/crypto.h, src/lib/packet-create.c, src/lib/packet-print.c, src/lib/packet-print.h, src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/reader.c, src/lib/rnp.c, src/lib/validate.c, src/lib/validate.h, src/librekey/rnp_key_store.c, src/tests/cipher.c
This is just a simple rename for variables/functions that refer to a `pgp_key_t` as `keydata`.
This is misleading since we have an actual union typedef `pgp_keydata_key_t`. Items that actually deal with `pgp_keydata_key_t` are untouched.
This is basically a relic from OpenPGP-SDK, where our `pgp_key_t` was actually `ops_keydata`.
I had this in my original large branch because 1) it makes sense and 2) it makes the names of some functions I added later less ambiguous.
=> Rename misleading keydata items to key.

src/lib/crypto.c, src/lib/crypto.h, src/lib/packet.h, src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/rnp.c, src/rnpkeys/rnpkeys.c, src/rnpkeys/tui.c, src/tests/cipher.c, src/tests/generatekey.c, src/tests/support.c
Depends on: #341 
This is an intermediate step I took when working on subkey generation (with some updates).
The last two commits are the ones relevant for this PR.
(Actually the middle commit is sort of unrelated, but is used in some future fixes)
The diff is kind of hard to read, so you're probably better off just checking out `pgp_generate_seckey` and `pgp_generate_keypair` in https://github.com/riboseinc/rnp/blob/efe2cad0aabacde3b88bf366efef60e5ccbe7fc5/src/lib/crypto.c
=> Abstract key generation a bit

ci/install.sh, src/lib/Makefile.am, src/lib/crypto.c, src/lib/crypto.h, src/lib/ecdh.c, src/lib/ecdh.h, src/lib/ecdsa.c, src/lib/ecdsa.h, src/lib/errors.h, src/lib/misc.c, src/lib/packet-create.c, src/lib/packet-create.h, src/lib/packet-parse.c, src/lib/packet-print.c, src/lib/packet-show.c, src/lib/packet.h, src/lib/signature.c, src/lib/symmetric.c, src/lib/writer.c, src/rnpkeys/tui.c, src/tests/Makefile.am, src/tests/cipher.c, src/tests/generatekey.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
This patch implements support for encryption with ECDH as specified in RFC 4880 bis 01.
Key can be generated with ``rnpkey --generate-key -expert``. Key can use any of NIST curves : P-256, P-384 or P-521.
Encryption/decryption can be done as usual with ``rnp --encrypt/--decrypt``. To do round trip one may use:
```
rnp --encrypt file.in --output file.out
rnp --decrypt file.out --output file.res
diff file.in file.res
```
Nevertheless, one more stepis needed in the development to support compatibility with ``gpg``. Currently we have 2 problems:
* GnuPG always expects that ECDH key is a subkey of ECDSA key. As it is not a case currently in ``rnp`` (and not part of RFC 4880 spec) it means we can't (yet) import key generated by ``rnp`` to ``gpg``. 
* There is also a problem in ``rnp`` when …
=> ECDH support

include/rekey/rnp_key_store.h, include/rnp/rnp_types.h, src/lib/packet.h, src/lib/pgp-key.c, src/lib/rnp.c, src/librekey/key_store_g10.c, src/librekey/key_store_g10.h, src/librekey/rnp_key_store.c, src/rnp/rnpcfg.c, src/rnpkeys/rnpkeys.c, src/tests/generatekey.c, src/tests/support.c
Hey,
It is second step of implementation librekey with GnuPG 2.1+ format support.
Right now it can use a raw key (= without password) that was generated by GnuPG 2.1+.
So, the next step is implementing support protected keys.
@dewyatt can I ask you to confirm that I did https://github.com/riboseinc/rnp/commit/c1f57ec3f5e269e4d6fd98fa7a23c68bb40d4378 in right way?
An example:
```
➜  rnp git:(librekey) ✗ rm -rf ~/.rnp                                    
➜  rnp git:(librekey) ✗ mkdir ~/.rnp 
➜  rnp git:(librekey) ✗ gpg-agent --homedir ~/.rnp --daemon
gpg-agent[83105]: directory '/Users/catap/.rnp/private-keys-v1.d' created
gpg-agent[83106]: gpg-agent (GnuPG) 2.1.21 started
➜  rnp git:(librekey) ✗ cat > gpg-script                                 
Key-Type: 1
Key-Length: 2048
Subkey-Type: 1 …
```
=> librekey step two

src/lib/signature.c, src/lib/writer.c
Fixes #206 (actually that is already fixed but this aims to be more thorough)
I was able to condense/simplify a lot of the code in here as well since the cleartext and non-cleartext signature cases have few differences. I suspect a lot of this can be factored out further (like `pgp_sign_buf` and `pgp_sign_file` could probably use a shared function for the bulk of the operation), but did not attempt this for now.
This also fixes some memory leaks for certain cases with `pgp_create_sig_delete`.
We don't appear to have test coverage for `pgp_sign_file` or `pgp_sign_detached` so I did some quick checks with rnp and gpg manually. No tests added because I'm trying to focus on password handling and FFI.
=> Take care of of pgp_sig_write unchecked return values

src/lib/compress.c
This short pull request fixes issue #378 
Actually, decompression didn't work well at all.
=> Fix for incorrect output buffer offset handling in zlib_compressed_data_reader

configure.ac, remove_artifacts.sh, src/Makefile.am, src/compat/Makefile.am, src/compat/explicit_bzero.c, src/lib/Makefile.am, src/lib/misc.c, src/lib/rnp.c
Fixes #263 
Two things here:
* Use `explicit_bzero`/`explicit_memset`/`memset_s` in `pgp_forget` to ensure that the crucial piece of code is not optimized out. I pulled in a public domain implementation of `explicit_bzero` from libressl as a fallback. It's built as a separate static lib with no optimization (you'll probably see both -O2 and -O0 on the command line but the last option takes effect - room for improvement there). Most BSDs and Linux w/glibc >= 2.25 have `explicit_bzero` or `explicit_memset` available. I *think* macOS has `memset_s`. For Windows we'll probably eventually want to use `SecureZeroMemory`. None of these functions are very portable, but it's a start.
* Add a few more `pgp_forget` calls in to `find_passphrase`. The `find_passphrase` function is still a bit wonky …
=> Ensure pgp_forget always zeros things

src/lib/packet-print.c, src/lib/rnp.c
Just a minor change to address [this comment](https://github.com/riboseinc/rnp/pull/285#issuecomment-313824599). I didn't do proper error handling at the call site here because that whole function needs a lot of rework with regards to that, and there are much higher priority items in rnp.
I also renamed the "flags" entry in the JSON to "key flags" to fit better with f10588d25a11e737aacd0a5e14115cc4d2cf30f7.
I think we can close #35 with this.
=> Change key flags JSON to be an array of strings.

src/lib/crypto.c, src/lib/rnp.c, src/lib/signature.c, src/lib/signature.h, src/lib/writer.c, src/tests/cli_tests.py
This PR was first targeted to solve issue #383 - problem with verification of armored messages with 'BEGIN PGP MESSAGE' header.
However together with it I consolidated all armored writers/finalizers and removed duplicated code.
I tested it mostly manually/with GPG - since looks like we have some major problems with dearmoring right now. Will write about it in other issue.
Also it has a minor CLI test update for signing/verification test.
=> Consolidate and remove duplicate armouring code

src/lib/crypto.c, src/lib/crypto/sm2.c, src/lib/crypto/sm2.h, src/lib/generate-key.c, src/lib/packet-create.c, src/lib/packet-parse.c, src/lib/packet-print.c, src/lib/packet-show.c, src/lib/packet.h, src/lib/pgp-key.c, src/lib/signature.c, src/librekey/rnp_key_store.c, src/rnpkeys/tui.c, src/tests/cipher.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
Adds support for SM2 encryption. (#127)
The SM2 ciphertext has a specific form (it's a triplet of an ECC point, the masked plaintext, and a SM3 hash that serves as an authenticator). However here it's just formatted as a BIGNUM holding an opaque block of bits. Which I think is fairly consistent with OpenPGPs approach to such things (eg using a single BIGNUM to hold ECC points).
Testing on the command line, keygen and encrypt/decrypt round trip work ok. Of course there is no other implementation to test this against. so maybe I made some dumb mistake.
I changed `rnpkeys` so SM2 signature key get an encryption subkey. I'm not totally sure this is the correct approach.
=> Add support for SM2 encryption

src/lib/crypto.c, src/lib/generate-key.c, src/lib/packet-create.c, src/lib/packet-create.h, src/lib/packet-parse.c, src/lib/packet-parse.h, src/lib/packet.h, src/lib/reader.c, src/lib/rnp.c, src/lib/symmetric.c, src/lib/symmetric.h, src/lib/writer.c, src/librekey/key_store_ssh.c, src/tests/cipher.c
The big change here is replacing the combination of `pgp_crypt_any`, `pgp_decrypt_init`, `pgp_cipher_set_iv` and `pgp_cipher_set_key` with the combination function `pgp_cipher_start` which does all of these operations on one go. Also while I could still not make the cipher structure opaque I at least change all code to not touch any fields in it except (in a couple of spots) `alg`.
Also removed several completely unused functions `pgp_decrypt_se`, `pgp_encrypt_se`, `pgp_write_symm_enc_data` and  `pgp_cipher_block_decrypt`, and removed `pgp_cipher_block_encrypt` since it was only called in one spot that was accessing internal structures of the cipher struct, so I hide the operation behind a new function `pgp_cipher_cfb_resync_v2` (which could use a better name).
More changes in this area …
=> Cleanups in symmetric cipher code

.travis.yml, Developers Guide.md, ci/install.sh, ci/main.sh, packaging/redhat/extra/prepare_build.sh, src/tests/cli_tests.py
Fixes https://github.com/riboseinc/rnp/issues/394#issuecomment-323879018
I also realized my mistake of setting CORES based on /proc/cpuinfo in Travis CI. The container's /proc/cpuinfo matches the host, of course, so sometimes we were trying to build botan and other things with 32 cores in a travis-ci container (which resulted in processes being killed). Now defaults to 2 cores and can be overridden.
=> Add GPG 2.1 to CI and run cli_tests.py

src/lib/compress.c, src/lib/compress.h, src/lib/writer.c, src/tests/pgp-parse.c
Also fixes bzip2 compression which called the wrong shutdown function `BZ2_bzDecompressInit` instead of `BZ2_bzDecompressEnd` - and so always crashed... Also fix what appears to be an off by one in the decompression code that caused bzip2 (but not zlib) to fail.
I've updated the test to check compression roundtrips, but this does not update the CLI (#359). I don't see a good way to pass any arguments/options to `encrypt_se_ip_writer` so maybe some more refactoring is required to get that to work.
=> Add support for bzip2 and zip (deflate) compression

src/lib/symmetric.c, src/lib/symmetric.h, src/librepgp/reader.c
This took way longer than I expected because I figured it was just an issue of implementing CFB resync correctly. It turned out there were also two bugs in `reader.c` that meant reading a V3 encrypted key almost certainly never worked (including in NetPGP, based on the history).
First, the resync call happened in the wrong time, which screwed up the IVs. Additionally, when copying the unencrypted v3 MPI lengths, it copied them into an offset. So what ended up happening is RNP would interpret the first 2 bytes of the decrypted modulus (still around in the buffer at offset 0) as the length of the following MPI. This would fail due to either being a seemingly invalid length or else cause corruptions. So it seems like there is no way this could have worked.
Anyway I confirmed that with this …
=> Fix decryption of V3 keys

src/rnpkeys/rnpkeys.c
Otherwise you may do something like:
```
rnpkeys --gen-key --numbits 1024
```
And you'll get a primary key 1024-bit RSA key but a 2048-bit (the default) subkey.
=> Copy primary crypto params to subkey crypto params in non-expert mode.

src/lib/compress.c, src/lib/writer.c, src/librepgp/reader.c, src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/tests/cli_common.py, src/tests/cli_tests.py, src/tests/perf_tests.py
- Added --zlib, --zip and --bzip2, -z 0..9 parameters to the rnp commandline and implemented their handling. Since compression now is used only during encryption it works only in this case.
- Fixed hanging bug in bzip2 decompression
- Updated CLI tests with more compression/decompression cases
- (hopefully) Fixed possible random CLI tests crash in Travis
- fixes #359
=> Added compression parameters selection to CLI

src/lib/crypto/rsa.c
As per RFC 4880 p should be less then q for the RSA key. Otherwise generated key could behave wrong with GnuPG because of some optimized calculations which most likely utilize this fact.
This fixes #400.
=> Ensure that p < q in the generated RSA key.

src/lib/crypto.c, src/lib/readerwriter.h, src/lib/symmetric.c, src/lib/symmetric.h, src/lib/writer.c, src/lib/writer.h
First step of #412.
Each OpenPGP block can be up to 4Gb size and in case if someone try to encrypt file >= 4Gb we should use the parital encoding.
Good new: we have this code and looks like it works.
Bad news:
- we haven't got decryption code :(
- sometime GnuPG can't decode the file that rnp provides.
But I'm using 'crypto-container' (gpg encrypted archives, from few gigabytes up to handreds gigabytes) and I can say that GnuPG not at all time can decrypt bigger file that it created :)
=> One OpenPGP block can't be bigger than 0xffffffff, so, switched to streaming if it required

LICENSE-OCB.md, LICENSE.md
Allow us to thank Prof. Phillip Rogaway for granting an OCB license to `rnp` users! 👍
A quote from him:
> My real reward [...], has always been in the pleasure of doing crypto and seeing a bit of
it get into the world.
OCB should be made default in `rnp`.
=> Provide OCB license.

src/lib/crypto.h, src/lib/generate-key.c, src/lib/packet-create.c, src/lib/packet-create.h, src/lib/readerwriter.h, src/lib/symmetric.c, src/lib/types.h, src/lib/writer.c, src/librepgp/packet-parse.c
This is based on the branch in https://github.com/riboseinc/rnp/pull/431 so that should be merged first. The last 4 commits are the ones relevant here.
Note: This adds the functionality for writing unencrypted keys but it does *not* use it yet.
This also cleans up a lot of the error handling in some of these functions.
My plan here is to:
* Add support for writing unencrypted pgp seckeys.
* Use unencrypted keys during key generation. (See below point)
* Add the concept of protect/unprotect. Will take care of things like those mentioned [here](https://github.com/riboseinc/rnp/issues/231#issuecomment-310108861).
* Do a few other things to get G10 support working again.
=> Add support for writing unencrypted pgp seckeys

src/lib/rnp.c
So we can't be sure does this key can be used to signing.
This commit just switched to using pubring that is GPG or KBX and keeps metadata.
=> G10 keystore doesn't keep a key metadata likes `key_flags`.

src/lib/packet-create.c
Looks like this was mistakenly using the rsa field.
=> Fix SM2 session key packet length.

src/lib/packet-create.c
It looks like this was accidentally dropped in https://github.com/riboseinc/rnp/pull/422, SM2 encryption fails without it.
We have tests for the lower-level SM2 enc/dec, but not for this particular piece so it wasn't caught.
=> Re-add SM2 to allowed algs for pgp_create_pk_sesskey.

src/lib/crypto/sm2.c, src/lib/signature.c, src/lib/types.h
This passed "Raw" but for SM2 the parameter is the associated userid, not the hash. Instead leave it empty.
Remove .ecdsa sig type from union and use .ecc everywhere since the same format is used for all ECC signature methods (ECDSA, SM2, EDDSA)
Inline hash_and_check_sig into its only caller, minor simplification.
=> Correct SM2 signature ID

src/lib/crypto/sm2.c, src/lib/crypto/sm2.h, src/lib/packet-create.c, src/tests/cipher.c
Also appends a byte to the encrypted packet that specifies what hash was used, which matches the draft text.
The actual call in pgp_create_pk_sesskey still hardcodes SM3, this should I guess take the hash from the key's hash preferences?
Requires recent Botan with https://github.com/randombit/botan/pull/1188. I will clear the Travis cache so it gets rebuilt.
=> Support arbitrary hashes for SM2 encryption KDF/integrity check

src/lib/pgp-key.c
We added this originally in [PR 181](https://github.com/riboseinc/rnp/pull/181/files) because netpgp CVS added it, but they
probably added it because they don't actually support unencrypted
(password-less) keys, which we now do.
It's really inefficient to try decryption twice for each decryption
attempt, so it seems best to remove this now.
=> Remove empty passphrase decryption attempt.

src/tests/key-unlock.c, src/tests/support.c, src/tests/support.h
This just makes this test a little more thorough.
I also moved the passphrase callbacks to support because I used them in some other tests (future PR).
=> Improve key lock test

ci/main.sh, src/tests/cli_tests.py
It looks like CI isn't always finding the correct gpg, for whatever reason, so it's likely safest to just provide an explicit path.
I just used the environment here, but an arg would certainly work as well. It still falls back to the normal search.
=> tests: Provide explicit path for gpg to cli_tests.py.

include/repgp/repgp.h, src/lib/crypto/ecdh.h, src/librepgp/repgp.c, src/rnp/rnp.c
REPGP_HANDLE_NULL was useful when functions were returning or accepting
pointers to void. Later this has been simplified. Currently API
functions accept or return pointers to types which are forward-declared.
At the moment REPGP_HANDLE_NULL can be simply replaced with NULL.
Also improves some comments in ECDH
=> repgp: Use NULL instead of REPGP_HANDLE_NULL

src/lib/types.h, src/librekey/key_store_g10.c
Since this is no longer used in pgp_seckey_t. Just a minor thing I noticed this morning.
=> Rename/move G10_PROTECTED_AT_SIZE.

src/lib/crypto.c, src/lib/crypto.h, src/lib/crypto/bn.c, src/lib/crypto/bn.h, src/lib/crypto/dsa.c, src/lib/crypto/ecdh.c, src/lib/crypto/ecdh.h, src/lib/crypto/elgamal.c, src/lib/crypto/rsa.c, src/lib/packet-create.c, src/lib/pem.c, src/librekey/key_store_g10.c, src/tests/cipher.c, src/tests/support.c, src/tests/support.h
All super piddly stuff actually but I noticed it while looking at something else and it bugged me.
Basically don't include `<botan/ffi.h>` in any headers, just in the files that directly use it. Changes ECDH interface slightly (taking BIGNUM instead of botan_mp_t)
Removes `new_BN_take_mp` because it was only used in one place and the code is simpler without it.
The BN layer is due for a pruning, a lot of functionality in there was just to implement ElGamal etc and is no longer necessary. But not really a problem so ignoring that here.
=> Clean up inclusion of botan/ffi.h

include/repgp/repgp_def.h, src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/rnp.c, src/librekey/key_store_pgp.c, src/librekey/key_store_pgp.h, src/tests/Makefile.am, src/tests/key-add-userid.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
Ok I had to expand this PR and fix an unrelated issue or CI would be broken.
So this:
* Fixes key importing (https://github.com/riboseinc/rnp/issues/21). I've only tested .gpg format. It would likely (should) fail for imports that require conversions (like importing a G10 key into a GPG key store).
* Support secret keys.
* Actually save to disk.
* Adds some support+tests for adding additional userids to keys.
=> Add support for adding additional userids to keys, fix key importing

src/lib/misc.c
I encountered a tricky bug while working on FFI and had to track this down.
Previously, strings like "test1" and "test198281939823" would compare equal. I ran some tests on random strings of random lengths for 10 min or so and confirmed this produces correct results (compared to a known-good impl).
=> Fix rnp_strcasecmp.

include/rekey/rnp_key_store.h, src/lib/rnp.c, src/librekey/key_store_g10.c, src/librekey/key_store_g10.h, src/librekey/key_store_kbx.c, src/librekey/key_store_kbx.h, src/librekey/key_store_pgp.c, src/librekey/key_store_pgp.h, src/librekey/rnp_key_store.c
I noticed these are no longer used anywhere, so it seems best to remove them (maybe slightly safer).
=> Remove passphrase parameters from key store interfaces.

src/tests/cipher.c
It expected the ciphertext size the match that from the IETF draft, but Botan has changed (in  https://github.com/randombit/botan/pull/1218) to use the ASN.1 formatting instead.
=> Fix SM2 test

src/lib/crypto/s2k.c, src/lib/crypto/s2k.h, src/lib/packet-create.c, src/lib/types.h, src/librepgp/packet-parse.c, src/librepgp/stream-parse.c, src/librepgp/stream-write.c
This PR:
- adds `pgp_forget` in some places, fixing #473 
- renames pgp_s2k to pgp_s2k_t
- removes some s2k-related code duplication by using new function pgp_s2k_derive_key
=> Review pgp_forget usage in #463, some s2k refactoring

include/repgp/repgp_def.h, include/rnp/rnp_types.h, src/lib/Makefile.am, src/lib/key-provider.h, src/lib/pgp-key.h, src/lib/rnp.c, src/lib/types.h, src/librepgp/Makefile.am, src/librepgp/stream-armour.c, src/librepgp/stream-common.c, src/librepgp/stream-common.h, src/librepgp/stream-packet.c, src/librepgp/stream-packet.h, src/librepgp/stream-parse.c, src/librepgp/stream-parse.h, src/librepgp/stream-write.c, src/librepgp/stream-write.h, src/rnp/rnp.c, src/tests/cli_tests.py
This PR completely moves encrypt and decrypt commands (including password-only encryption) to the streamed approach.
Also it makes rnp ready for multiple-recipient encryption and decryption, just some minor CLI modifications are required.
It doesn't remove old encrypt/decrypt functionality - I think it would be better to remove it when signing/verification and cleartext operations will be updated to use streamed approach as well.
It is the part of the issue #424
=> Streamed PK-based encryption and decryption

src/lib/packet-create.c, src/lib/signature.c, src/lib/signature.h
I ran into a tricky issue with some local changes, and I saw tests aren't catching it, so this is just trying to improve some error checking in this area.
(`signature.c` still has a lot of room for improvement on error checking, but I'm just doing this one piece since it caused me some trouble.)
=> Check pgp_build_pubkey return value (and callers).

src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/rnp.c, src/lib/rnp2.c, src/librepgp/stream-write.c
Code was trying to encrypt always with primary key. Primary keys are mostly used for signing.
With this patch code will check if key used for encryption has PGP_KF_ENCRYPT flag, if not it will try to look in subkeys for encryption key. It will fail if proper key is not found
=> repgp: Check usage flag before encrypting

src/librekey/key_store_pgp.c, src/tests/generatekey.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
I noticed our `key->subsigs` always have NULL MPIs for v4 sigs and realized we weren't properly loading these.
During the `CT_SIGNATURE_HEADER` callback, the sig MPIs haven't been populated yet (need to wait for `CT_SIGNATURE_FOOTER`). `CT_SIGNATURE_HEADER` is more of a heads up before the subpackets start flooding in (so we use it to expand the array).
Anyways, I went ahead and wrote some lengthy tests for generated keyring sigs.
(netpgp cvs appears to still have this issue for v4 sigs, so I guess we inherited it)
=> Fix PGP keyring subsig MPI loading, add tests.

include/rnp/rnp.h, src/lib/rnp.c, src/rnpkeys/rnpkeys.c, src/rnpkeys/rnpkeys.h, src/rnpkeys/tui.c, src/tests/generatekey.c
As mentioned in #344 the ECDH key generated by rnp can't be imported to GnuPG and other way around. At the time ECDH was implemented the functionality needed for generation a key with a subkey wasn't fully supported.
Needed functionality for subkey generation is now implemented so we can carry on with ECDH key generation, so that it's compatible with GnuPG
Closes #488
=> Generate ECDH key as subkey to ECDSA key

build_common.inc.sh, src/tests/cli_perf.py
In order to eliminate slow disk accesses and speed up performance testing, it would good to have possibility to use ramdisk for perf testing.
This patch adds possibility to optionally specify working directory.
=> Possibility to specify working directory for perf tests

src/lib/pass-provider.c, src/lib/pass-provider.h, src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/tests/cli_common.py, src/tests/cli_perf.py
This PR adds --passphrase command line parameter handling, and introduces 'string' password provider. Also it updates performance test with some fixes and improvements.
It was added for easier handling of passphrase in performance and CLI tests, however most likely users will make use of it as well. Despite the fact of quite low security properties of such approach.
=> Passphrase command line parameter

src/lib/crypto/ecdsa.c, src/lib/crypto/ecdsa.h, src/lib/signature.c, src/rnpkeys/tui.c
It seems from some time, we require user to provide a hash algo to be used when signing with ECDSA. For some cases it may be good idea, but for majority of cases this process should be automatic.
With this fix ``rnp`` will chose hash which can be used with given curve securely.
=> Don't require from user to provide ``--hash`` for signing with secp384r1 and secp521r1

include/rnp/rnp.h, include/rnp/rnp_types.h, src/lib/rnp.c, src/librepgp/stream-armour.c, src/librepgp/stream-armour.h, src/rnp/Makefile.am, src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/tests/cli_tests.py
Option that makes it possible to convert from binary format to ASCII Armor. This functionality was mainly implemented in order to test performance of pure base64 implementation, but I found it may be useful for anybody who wants to convert from one format to another (for whatever reason).
Usage:
```
rnp --enarmor=msg input > middle
rnp --dearmor middle > output 
> diff input output
>
```
=> (rnp) Adds option symmetric to --dearmor

src/tests/rnp_tests.c
On my system, the copy_recursively function prints out some
complaints when the current directory doesn't exist.
(You can see this on travis too - it's more of a nuisance than an actual issue)
=> tests: Re-arrange test data copy order.

src/lib/pass-provider.c
This is just to prevent the (unlikely) possibility of truncating a password with the strncpy below.
=> Make string passphrase provider a bit stricter.

include/rnp/rnp.h, include/rnp/rnp_types.h, src/lib/rnp.c, src/librepgp/stream-common.c, src/librepgp/stream-write.c, src/rnp/rnp.c
The main thing here is just moving password retrieval out of the `init_encrypted_dst` code path and instead deriving the key for passwords immediately.
Also adds support for setting the s2k cipher that will wrap the session key (when applicable). (We'll probably want to add a `--s2k-cipher` CLI arg at some point)
The reason for this change is that with FFI I'm aiming to use password parameters directly when possible. It just makes for a very awkward API in some places otherwise.
I will admit that in some ways this could be viewed as less secure since previously I believe the pass+derived key were isolated to one function, and now the key ends up in `ctx->passwords` until used. I think it's practically no difference though and is a decent compromise.
=> Change symmetric password encryption to not use provider in lower layers

src/lib/fingerprint.c, src/lib/misc.c, src/lib/rnp.c, src/lib/utils.h, src/librekey/key_store_kbx.c, src/librepgp/stream-packet.c, src/librepgp/stream-write.c, src/librepgp/validate.c
The define was accidentally named STORE32LE, while actually it is BE.
=> Fix wrong define name, which is actually big-endian.

Developers Guide.md
This is a change I'd like to suggest to avoid issues like de4165f4ff46ec4c1a6bee3fd0e670b5a4fc5f80.
It's a minor thing, but basically this guideline is suggesting "default to failure" so that in the cases like the above, if you forget to set an appropriate error code, the function won't return success even when it actually failed.
IOW, do this:
```c
rnp_result_t ret = RNP_ERROR_GENERIC;
// later on, if all is well
ret = RNP_SUCCESS;
done:
return ret;
```
Instead of:
```c
rnp_result_t ret = RNP_SUCCESS;
if (something_failed) {
// forgot to set ret here!
goto done;
}
done:
return ret;
```
=> docs: Update dev guide with info on ret variable initial values.

ci/main.sh, src/lib/hash.c, src/lib/utils.h, src/tests/cli_common.py, src/tests/cli_perf.py, src/tests/cli_tests.py
3 misc changes in 3  separated commits :
* Removes code duplication for hash interface
* Use 'unitests' python module for CLI tests
Use unittest python module to do CLI tests
This way we will be able to choose test to
run
This is done in order to be able to run single
test during development process. Example:
```./src/tests/cli_tests.py -f  -v Keystore.test_generate_with_rnp_import_to_gpg```
This patch removes '--debug' cmd line option.
Instead '-v' and '-f' options should be used
For more details on how to run the tests issue
./src/tests/cli_tests.py -h
* Refactors cli_performance tests in order to
be able to run single test during development process
For more info how to do it, run:
```./src/tests/cli_perf.py -h```
Example: ```./src/tests/cli_perf.py large_file_armored_decryption```
=> Misc changes for CLI tests and hash interface

src/lib/crypto/ecdh.c, src/lib/crypto/ecdsa.c, src/lib/crypto/sm2.c, src/lib/generate-key.c, src/lib/hash.c, src/lib/packet-create.c, src/lib/rnp2.c, src/librekey/key_store_g10.c, src/librekey/key_store_kbx.c, src/librekey/key_store_pgp.c, src/librekey/rnp_key_store.c, src/librepgp/packet-print.c, src/librepgp/reader.c, src/rnp/rnpcfg.c, src/tests/cipher.c, src/tests/generatekey.c, src/tests/rnp_tests.c, src/tests/user-prefs.c
As per discussion at https://github.com/riboseinc/rnp/pull/539#discussion_r152394006 I checked code with `-Wsign-compare`, and introduced required fixes.
This PR doesn't add changes to the streamed code to avoid merge problems since they were added in PR #539.
@dewyatt @ronaldtse @flowher  Probably we should add `-Wsign-compare` to default build options, or travis checks, what do you think?
=> Fix code to be compliant with -Wsign-compare

include/repgp/repgp_def.h, include/rnp/rnp_sdk.h, include/rnp/rnp_types.h, src/lib/misc.c, src/lib/rnp.c, src/lib/types.h, src/librepgp/packet-parse.c, src/librepgp/packet-print.c, src/librepgp/stream-armor.c, src/librepgp/stream-armor.h, src/librepgp/stream-common.c, src/librepgp/stream-common.h, src/librepgp/stream-packet.c, src/librepgp/stream-packet.h, src/librepgp/stream-parse.c, src/librepgp/stream-parse.h, src/librepgp/stream-write.c, src/rnp/rnp.c, src/tests/cli_tests.py
This PR adds streamed approach for signature verification (signing will be done later, as separate PR).
- signed source type (it is called 'signed', however it is for verification purpose)
- cleartext signed source type (kinda subtype of signed source)
- detached signatures processing (as part of the signed source)
- minor very rare bug in cleartext signature verification, which I will fix later
- on_signatures event to handle verification results by callee
- src_provider to provide source for detached signature.
- method process_pgp_source was divided to some submethods for readability
- moved to list instead of DYNARRAY, seems to be much easier and nicer in handling
- some code partially duplicates old codebase and types - this is just because old code will be removed once streamed …
=> Streamed signature verification

src/lib/hash.c, src/lib/hash.h, src/lib/types.h, src/librepgp/stream-armor.c, src/librepgp/stream-common.c, src/librepgp/stream-common.h, src/librepgp/stream-packet.c, src/librepgp/stream-parse.c, src/librepgp/stream-write.c
This PR includes some improvements over streamed code which I noticed but didn't include into the previous PR:
- added common initialization functions, removed duplicate zero-initializations
- replaced default RNP_SUCCES for return code (thanks to @dewyatt for noticing some time ago)
- shortcuted iteration over lists of items
- replaced DYNARRAY with list for signature subpackets
- added pgp_hash_list_* functions to use them later in streamed signing
=> Streamed processing improvements

src/rnp/rnp.c
Just a minor thing here that my compiler has been complaining about (refuses to build).
=> Initialize title variable in rnp_on_signatures.

src/librekey/key_store_pgp.c, src/tests/load-pgp.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
It looks like we inherited this from netpgp. The PGP packet parsing library already handles these particular subpackets, so the keyring loading code should not duplicate that. (We copy this stuff when handling `PGP_PTAG_CT_SIGNATURE_FOOTER`)
Also adds a couple of tests that are focused on this somewhat.
=> Remove duplicate signature subpkt handling

src/lib/rnp.c, src/lib/rnp2.c, src/librekey/rnp_key_store.c, src/librepgp/stream-common.c, src/librepgp/stream-common.h, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.c, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/gnupg.py, src/tests/rnp.py
Implements ECDSA tests against GnuPG
* Introduces two wrappers around rnp (rnp.py) and gpg (gnupg.py)
* Tests sign with either gpg or rnp and verify with the other one
* ``rnpkey`` got possibility to export key to file 
Closes #516
=> ECDSA tests against GnuPG

src/librepgp/stream-armor.c, src/librepgp/stream-def.h, src/librepgp/stream-parse.c
These constants will be needed in cleartext streamed signing. Also there were some places for the same double-defined constants.
I didn't touch old code (like reader.c, writer.c) as it will be removed once streamed signing is finished.
=> Move character/string constants to the separate file

src/librepgp/stream-write.c
GCC warns about this and it seems bogus to me, @ni4 can you look?
=> Fix a bad pointer comparison

src/lib/rnp.c, src/tests/cli_tests.py
Bug introduced by me, myself and I.
=> (rnpkeys) Return NULL if key was not found

src/lib/crypto.c, src/lib/packet-create.c, src/lib/rnp.c, src/lib/signature.c, src/lib/types.h, src/librekey/key_store_kbx.c, src/librekey/key_store_pgp.c, src/librekey/key_store_ssh.c, src/librepgp/packet-parse.c, src/librepgp/packet-print.c, src/librepgp/validate.c, src/librepgp/validate.h, src/rnp/rnp.1, src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/tests/key-add-userid.c, src/tests/load-pgp.c, tests/tst
This PR renames birthtime to 'creation' and duration to 'expiration' which are used in RFC.
Closes #329
=> Rename 'birthtime' and 'duration' to more applicable names

src/librekey/key_store_g10.c
The main thing here is the trailing byte. I added the `block->len` check as well since I don't think that case would be valid.
I also noticed the sizeof portion of this isn't really correct, but it doesn't look like a big deal so I'm not touching it here. I'm not sure that value can really be determined at compile-time, you would probably want to use log10 or snprintf or use a fixed upper value etc.
=> Fix uninitialized data used in G10 keys.

src/librepgp/stream-armor.c
I think maybe this was overlooked when introducing `init_dst_common`? Some uninitialized data was being used because of this.
=> Fix uninitialized data use for armored writing.

src/librekey/key_store_kbx.c
I suspect we may have other similar bugs lurking around. This has to do with `realloc` (used in `pgp_memory_pad`) having the potential to invalidate held pointers.
=> Fix heap use-after-free in KBX.

src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/rnpkeys/main.c, src/rnpkeys/rnpkeys.c, src/tests/Makefile.am, src/tests/generatekey.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h, src/tests/utils-rnpcfg.c
During work on multiple signers/recipients I needed to allow storage of lists in rnp_cfg_t.
So redesigned it to work with list, and allow storage of typed information. Maybe this is overhead a bit  but, at least, it would be much more flexible for future needs.
So now all values stored in rnp_cfg_t have defined type and may be int, bool, char * (string) or list. Last one may contain the same value types stored in rnp_cfg_val_t.
=> Update rnp_cfg_t to allow storage of lists

ci/main.sh, src/librepgp/stream-parse.c, src/tests/cli_tests.py
This PR:
- fixes gpg key generation test
- reduces number of encryption test runs (we really don't need to run each file size for each algorithm, just need to check all algos/all sizes/all compression algorithm combinations)
- enables debug logging for CI
- fixes buffer underflow in cleartext_process_line (see https://github.com/riboseinc/rnp/pull/581#issuecomment-360343555)
=> Fix errors in key generation tests and some other CLI test improvements

src/lib/generate-key.c, src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/rnp.c, src/librekey/key_store_kbx.c, src/librekey/key_store_pgp.c, src/librekey/rnp_key_store.c, src/librepgp/stream-write.c, src/tests/load-pgp.c
This was done to avoid holding invalid pointers and such, from when the key store used a dynarray to store keys. But it's still nice to avoid having a key that points to a subkey that is actually in another store and similar oddities.
=> Replace pgp_key_t subkey dynarray with a grip list.

include/repgp/repgp_def.h, include/rnp/rnp_types.h, src/lib/packet-create.c, src/lib/symmetric.c, src/lib/symmetric.h, src/lib/types.h, src/lib/utils.h, src/librekey/key_store_ssh.c, src/librepgp/packet-parse.c, src/librepgp/reader.c, src/librepgp/stream-common.c, src/librepgp/stream-common.h, src/librepgp/stream-packet.c, src/librepgp/stream-packet.h, src/librepgp/stream-parse.c, src/librepgp/stream-write.c, src/rnp/rnp.c, src/rnp/rnpcfg.h, src/tests/cipher.c, src/tests/cli_tests.py
This PR implements AEAD-EAX encryption mode as defined in rfc4880bis-03.
It implements AEAD-EAX for SESK and AEAD encrypted data packet, but do not implement it for secret key encryption (this will be implemented separately, when key loading/saving will be moved to streams).
Also rfc4880-03 seems to introduce changes in AEAD format soon, once they will be published I'll reflect them to the rnp.
To enable AEAD encryption mode just add `--aead` to the encrypting command line.
Some changes are just strange behavior of clang-format, will re-check it.
=> AEAD-EAX encryption support

include/rekey/rnp_key_store.h, src/lib/packet-create.c, src/lib/pgp-key.c, src/lib/pgp-key.h, src/lib/rnp.c, src/librekey/rnp_key_store.c, src/tests/cli_tests.py, src/tests/gnupg.py, src/tests/rnp.py
I would like to propose functionality for exporting primary key with all subkeys (public). This patch adds such functionality to ``rnpkeys --export`` (previously ``--export`` was exporting only primary key). This operation is exact opposite to ``--import`` which imports primary key + subkeys. It's also similar to what's implemented in GnuPG.
Additionally the patch:
* Adds tests for ElGamal decryption against GnuPG encrypted data (this and coming tests for ECDH are main reasons why I need to have possibility to export subkeys). Those tests are also testing public-key export
* Fixes ``cli_tests.py`` - I've found out that after tests are done, in some cases, keys and workfiles are not removed, which is causing clashes and some other tests to break
=> Subkey export and tests for ElGamal decryption

src/lib/crypto/ec.c, src/lib/crypto/ec.h, src/lib/crypto/ecdh.c, src/lib/crypto/ecdh.h
* According to point RFC 4880bis04 (13.5) size of symmetric encryption key
can be padded to 40 bytes (obfuscated) or padded to 8 nearest byte granularity.
When encrypting, our implementation was padding the key to 40 bytes,
but this is incompatible with GnuPG implementation (2.3.0-beta190). Also
it is questionable how much security such solution bring. Also there is
a bug in the RFC which states that PKCS5 padding must be used when
padding symmetric key before it gets wrapped with AES-wrap. This makes
it impossible to obfuscate size of the key to 40 bytes.
Hence, I've change our implementation to pad symmetric key to nearest
8 byte granularity.
For more details see: https://dev.gnupg.org/T3763
* Some cleanup and removal of unnecessary checking against NULL was introduced
* When computing …
=> Fixes for ECDH encryption and decryption

src/tests/cli_tests.py
Encryption and decryption tests for ECDH against GnuPG
Requires: #605 and #607 to be merged before (otherwise tests will break)
Closes #27
=> (tests) ECDH tests against GnuPG

src/tests/cli_tests.py
The ElGamal decryption code was broken for some time already.  Now we can see it because we have tests.... and they fail.
I know what needs to be fixed, but until it is done I propose to skip ElGamal decryption tests.
=> Skip ElGamal decryption tests

include/repgp/repgp_def.h, include/rnp/rnp_types.h, src/lib/packet-create.c, src/lib/symmetric.c, src/lib/symmetric.h, src/lib/types.h, src/lib/utils.h, src/librepgp/stream-def.h, src/librepgp/stream-packet.c, src/librepgp/stream-parse.c, src/librepgp/stream-write.c, src/rnp/rnp.c, src/rnp/rnpcfg.h, src/tests/cli_tests.py
This PR adds support for AEAD-OCB encryption mode and ensures compatibility with latest GnuPG development build.
It updates CLI tests to check AEAD implementation against GnuPG (if it has AEAD implementation).
To select AEAD algorithm CLI parameter `--aead[=EAX|=OCB]` should be used.
Also (mostly for tests) you may control AEAD chunk size as per RFC4880bis via `--aead-chunk-bits` parameter.
=> AEAD OCB mode and GnuPG compatibility

include/rnp/rnp_def.h, src/lib/crypto/s2k.h, src/lib/defaults.h, src/lib/generate-key.c, src/lib/hash.c, src/lib/pgp-key.c, src/lib/rnp.c, src/lib/rnp2.c, src/lib/symmetric.c, src/lib/utils.h, src/rnp/rnp.c, src/rnp/rnpcfg.c, src/tests/generatekey.c
This PR moves all default algorithms and other constants related to default parameters selection to single defaults.h header.
We use cast5 as default symmetric algorithm, and, at least, AEAD without --cipher parameter doesn't work (since cast5 has 8-byte block).
RFC4880bis has AES-128 as a single MUST-implement algorithm. However, since ffi already used AES256, and GnuPG uses it as default, I replaced cast5 with aes256.
=> Add defaults.h and change default symmetric cipher to AES256

src/tests/cipher.c
This is just to prevent travis-ci from thinking the process is hung.
This test is pretty thorough and takes 5x longer than all the other `rnp_tests` combined, so travis-ci will sometimes kill it after 10 minutes of no output.
Obviously there's a few other ways to handle this, but this is simple and should work.
=> Add a printf to test_dsa_roundtrip.

src/tests/generatekey.c
It looks like `setup_rnp_common` duplicates some things that `rnpkeys_init` does, and a few tests were missing `rnp_end`.
=> Fix leaks in tests with ask_expert_details.

include/repgp/repgp_def.h, include/rnp/rnp2.h, src/lib/pgp-key.h, src/lib/rnp2.c, src/tests/ffi.c
I didn't get a chance to review #621 originally but I looked back and fixed some issues I saw:
* Updated to handle locked keys.
* Adds uid to both pub and sec keys (depends on keyring format a bit).
* Fixed a small mem leak.
=> Fix up rnp_key_add_uid to handle locked keys and add uid to both keys.

.travis.yml, include/rnp/rnp2.h, src/lib/crypto/sm2.c, src/lib/pgp-key.c, src/lib/rnp.c, src/lib/rnp2.c, src/librekey/key_store_g10.c, src/librepgp/packet-parse.c, src/librepgp/reader.c, src/librepgp/stream-parse.c, src/librepgp/validate.c, src/librepgp/validate.h, src/rnpkeys/main.c, src/rnpkeys/rnpkeys.c, src/tests/cipher.c, src/tests/ffi.c, src/tests/generatekey.c, src/tests/key-add-userid.c, src/tests/key-unlock.c, src/tests/pgp-parse.c, src/tests/utils-list.c
**Note**: The other PRs I have open should be merged before this one so that we can see the sanitize-leaks CI run pass. (I expect it to fail here initially)
Right now in master `rnp_tests` leaks quite a bit for me:
```SUMMARY: AddressSanitizer: 265317 byte(s) leaked in 1587 allocation(s).```
This, combined with the other PRs, should get us back to 0 so that we can re-enforce the sanitize-leaks CI run. (Hoping to add a valgrind run soon too)
=> Fix leaks in rnp_tests and re-enforce sanitize-leaks CI run.

src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h
Since stdin is now processed in streamed manner this parameter is no longer needed.
=> Remove max-alloc CLI parameter

src/rnp/rnp.c, src/rnp/rnpcfg.c, src/rnp/rnpcfg.h, src/tests/cli_common.py, src/tests/cli_tests.py, src/tests/rnp.py
This PR adds support for multiple-key encryption via `-r` or `--recipient` CLI parameter, which replaces previously used `--userid`. `--userid` will be used for signer's private key selection.
Also it adds `--passwords` CLI option which allows symmetric encryption to multiple passwords.
I didn't add CLI tests yet since we lack a functionality on keyring manipulation (or do I miss somehow the option to export private key, delete key from keyring, and so on?)
Fixes #236
=> Allow multiple-recipient encryption

src/tests/cipher.c, src/tests/cli_tests.py, src/tests/rnp_tests.c, src/tests/rnp_tests.h
Splits DSA test into 2. One is testing all key sizes required by RFC, the other one does some negative tests for selected key.
This should make dsa roundtrip test a bit less than 2x faster as key generation is done only once
More improvements are possible, but let see first if that's fast enough...
Closes #629
=> Split DSA roundtrip test into 2 cases

ci/install.sh, ci/main.sh
Previously, in some cases we were getting mostly useless stack traces from clang's sanitizers.
Adding fno-omit-frame-pointer for external libs will help ensure we get useful stack traces and adding debug info will get us line numbers.
=> ci: Enable more debug info, improve stack traces.

src/librepgp/stream-parse.c
This is a rare case because we have to pass checks on the algorithm id earlier in the code in order to reach this point.
Nevertheless, this did leak randomly on occasion (less than 2% chance in some of my tests).
=> Fix leak when encrypted_decrypt_cfb_header fails to decrypt.

ci/local.sh, ci/run-local.sh, doc/DEVELOPMENT-GUIDE.md, travis.sh
This just makes it easier to run things locally.
You can now do something like:
```sh
./travis.sh
env GPG_VERSION=beta BUILD_MODE=sanitize-leaks ci/local.sh
```
Other related changes in `travis.sh`:
* Changed to all verbose options, for readability.
* Added the ptrace capability, since it's needed for sanitize-leaks.
* Run as the travis user (uid 2000).
* Switch to working directory `/usr/local/rnp` immediately.
* Default to `bash -l` as the command, but allow others.
There's some duplication here, but we already had that duplication in the docs, so it's not too bad.
Maybe the macOS devs can let me know if any of this actually works for you guys...
=> ci: Make local CI runs simpler.

src/tests/cipher.c
I've seen `test_dsa_roundtrip` still timing out in travis fairly frequently. I tested flushing stdout and that made everything pass without any timeouts, so it seems like a good interim solution that I should have done in #625.
(Could also use `stderr` and rely on lack of buffering, but when I tested it I had better results this way)
=> Flush printf output in test_dsa_roundtrip to prevent CI timeouts.

src/librepgp/stream-write.c, src/rnp/rnp.c, src/rnp/rnpcfg.h, src/tests/cli_tests.py
This PR allows to stack `-u/--user` CLI parameters to sign/clearsign/detached sign file with multiple keys. Includes CLI test case.
Next PR, built on top of this and #619 , will allow encrypt-and-sign.
Fixes #620
=> Multiple-key signing

src/tests/cipher.c, src/tests/cli_tests.py
DSA key generation takes a lot of time and causes CI to break.
From the other hand it's not very important (as DSA is not required
by spec) and we test DSA with other key sizes.
In 'NORMAL' build with stable botan it takes now 22min vs 42min
The longest build (mode="SANITIZE" botan=beta) it takes now 35min vs 44min 
Those test may be added back once DSA keygen perf is improved, but it's good enough for now
=> (dsa) Removes tests for 3072 key

ci/install.sh
This is mostly because I missed disable-qt (Qt4) before, which causes the build to fail in my local tests with the newest pinentry master.
=> ci: Trim the pinentry build down.

src/librepgp/stream-packet.c
It could happen only during quite negative scenario, however still worth fixing.
=> Fix possible memory leak during signature writing

include/rnp/rnp2.h, src/lib/rnp2.c, src/librepgp/stream-common.c, src/tests/ffi.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
This PR just adds memory input/output streams to FFI and extends FFI tests to check those streams during signing/verification.
@dewyatt I changed my rnp_input_from_memory to match your implementation, however it still may have a merge conflict. So if you have branch(es) with only those changes feel free to make a PR and I'll rebase on it, fixing the conflicts.
=> FFI improvements: memory input/output, documentation, tests

include/rnp/rnp2.h, src/lib/rnp2.c, src/tests/ffi.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
* Removed rnp_keyring_t. This was used a lot originally, but it has become less and less useful and was sort of sticking out as an oddity. This is pretty much replaced with `rnp_load_keys`/`rnp_save_keys`.
* Using `rnp_input_t`/`rnp_output_t` for key loading/saving. We kind of cheat for now, but at least the interface is there.
* Renamed `rnp_input_from_file`->`rnp_input_from_path` (same for output), mostly because the argument can now be a directory for G10. It's maybe a little hacky, but I'm not sure there's a better way to do it at the moment.
* Some minor key format conversions should be doable now, though there's no tests for this. You should be able to load a GPG ring and save as KBX, or the reverse, etc. It's something we could already do internally, but I don't think the previous …
=> ffi: Remove/replace rnp_keyring_t.

include/rekey/rnp_key_store.h, src/lib/key-provider.c, src/lib/rnp.c, src/lib/rnp2.c, src/librekey/rnp_key_store.c, src/librepgp/stream-write.c, src/rnp/rnp.c, src/tests/generatekey.c, src/tests/key-add-userid.c, src/tests/key-protect.c, src/tests/key-store-search.c, src/tests/key-unlock.c, src/tests/user-prefs.c
While trying to finish up the ffi key provider stuff this week I ran into an issue, which led me to some limitation that I needed to get rid of, so here's some revisions that I think help:
* Revised `rnp_key_store_get_key_by_name` (and removed a sibling function) to have an interface more aligned with the other search functions. There's probably room for improvement on all of these really.
* Added an actual userid search, separate from the "name" search which is mostly useful for kind of fuzzy CLI searches.
* Switched the `rnp_ctx_t` signers and recipients lists to use key pointers, rather than strings. Previously the streaming framework code would resolve these strings to the appropriate keys during the execution of whatever operation (like …
=> Add userid search and revise signer and recipient lists

src/fuzzing/fuzz_keys.c, src/lib/crypto.c, src/lib/fingerprint.c, src/lib/generate-key.c, src/lib/hash.c, src/lib/packet-create.c, src/lib/pass-provider.c, src/lib/pgp-key.c, src/lib/rnp.c, src/lib/rnp2.c, src/librekey/key_store_g10.c, src/librepgp/packet-print.c, src/librepgp/repgp.c, src/librepgp/stream-common.c, src/librepgp/stream-packet.c, src/librepgp/stream-parse.c, src/librepgp/stream-write.c, src/librepgp/validate.c, src/rnp/rnpcfg.c, src/rnpkeys/rnpkeys.c, src/tests/Makefile.am, src/tests/cipher.c, src/tests/ffi.c, src/tests/generatekey.c, src/tests/load-g10.c, src/tests/rnp_tests.c, src/tests/rnp_tests.h
* Fixed a regression in G10 protected keys.
* (Hopefully) Fixed a bunch of issues reported by Coverity (which is working again).
* Fixed some other issues reported by clang's static analyzer.
* Fixed some issues with `pgp_keyid` and `pgp_fingerprint` (note that these can no longer be treated as if they return bool).
=> Fix G10 protected keys and also fix some static analysis issues

ci/install.sh
We don't really need the full history on any of these. Right now a
cache rebuild for GPG_VERSION=beta will git clone about ~800MiB. This
cuts that in half so it's probably worth doing.
Only thing to be aware of is that --branch will try a remote branch name
first, and a tag second. But I can't see any issue with that for us (and
generally people avoid naming tags and branches identically for reasons
like this).
=> ci: Use shallow clones.

ci/main.sh
Quick fix to prevent a codecov upload during the ruby-rnp test.
=> ci: Ensure ruby-rnp test does not upload to codecov.

doc/RELEASE-WORKFLOW.md
This is a bit light on details in some places, but can be expanded as needed.
I created the `release/v0.x` branch and tagged the 0.9.0 release. I also did some minor supporting commits directly to master.
=> docs: Add release workflow document.

CMakeLists.txt, cmake/version.cmake, src/lib/CMakeLists.txt
Apparently I made some last-minute changes and broke this.
This is broken in our tagged release too :( so currently an RPM of 0.9.0 will have libs like:
```
/usr/lib64/librnp.so
/usr/lib64/librnp.so.
/usr/lib64/librnp.so.0
```
After this change, we are back to normal:
```
/usr/lib64/librnp.so
/usr/lib64/librnp.so.0
/usr/lib64/librnp.so.0.9.0
```
=> CMake: Fix library versioning

CMakeLists.txt, ci/main.sh
This only tests the cmake code paths used in travis, so it's far from foolproof but it's better than nothing.
=> ci: Fail with uninitialized and unused CMake vars.

doc/RELEASE-WORKFLOW.md
This step is important to ensure github/`git archive` tarballs are buildable.
I failed to do this for the initial release so we should discuss how to fix that. My thought is to simply amend the commit and move the tag in the release branch, since it's the release itself that is the problem and the code is not changing (so a version bump would be a bit misleading).
=> docs: Add missing step for release workflow.

src/lib/misc.cpp, src/librekey/rnp_key_store.cpp, src/tests/key-store-search.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
While initially it was a fix for AV in key-by-name search (function str2keyid) I decided to move ahead and refactor it slightly.
Now it will allow search by fingerprint, and allow to use spaces/tabs inside.
=> More flexible key by name search

src/rnp/rnp.cpp, src/rnp/rnpcfg.cpp, src/tests/CMakeLists.txt, src/tests/cli.cpp, src/tests/data/test_cli/hello.txt, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
Recently signing/encryption with not specified signer/recipient was broken so this PR fixes it.
Also, in order to cover updated code, I added cmocka CLI test and some overhead to allow call rnp.cpp:main from the rnp_tests.
It uses define `RNP_TESTS`, which is set in `CMakeLists.txt` for `rnp_tests` target.
@dewyatt , @ronaldtse what do you think about such approach?
It would allow to add more tests later on and improve coverage and static analysis on rnp/rnpkeys
Fixes #682
=> Fix signing/encryption with default key

src/lib/fingerprint.cpp, src/lib/fingerprint.h, src/librepgp/stream-key.cpp, src/tests/generatekey.cpp
This PR adds issuer fingerprint subpacket to certifications and subkey bindings.
Also it extends tests with some more sig subpacket checks.
Fixes #513
=> Add issuer fingerprint to certifications and subkey bindings.

.travis.yml, src/lib/rnp2.cpp
This fixes the issue in https://github.com/riboseinc/enmail/issues/53#issuecomment-403798923 and is basically what I meant in https://github.com/riboseinc/rnp/issues/496.
The reason we never encountered this issue before is because it only affects G10 secrings and we don't have any tests using `rnp_op_add_signature` in that case (I'll work on adding that too, but wanted to get this fix in).
=> Fix rnp_op_add_signature.

src/librekey/key_store_g10.cpp, src/tests/cli.cpp
This is mostly @dewyatt's fixes from https://github.com/riboseinc/rnp/issues/715#issuecomment-405060732 within addition of cli cmocka test for the g10 secret keys usage.
Fixes #715
=> Fix usage of g10 secret keys and corresponding tests.

src/lib/types.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h, src/tests/streams.cpp
This PR adds primary key binding signature for signing subkeys (which marked as MUST in RFC).
Tests already include validation of gpg/rnp key signatures so I didn't add new ones.
Also tests will be updated with upcoming code for validation of the key signatures before allowing usage of that key.
Fixes #373
=> Add primary key binding embedded signature

README.md
After a Google search, it seems that Alistair is the right spelling
(and not Allistair) for NetBSD Foundation president Alistair G. Crooks.
=> Fix typo: Allistair -> Alistair

src/lib/crypto/ecdsa.cpp, src/lib/crypto/ecdsa.h, src/librepgp/stream-sig.cpp, src/tests/cipher.cpp
This causes the matching hash to be used for the deterministic nonce generation. It also checks that the input is of the expected length.
This removes the code to truncate the ECDSA input as since the merge of https://github.com/randombit/botan/pull/1502/ Botan handles it already. This patch was included in Botan 2.5 which is already the minimum required version for rnp.
GH #367
=> ECDSA: pass expected hash length via "Raw(hashname)" param

src/librepgp/stream-armor.cpp
The RFC seems to indicate that PRIVATE is the most correct form, and
that only PGP 2.x used SECRET. RFC 4880 section 6.2 only mentions
PRIVATE.
=> Switch armor to use PRIVATE KEY instead of SECRET KEY.

src/librepgp/stream-key.cpp, src/librepgp/stream-sig.h
Fixes and documents logic of the return codes from key signature validation code.
Fixes #726
=> Correct return codes from validate_pgp_key_signature

README.md
I'm not quite familiar with debian but these instructions at least allows to build on clean debian/stretch Docker container.
Based on #748
=> Update readme with instructions for debian

src/apps/packet-dumper/redumper.cpp, src/lib/rnp.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-dump.h, src/tests/streams.cpp
Just needed this functionality within other task (correcting key grip calculation).
Also now times/s2k iterations are printed as unsigned.
=> Display key id/fingerprint/grip in packet listing

src/lib/crypto.h, src/lib/crypto/bn.cpp, src/lib/crypto/bn.h
Got across of some unused functions/defines. Most of them are from bn.h/bn.c and were used when we internally stored data via bignums. So now they can be safely removed.
=> Remove some unused defines and functions.

src/rnp/rnp.cpp, src/rnp/rnpcfg.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/rnpkeys/tui.cpp, src/tests/generatekey.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
Mostly done in #761, this adds support for setting the hash in `rnpkeys`
Required some changes to rnpcfg as there was no way to distinguish between the user having set the hash to SHA-256 on the command line, vs that just having been the default. Now hash defaults to SHA256 as before, except SM2 which still uses SM3 by default. But in all cases an alternative can be set with `--hash`.
Closes #436
=> Support SM2 with arbitrary hashes

src/lib/defs.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/types.h, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/key_store_pgp.h
This PR was aimed to fix #763.
As the side effect it changed the way keys are copied - now all fields are copied instead of reparsing to/from transferable key.
Fixes #763 
Now travis will fail - need to wait till #770 is merged.
=> Correctly copy all parsed pgp_key_t fields during load

.cirrus.yml
I forgot to limit this to important branches as we do for Travis CI.
Note: Cirrus CI is a little weird because it will still show a build entry that failed with `INVALID_ARGUMENT: No tasks found to start!`.
=> ci: Only run Cirrus CI for certain branches and PRs.

src/lib/pgp-key.cpp, src/tests/CMakeLists.txt, src/tests/key-prefs.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
This PR fixes error in aforementioned function (used to add preferred sym algs/hashes/etc), improves it to not allow duplicates, and adds tests.
=> Fix pgp_user_prefs_add_val function: add items correctly

docs/README.adoc, docs/navigation.adoc
This moves the README under docs/ (where it will still be recognized by GitHub), and converts markup from Markdown to AsciiDoc. This way it’ll integrate well with rnpgp.com (and the latest version of Open Project theme also adds in-page ToC navigation for AsciiDoc-rendered documentation files).
=> docs: Convert README to AsciiDoc, add navigation

src/librepgp/stream-armor.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h, src/tests/streams.cpp
Current master will crash on this test, so this fixes that.
=> Fix double-free with invalid armored headers.

cmake/version.cmake
Our version determining code will currently error out if rnp is used as a submodule because it checks for a directory named `.git`, which is in fact a file when used as a submodule.
=> Fix broken versioning when added as a git submodule.

include/rnp/rnp2.h, src/lib/rnp2.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
We didn't have such function before, and it is useful sometimes (at least need this for CLI to FFI transition).
=> Add rnp_unload_keys function to the FFI.

src/librepgp/stream-armor.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-key.cpp, src/tests/ffi.cpp
This PR fixes #824 :
- it adds check for premature armored stream end;
- also adds check for underlying armored stream error while processing armored key(s).
- updates test to make sure there are no memory leaks/other problems while processing cut out armored input
- raises issue #826
=> Check for premature armored stream end

src/lib/pgp-key.cpp
This PR just fixes the warning which was somehow missed before.
=> Fix signed comparison warning in pgp_user_prefs_add_val().

src/librepgp/stream-write.cpp, src/tests/ffi.cpp
This fixes #811 and update tests to not let this happen in the future.
=> Correctly set armor header for detached signatures.

src/lib/rnp.cpp, src/tests/data/test_ffi_json/generate-pair-dsa-elg.json, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
I realize the JSON key generation code is due for a rewrite (using the non-JSON keygen code) but I still think it may be worth merging.
There is currently a slight backwards-incompatible change here, so that should probably be discussed. Previously, you could pass something like:
```json
{
"primary": {
"length": 1024
}
}
```
And it would default to RSA. With this change, you must specify the type:
```json
{
"primary": {
"type": "RSA",
"length": 1024
}
}
```
I don't think this was documented anywhere.
=> ffi: Expand JSON key generation bit length support.

src/lib/rnp.cpp, src/tests/ffi.cpp
I've been doing some work on ruby-rnp and noticed that the password parameter here ends up being ignored when generating a primary key only. This API didn't make it into a release yet, so not a huge deal.
=> Fix primary key protection in rnp_generate_key_ex.

include/rnp/rnp.h, src/apps/packet-dumper/CMakeLists.txt, src/apps/packet-dumper/redumper.cpp, src/lib/rnp.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-dump.h, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/tests/cli.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h, src/tests/streams.cpp
This PR adds option to output JSON while dumping packets.
Also it adds functions `rnp_key_packets_to_json` and `rnp_dump_packets_to_json` to the FFI.
First one was needed for CLI, second one will be handy as well in some cases (like tests).
Tests are basic for now since most likely there would be suggestions on JSON structure.
Here are output examples:
<details><summary>Key</summary>
```json
[
{
"header":{
"offset":0,
"tag":6,
"tag.str":"Public Key",
"hdr":"99032e",
"length":814,
"partial":false,
"indeterminate":false
},
"version":4,
"creation time":1522761670,
"algorithm":17,
"algorithm.str":"DSA",
"material":{
"p.bits":2048,
"q.bits":256,
"g.bits":2047,
"y.bits":2044
},
"keyid":"c8a10a7d78273e10"
},
{
"header":{
"offset":817,
"tag":13,
"tag.str":"User ID",
"hdr":"b406",
"length":6, …
```
=> JSON output for packet dumper and FFI packet dump

src/lib/rnp.cpp, src/tests/ffi.cpp
This is a minor fix to match up with the docs in the header.
```cpp
* @param keyserver NULL-terminated string with key server's URL, or NULL to delete it from
*                  user preferences.
```
=> ffi: Fix to allow a NULL key server pref in key generation operation.

src/lib/CMakeLists.txt, src/lib/crypto/ecdh.cpp, src/lib/crypto/rsa.cpp, src/lib/crypto/sm2.cpp
There's a handful of functions that were recently deprecated in Botan, which we currently use in rnp.
Some links for more info:
* https://github.com/randombit/botan/commit/d17dbed547765739e1885bde33b0165795bcbd72
* https://github.com/randombit/botan/blob/a82d746a51c786049e855098934349a7821e1a7e/src/lib/ffi/ffi.h#L1112
* https://github.com/randombit/botan/blob/a82d746a51c786049e855098934349a7821e1a7e/src/lib/ffi/ffi.h#L942
Note that I opened https://github.com/riboseinc/rnp/issues/839 since I know this introduces something that can throw (`std::to_string`). `std::to_chars` would be better but it's c++17.
=> Remove the use of deprecated Botan functions.

src/librepgp/stream-dump.cpp
=> Fix GCC warning caused by wrong local variable type.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h, src/tests/streams.cpp, src/tests/support.cpp, src/tests/support.h
Main goal of this PR was to add rnp_output_t creation functions which would allow to control file overwrite/random temporary file creation. 
Probably it should have another name, like rnp_output_to_path_ex() or so on.
However then we'll probably need to control temporary dir creation as well.
=> FFI: add function rnp_output_to_file()

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
This PR adds some basic signature access functions which I needed for CLI.
Also it fixes `rnp_locate_key()` function to set result to NULL if key was not found (basically, it should be in a separate PR, needed this in `rnp_signature_get_signer()`).
=> FFI: add functions to access key/uid signature(s).

src/lib/rnp.cpp
This was generally preventing the use of SHA3 in the FFI.
=> Add SHA3 strings to hash alg map.

include/rnp/rnp_sdk.h
Add missing ifdef for `__cplusplus` in `rnp_sdk.h`.
=> Add check for __cplusplus for closing brace.

include/rekey/rnp_key_store.h, include/rnp/rnp.h, src/lib/json_utils.h, src/lib/misc.cpp, src/lib/rnp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-dump.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
While we have `rnp_load_keys()` this one is different since it works only with OpenPGP transferable keys, and lets caller to know the results of the import (which keys were imported/updated).
Need the last part to use in CLI.
=> FFI: add rnp_import_keys() function.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
Needed it in CLI, so here it comes.
Any comments whether we could need second parameter (sample time) or can always use the default one?
=> FFI: add rnp_calculate_iterations() function.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
Need it for the CLI since we have corresponding command-line parameters.
=> FFI: add rnp_enable_debug() function.

include/rnp/rnp.h, src/lib/misc.cpp, src/lib/rnp.cpp, src/lib/utils.h, src/tests/ffi.cpp
We need this function to not make Travis sad because of too long logs.
Also it may be found useful in other cases.
=> FFI: add rnp_disable_debug() and allocation check to rnp_set_debug().

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
We didn't have a way to find primary key from subkey, so here it is.
=> FFI: add rnp_key_get_primary_grip() function.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
This function is needed in CLI to export multiple keys into the single armored stream. Also may be useful in other places.
This PR should be merged once problems of #865 are resolved.
=> FFI: add rnp_output_to_armor()

src/lib/rnp.cpp, src/tests/ffi.cpp
In previous PRs I missed default key flags setup, so keys/subkeys were by default generated with all available by the algorithm flags.
This PR fixes changes defaults to sign/certify for primary key, and encrypting (or signing for DSA/EdDSA/ECDSA) subkey.
I updated already existing tests instead of writing new one since new test would require to generate new keys, slowing things down.
=> FFI: set default algorithm-dependent key/subkey flags before the generation.

.cirrus.yml, ci/main.sh
It looks like the issue here was pretty much what I suspected, the cache had ruby gems installed for 2.4, but FreeBSD had some updates and a newer ruby was installed, etc.
So the main fix is in 43001e4. I also did some rearranging mostly to improve readability of logs.
=> Fix missing rspec in Cirrus

.cirrus.yml
I accidentally left this duplicate call to before_install in here.
=> ci: Don't call before_install twice in Cirrus.

src/lib/crypto/ecdsa.cpp, src/lib/crypto/eddsa.cpp, src/lib/crypto/elgamal.cpp, src/lib/crypto/rsa.cpp, src/lib/crypto/sm2.cpp, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-key.cpp, src/rnp/rnpcli.cpp
This PR addresses CI timeout issues, discussed in #873.
It disables time-expensive key material tests and disables key material validation right after the load.
Since key material cannot be changed, it is enough to validate it only after generation (to be extra-safe), and after the key import.
=> Validate key material only after generation or key import.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp, src/tests/rnp_tests.h
This PR adds a way to request key encryption password via FFI's password provider and then use it to encrypt generated key.
While it is already possible to encrypt key via rnp_op_generate_set_password(), this method could be handy in some situations (in rnpkeys for instance :)).
I'm not sure about the function name, so if you have better suggestions - you are welcome to share :)
=> FFI: add function rnp_op_generate_set_request_password().

src/lib/librnp.3, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.cpp, src/rnp/rnpcfg.h, src/rnp/rnpcli.cpp, src/rnp/rnpcli.h, src/rnpkeys/CMakeLists.txt, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/rnpkeys/tui.cpp, src/tests/CMakeLists.txt, src/tests/data/test_cli_rnpkeys/getkey_2fcadf05ffa501bb_sec, src/tests/data/test_cli_rnpkeys/keyring_1_list_keys_sec, src/tests/data/test_cli_rnpkeys/keyring_1_list_sigs_sec, src/tests/exportkey.cpp, src/tests/generatekey.cpp, src/tests/load-pgp.cpp, src/tests/support.cpp, src/tests/support.h, src/tests/user-prefs.cpp
This PR makes rnpkeys to use FFI interface.
rnp will be moved later on so we'll finally be able to have single interface to rnp functions.
Also it removes no longer used code, which is replaced with FFI calls.
There are some minor usages of direct interface (see `fficli.h`), which will be adressed during `rnp` transition.
P.S. Unfortunately I don't see the good way to make compilable incremental commits for `rnpkeys` instead of single large one.
=> Use FFI in rnpkeys

include/rnp/rnp.h, src/lib/rnp.cpp, src/librepgp/stream-armor.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
Wrote this for CLI enarmor command for automatic armor header detection but then realized that it is already available in `rnp_dearmor` when passing NULL as armor type.
Anyway, it may be usable in other library usage scenarios.
=> FFI: add function rnp_guess_contents()

src/lib/rnp.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/tests/cli.cpp
Fixes #906 and other possible crashes due to uninitialized rnp_input_t.src field.
=> Fix possible crashes when input directory instead of file is specified.

src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
It appeared that we were not checking for NULL in `rnp_op_set_hash()`, so NULL parameter value was causing AV which is not good.
=> Check for NULL in rnp_op_set_hash()

.travis.yml, ci/before_install.sh, include/rnp/rnp.h, src/lib/crypto/symmetric.h, src/lib/rnp.cpp, src/lib/types.h, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-parse.h, src/tests/ffi.cpp, src/tests/rnp_tests.h, src/tests/streams.cpp, src/tests/support.cpp, src/tests/support.h
This PR adds a single function to FFI which would allow to set AEAD chunk size bits from the CLI.
However, since we didn't have a way to dump AEAD encrypted packet details before, it required a lot of lower layer additions and changes (including some refactoring).
=> FFI: add rnp_op_encrypt_set_aead() function.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
Sometimes (in CLI for example) it is useful to be able to request password(s) for symmetric encryption via the configured pass provider instead of specifying it directly.
=> Allow to use password provider in rnp_op_encrypt_add_password

include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h, src/tests/support.cpp, src/tests/support.h
This PR adds function which dumps signature packet information to JSON.
This would allow to get required info via JSON instead of having FFI function for each possible field.
As a side effect also function `rnp_op_verify_signature_get_handle` was added, allowing to have single interface to signature functions.
P.S. It is draft since it uses cherry-picked commits from yet unmerged PR #924 and is a part of #920.
=> FFI: add function to dump signature packet to JSON

src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
While it's some sort of misuse (trying to verify detached signature via rnp_op_verify_create()), we still should not crash but return an error.
=> Fix possible crash on rnp_op_verify_t misuse.

src/tests/cli_tests.py
Newer version of gpg can have some extraneous output that prevents
matching with the previous regex.
=> tests: Relax cli_tests gpg good signature regex.

include/rekey/rnp_key_store.h, src/librekey/rnp_key_store.cpp, src/tests/key-add-userid.cpp, src/tests/key-protect.cpp, src/tests/key-store-search.cpp, src/tests/key-validate.cpp, src/tests/load-pgp.cpp, src/tests/support.cpp, src/tests/support.h, src/tests/user-prefs.cpp
=> Replaced and removed rnp_key_store_get_key_by_name() in tests.

src/librekey/key_store_kbx.cpp, src/librekey/key_store_kbx.h, src/librekey/rnp_key_store.cpp, src/tests/CMakeLists.txt, src/tests/cli_tests.py, src/tests/kbx-nsigs-test.cpp, src/tests/rnp_tests.h
[NSIGS] "Number of signatures" field should match the total number of signatures in the blob including subkey signatures.
Though, this check was removed on Mar 30, 2017 update of GPG https://dev.gnupg.org/rGa6142dbdbc5783043deb847dc64998c421860941
Closes #405
=> gpg 2.1.15 complains about kbx format

docs/installation.adoc
I have tested these instructions on Ubuntu 18.04.3
Should also work for Ubuntu 18.10
For Ubuntu 19 we can pull botan2 (version 2.9.0) from package.
I used the URL of the latest release of Botan from randombit repository -- 2.12.1
We could also use `git clone` but it would take more time to process.
Fixes #981
=> added instructions for building and installation on Ubuntu 18

include/rnp/rnp.h, src/librepgp/stream-dump.cpp, src/tests/CMakeLists.txt, src/tests/cipher.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h, src/tests/s2k-iterations.cpp, src/tests/support.cpp, src/tests/support.h
- Added tests to ensure that correct iteration count is actually used when user calls rnp_op_encrypt_add_password(). Check is done via packet dumping to JSON and checking of output.
- Added tests for s2k iterations encode/decode functions
- Corrected packet dump output
- Corrected `rnp_op_encrypt_ad_password()` function's documentation.
Closes #982 
Closes #999
=> s2k iterations tests, documentation and packet dump

src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/librekey/key_store_pgp.cpp, src/tests/generatekey.cpp, src/tests/key-add-userid.cpp, src/tests/key-store-search.cpp, src/tests/user-prefs.cpp
This PR refactors pgp_key_t to use struct (and sometimes later on C++ class) instead of raw char* as it was before.
We'll benefit from it via the other PR which corrects key validation (see the issue #1001).
=> Add pgp_userid_t type to store uid information in pgp_key_t

include/rekey/rnp_key_store.h, include/rnp/rnp.h, src/lib/crypto.h, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/rnp/fficli.cpp, src/tests/generatekey.cpp, src/tests/key-grip.cpp, src/tests/key-store-search.cpp, src/tests/key-validate.cpp, src/tests/load-g10.cpp, src/tests/load-pgp.cpp, src/tests/streams.cpp, src/tests/user-prefs.cpp
This PR fixes #1025, and also refactors lower layer to use pgp_key_store_format_t instead of `char *`.
=> Expose RNP_KEYSTORE_* constants via FFI header.

src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h
This should be done in PR #1017 but somehow I missed it.
=> Remove unused pgp_signatures_info_t structure and functions.

include/rnp/rnp.h
=> Fixed incorrect constant names in rnp_unload_keys() description.

src/rnp/fficli.cpp, src/rnp/rnp.cpp, src/rnp/rnpcfg.cpp, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp
Probably later on we should use some function instead of define, but at least now it will be more consistent, and later on easily replaceable.
=> Use single ERR_MSG() call to report errors and warning in CLI.

include/repgp/repgp_def.h, src/lib/crypto.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/types.h, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/key_store_pgp.h, src/librepgp/stream-armor.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-write.cpp, src/tests/ffi.cpp, src/tests/generatekey.cpp, src/tests/key-store-search.cpp, src/tests/load-pgp.cpp, src/tests/partial-length.cpp, src/tests/s2k-iterations.cpp
This PR fixes #785 by renaming ages old pgp_content_enum to more applicable pgp_pkt_type_t.
Also does some refactoring by using pgp_pkt_type_t instead of int.
=> Rename pgp_content_enum to pgp_pkt_type_t

include/repgp/repgp_def.h, include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/librekey/key_store_pgp.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-key.h, src/librepgp/stream-packet.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h, src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_common.py, src/tests/cli_tests.py, src/tests/exportkey.cpp, src/tests/ffi.cpp, src/tests/generatekey.cpp, src/tests/issues/1030.cpp, src/tests/rnp_tests.h, src/tests/streams.cpp
This PR is part of work on key revocation(s) (issue #1005), and fixes #1007 
It implements low-level functionality to generate key revocation certificate, FFI function to export such certificate and rnpkeys CLI command `--export-rev` and options `--rev-type, --rev-reason`  to work with this.
=> Add feature to export key revocation.

src/librekey/rnp_key_store.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
Hit this while was working on subkey revocation: unlocked secret key is locked when some signatures/userids/subkeys are attached to it.
This PR fixes this issue.
=> Fix secret key locking during signature import.

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.cpp, src/rnp/rnpcfg.cpp, src/rnp/rnpcfg.h, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/exportkey.cpp, src/tests/generatekey.cpp, src/tests/issues/1030.cpp, src/tests/key-unlock.cpp, src/tests/load-pgp.cpp, src/tests/streams.cpp, src/tests/support.cpp, src/tests/utils-rnpcfg.cpp
This PR improves usage of rnp_cfg_t for cli_rnp_t structure, which would make implementation of future CLI features easier.
Also fixes #1075
=> Refactor rnp_cfg_t usage within cli_rnp_t

src/tests/key-unlock.cpp
It's quite logical that we should not attempt to modify the signature by writing constant value inside of it - it may match already existing one in 1 in 256 cases.
Fixes #994
=> Fix possible rare failure in test_key_unlock_pgp() test.

include/rnp/rnp.h, src/lib/rnp.cpp, src/rnp/fficli.cpp, src/rnp/fficli.h, src/tests/ffi.cpp, src/tests/rnp_tests.h
This PR implements function `rnp_request_password()` which requests password via configured FFI callback in case user needs it. Fixes #1036.
Also it adds function `rnp_buffer_clear()` to securely clear buffer (instead of pgp_forget() which belongs to lower layer).
Fixes #1035.
=> Add FFI function rnp_request_password().

src/tests/gtest-CMakeLists.txt.in
This should prevent random breakage and can be updated periodically as
needed.
=> tests: Use a specific Google Test commit.

include/rnp/rnp.h, src/examples/dump.c, src/lib/rnp.cpp, src/librepgp/stream-armor.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-write.cpp, src/rnp/fficli.cpp, src/tests/partial-length.cpp, src/tests/streams.cpp, src/tests/support.cpp, src/tests/support.h
This PR removes ssize_t (which is not well available in Windows) from the whole library.
While internal usage was mostly around src_read() function and is pretty safe, it make a breaking change for FFI interface, so ruby-rnp side should be updated.
Fixes #898
=> Remove ssize_t usage.

include/rekey/rnp_key_store.h, include/rnp/rnp.h, src/lib/rnp.cpp, src/librekey/rnp_key_store.cpp, src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/ffi.cpp, src/tests/rnp_tests.h
This PR adds the following functionality:
- rnp_key_revoke() FFI function, which allows to revoke key and subkey and all underlying code
- `rnpkeys --revoke-key` command, which uses this function.
Currently we have feature to export key revocation signature, this PR extends functionality to allow to revoke key and subkey directly (without the signature import).
=> Add FFI function and CLI command to revoke key and subkey.

.cirrus.yml, ci/before_install.sh
Looks like something changed in GHA macos runner, preventing correct installation of json-c. Attempting to fix it.
=> Install automake for macos GHA.

include/repgp/repgp_def.h, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/types.h, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-key.h, src/librepgp/stream-sig.cpp, src/tests/generatekey.cpp
This is a bit wide PR is part of the work on ability to update key expiration (as well as other fields).
Main feature here is moving from old incorrect way of key fields calculation (previously we just set key fields once new signature is added, without checking sigs validity and creation date).
Now it behave correctly by using data only from valid self-signatures, using the latest one as the source of key data (as key expiration, preferred algorithms and so on).
As a side effect of the changes different not so clearly related things were fixed here:
- issue #1092 (expired key)
- issue #1089 (wrong key expiration time)
- incorrect generation of subkey revocation signature
- issue #1020 (wrong subkey flags check)
Normally I would issue separate PRs for all these things, but now I'm a bit …
=> Correct key fields calculation and sigs validation.

src/librepgp/stream-common.cpp
Set the pgp source into error state on src_skip memory allocation failure
Fixes #1091
=> Better handling of error in src_skip

src/lib/rnp.cpp, src/tests/ffi.cpp
Latest MinGW uses json-c 0.14, where TRUE/FALSE constants were removed and replaced with 1/0.
So, changing those to normal true/false (so Windows CI may just hang instead of reporting compilation error).
=> Use true/false instead of TRUE/FALSE for json boolean.

include/rnp/rnp.h
Just removed outdated comments, as noticed in https://github.com/rnpgp/rnp/issues/1119#issuecomment-623437063
=> Remove obsolete todo comments from FFI header.

.github/workflows/centos7.yml, .github/workflows/coverity.yml, .github/workflows/lint.yml, .github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, src/librepgp/stream-armor.cpp
=> Removed the version header from armored messages.

include/rekey/rnp_key_store.h, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/tests/generatekey.cpp, src/tests/key-protect.cpp, src/tests/key-store-search.cpp, src/tests/load-pgp.cpp, src/tests/user-prefs.cpp
This would significantly speed things up for the large keys.
Also move us closer to the C++ approach: pgp_key_t now is treated as C++ object with constructors/destructors instead of direct memory copying/deletion/etc.
Fixes #1101
=> Use std::vector to store signatures/uids/keys etc.

src/lib/misc.cpp, src/tests/CMakeLists.txt, src/tests/utils-hex2bin.cpp
The implementation of hex2bin had some bugs, mostly with handling whitespace.
=> Make hex2bin utilize rnp_hex_decode.

src/lib/misc.cpp, src/lib/utils.h, src/tests/CMakeLists.txt, src/tests/cli_tests.py, src/tests/log-switch.cpp, src/tests/rnp_tests.h
=> A switch to disable logging in optimized builds

src/lib/rnp.cpp, src/lib/utils.h, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp
This PR improves logging, making potential error discovery faster and easier.
Fixes #1162
=> Log errored key ids during import/merge.

src/lib/utils.h, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp
This PR updates #1166. It appears that during troubleshooting it's not easy to locate primary key's id using the GnuPG/other tools.
=> Update errored subkey dumping with primary's keyid.

.github/workflows/centos7.yml
I think I meant to do this also in #1173, it's similar to the pkgconfig test but uses the cmake target instead (for systems w/out pkgconfig, etc).
=> ci: Add test for using cmake target

include/rekey/rnp_key_store.h, include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/tests/CMakeLists.txt, src/tests/ffi.cpp, src/tests/issues/1171.cpp, src/tests/rnp_tests.h
This PR:
- fixes #1171 and adds test for it.
- adds new flag RNP_KEY_REMOVE_SUBKEYS, allowing to remove subkey together with the primary key, making things faster and easier.
- adds test for rnp_key_remove() FFI function
=> FFI: Fix and improve rnp_key_remove().

src/librekey/rnp_key_store.cpp
=> Remove unused regex include from the rnp_key_store.cpp

docs/develop.adoc
Quite plain and simple change. 
And a question:
@ronaldtse @dewyatt : should we update `Reviewers and Responsibility areas` with more uptodate information?
=> Update develop.adoc with better readability/latest RFC4880bis link.

src/lib/rnp.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-parse.h, src/tests/data/test_messages/message.txt.literal, src/tests/ffi.cpp, src/tests/rnp_tests.h
This PR fixes issue #1191, allowing to process messages wrapped just to the literal packet.
Also it adds some more C++ refactoring  to pgp_processing_ctx_t.
=> Allow to process raw literal packets.

include/rnp/rnp.h, src/lib/rnp.cpp, src/librepgp/stream-armor.cpp, src/librepgp/stream-armor.h, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/tests/CMakeLists.txt, src/tests/ffi.cpp, src/tests/pipe.cpp, src/tests/rnp_tests.h
I have added `rnp_pipe` to pipe from input to output, as well as `rnp_output_armor_set_line_length` as siggested,
so it is now possible to do:
```
rnp_output_to_armor(...)
rnp_output_armor_set_line_length(...);
rnp_pipe(...);
```
Fixes #1099
=> Armor line length

CMakeLists.txt
I should have bumped the cmake version requirement in #1182. From [the changelog](https://cmake.org/cmake/help/v3.14/release/3.14.html):
```
Object library linking has been fixed to propagate private link libraries of object libraries to consuming targets.
```
Fixes #1196
=> build: Bump required CMake version.

include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
While this first planned as part of signature stripping work, I decided to do it as separate function due to requirements of autocrypt: be able to export single key with single uid and single subkey (see https://github.com/rnpgp/rnp/issues/1006#issuecomment-647536642).
Part if the issue #1006, and related to still draft PR #1136
=> Add FFI function to export autocrypt-compatible key.

src/lib/rnp.cpp, src/tests/ffi.cpp
This uses function try blocks to prevent C++ exceptions from propagating
across the FFI boundary. Some functions which return direct values
(rather than error codes) and do not throw are left as-is.
For now it just prints directly to `stderr` and uses a format similar to `RNP_LOG`, which I think is a good compromise considering that it should be a very rare occurrence.
Fixes #839
=> Add exception guard to FFI boundary.

src/fuzzing/CMakeLists.txt
This commit will allow us to use the AFL driver on OSS-Fuzz
=> When we're compiling for AFL, use C++'s stdlib because AFL's library uses C++ code

src/librepgp/stream-packet.cpp
```
=================================================================
==1==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 245 byte(s) in 1 object(s) allocated from:
#0 0x51e1bd in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x7fae0309f210 in stream_read_packet_body(pgp_source_t*, pgp_packet_body_t*) /src/rnp/src/librepgp/stream-packet.cpp:681:36
#2 0x7fae030a6434 in stream_parse_pk_sesskey(pgp_source_t*, pgp_pk_sesskey_t*) /src/rnp/src/librepgp/stream-packet.cpp:1115:16
#3 0x7fae03067daa in stream_dump_pk_session_key(rnp_dump_ctx_t*, pgp_source_t*, pgp_dest_t*) /src/rnp/src/librepgp/stream-dump.cpp:918:16
#4 0x7fae03062cf0 in stream_dump_packets_raw(rnp_dump_ctx_t*, pgp_source_t*, pgp_dest_t*) /src/rnp/src/librepgp/stream-dump.cpp:1215:19
#5 …
```
=> Memory leak from unknown pk algo

src/fuzzing/dump.c
While this works, it might be possible to do this better but I'm not sure about how to use `rnp_dump_packets_to_output`.
=> Swallow the dump output to speed up fuzzing.

src/rnp/fficli.cpp, src/tests/cli_tests.py, src/tests/data/test_single_export_subkeys/list_key_export_single.txt
Fixes double export of keys having subkeys.
If the found key has subkeys, they are exported
anyway by rnp_key_export() with RNP_KEY_EXPORT_SUBKEYS flag set.
=> Remove flag CLI_SEARCH_SUBKEYS_AFTER. Fixes #1153

src/lib/crypto/signatures.cpp, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-key.h, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h, src/librepgp/stream-write.cpp, src/tests/ffi.cpp, src/tests/generatekey.cpp, src/tests/key-protect.cpp, src/tests/key-validate.cpp, src/tests/large-mpi.cpp, src/tests/load-pgp.cpp, src/tests/streams.cpp
This PR is aimed to (at least partially) fix issue #1181 
It includes the following changes:
- use pointer to signature instead of static field for embedded signature subpacket (effectively reducing pgp_sig_subpkt_t size).
- parse signature material to corresponding structure only on validation: this would not add much time overhead, but save a bunch of kilobytes for the each signature
- use std::vector instead of list for signatures/signature subpackets, reducing memory allocations and fragmentation
=> Reduce memory usage in library

src/librepgp/stream-key.cpp, src/librepgp/stream-key.h
This is attempt to fix issues #1249 and #1244.
Since it is not reflected in our CI yet, it needs a confirmation.
=> Add missing move constructor for pgp_transferable_userid_t.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.h
This PR adds a bunch of FFI functions, which allows to get information about the key protection (and whether secret key is available at all, like cases where secret key is offloaded or stored on the smartcard).
Related issue #1217
=> Add FFI functions to retrieve secret key protection info.

src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/data/test_cli_rnpkeys/pubring-malf-cert-permissive-import.txt
Adds --permissive option for --import-keys command, which makes rnp_import_keys() to be called with RNP_LOAD_SAVE_PERMISSIVE flag set.
Closes #1160
=> Add --permissive option to rnpkeys.

src/lib/crypto.cpp, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/librekey/key_store_g10.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-key.h, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-write.cpp, src/tests/cipher.cpp, src/tests/generatekey.cpp, src/tests/key-protect.cpp, src/tests/key-store-search.cpp, src/tests/load-pgp.cpp
This PR refactors code to make packet structs more C++ : use constructors/destructors/operators instead of dedicated functions.
Separated from #1207 due to strange compilation problems.
=> Refactor packets to c++

src/librepgp/stream-dump.cpp, src/tests/ffi.cpp
=> Correctly calculate packet nesting level during packet dumping.

include/repgp/repgp_def.h
Since we're using C++11 we can set an explicit type for these enums and that should fix these.
Testing locally with oss-fuzz shows all these to now be fixed.
EDIT: Proper wording since these are actual fixes
=> Fix oss-fuzz invalid-enum-value issues

src/lib/crypto/s2k.cpp
=> Use botan_pwdhash() instead of deprecated botan_pbkdf()

include/repgp/repgp_def.h
=> Fix oss-fuzz issue 25334: invalid enum value for pgp_revocation_type_t

src/librekey/key_store_g10.cpp, src/librekey/key_store_g10.h, src/tests/CMakeLists.txt, src/tests/issues/oss-fuzz-25489.cpp
https://github.com/rnpgp/security-reports/issues/46
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25489
This just adds support for a compile-time constant to limit the recursion when parsing s-expressions.
=> Fix oss-fuzz 25489: rnp:fuzz_keyring_g10: Stack-overflow in parse_sexp

ci/before_install.sh
=> macOS CI: fix homebrew openssl installation failure.

src/librepgp/stream-common.cpp
Looks like Coverity backend doesn't understand if some variable is set inside of `if ()` block, generating a bunch of false positives.
Also this PR fixes some coding style as well.
=> Slightly refactor code to get less false-positives from Coverity.

src/librepgp/stream-parse.cpp
https://github.com/rnpgp/security-reports/issues/17
=> Fix RNP-01-005 WP1: Literal packet parsing allows for Integer underflow (Low).

.github/workflows/macos.yml
Attempt to fix macOS CI timeout issue, and check whether GHA works under the Big Sur.
=> Increase timeout and run GHA on macOS 10.15 and 11.0

src/lib/types.h, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-sig.cpp, src/tests/partial-length.cpp
This PR refactors pgp_packet_body_t and packet parsing/writing to be more C++, having cleaner code and destructor-based memory freeing.
It will be updated with the code borrowed from PR #1349 via new PRs once merged.
=> Refactor pgp_packet_body_t to be more C++.

src/lib/crypto.cpp, src/lib/crypto.h, src/lib/crypto/dsa.cpp, src/lib/crypto/dsa.h, src/lib/generate-key.cpp, src/lib/key-provider.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/lib/utils.h, src/librekey/key_store_g10.cpp, src/librekey/key_store_kbx.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-write.cpp, src/tests/ffi.cpp, src/tests/generatekey.cpp, src/tests/issues/1171.cpp, src/tests/key-add-userid.cpp, src/tests/key-protect.cpp, src/tests/key-store-search.cpp, src/tests/key-unlock.cpp, src/tests/key-validate.cpp, src/tests/load-pgp.cpp, src/tests/streams.cpp, src/tests/support.cpp, src/tests/support.h
This PR refactors getters/setters for cleaner code.
Will be followed with other pgp_key_t functions refactoring, as it is too much changes for a single PR.
=> Refactor pgp_key_t fields access

include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/tests/ffi-key-sig.cpp, src/tests/ffi.cpp, src/tests/generatekey.cpp, src/tests/key-validate.cpp
First function would allow caller to check whether public key is considered to be valid for operations (encryption/verifications).
`rnp_key_valid_till()` would allow to fetch the latest timestamp when key is considered to be valid, so it may be used to validate old signatures.
Fixes #1214 
Should be rebased after #1368 is merged.
=> Add FFI functions rnp_key_is_valid()/rnp_key_valid_till().

ci/test.msvc.sh
This would work as a workaround until issue #1394 is fixed.
=> Run cli_tests under MSVC in a single thread to avoid timeouts.

src/lib/crypto.cpp, src/lib/misc.cpp, src/lib/pgp-key.h, src/lib/utils.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-sig.cpp, src/rnp/fficli.cpp
It fixes the following warnings:
- `warning: implicitly-declared 'pgp_key_t& pgp_key_t::operator=(const pgp_key_t&)' is deprecated [-Wdeprecated-copy]`
- `warning: this statement may fall through [-Wimplicit-fallthrough=]`
- `warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'pgp_transferable_key_t' {aka 'struct pgp_transferable_key_t'} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]`
=> Fix a bunch of GCC warnings.

CMakeSettings.json, docs/installation.adoc
These instructions embrace configuring with `cmake` and building with `MSBuild`, so `make` isn't required here.
Do we need to provide further steps to "deploy" or "install" the exe and dll files?
If so, what are the criteria to consider the rnp "installed" on Windows?
Close #1386
=> Added instructions to build with MSVC

src/tests/cipher.cpp, src/tests/rnp_tests.h
This doesn't necessarily solve the problem of a CPU core being
jittery, but it gives clearer detail if there is a failure.
Closes: #1418
An example failure is now:
```
15: Expected: ((static_cast<double>(iters_100) / iters_10)) > ((6)), actual: 5.93103 vs 6
15: [pgp_s2k_compute_iters() /home/dkg/src/rnp/rnp/src/lib/crypto/s2k.cpp:178] failed to create hash object
15: [  FAILED  ] rnp_tests.s2k_iteration_tuning (528 ms)
15: [----------] 1 test from rnp_tests (528 ms total)
15: 
15: [----------] Global test environment tear-down
15: [==========] 1 test from 1 test suite ran. (528 ms total)
15: [  PASSED  ] 0 tests.
15: [  FAILED  ] 1 test, listed below:
15: [  FAILED  ] rnp_tests.s2k_iteration_tuning
15: 
15:  1 FAILED TEST
````
=> Produce more useful error reports if s2k_iteration_tuning test fails

.cirrus.yml
Fix Cirrus CI failure : ld-elf.so.1: /lib/libthr.so.3: version FBSD_1.6 required by /usr/local/lib/libruby25.so.25 not found
=> Fix Cirrus CI failure : /lib/libthr.so.3: version FBSD_1.6 not found

.github/workflows/ubuntu.yml, CMakeLists.txt, ci/main.sh, src/tests/CMakeLists.txt, src/tests/gtest-CMakeLists.txt.in
This PR adds CMake option DOWNLOAD_GTEST, which is On by default.
Setting it to Off will search for preinstalled Googletest.
Fixes #1410
=> Add CMake option to disable Googletest download.

src/tests/cli_perf.py, src/tests/cli_tests.py
When built in /tmp with a parallel run of the test suite, the same
filename can be clobbered by different tests.
As long as any tests might be run in parallel, we want each test to
have its own workdir.
Closes: #1408
=> tests: Avoid concurrent test failures in /tmp

.github/workflows/ubuntu.yml, CMakeLists.txt, ci/main.sh, src/tests/CMakeLists.txt
=> Add CMake option to disable automatic ruby-rnp installation

include/rnp/rnp.h, src/lib/ffi-priv-types.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h, src/tests/ffi-key-sig.cpp, src/tests/ffi-uid.cpp, src/tests/ffi.cpp, src/tests/issues/1171.cpp, src/tests/rnp_tests.h, src/tests/support.cpp, src/tests/support.h
This PR adds FFI function `rnp_key_remove_signatures()`, which would allow to quickly filter out unneeded signatures on key export or import.
Fixes #1006 
Also it refactors some internal and tests code as a side effect.
=> Add FFI function for batch signature removal.

src/fuzzing/keyring_g10.cpp, src/lib/CMakeLists.txt, src/lib/logging.cpp, src/lib/logging.h, src/lib/misc.cpp, src/lib/utils.h, src/rnp/CMakeLists.txt, src/rnpkeys/CMakeLists.txt
This PR is based on PR #1416 by @dkg and additionally extracts all logging code to the separate code (this would be needed in later PR, which gets rid of lib includes for `rnpcfg.cpp` and `tui.cpp`).
See this comment for more details: https://github.com/rnpgp/rnp/pull/1416#issue-572227080
=> Extract logging code to the separate file/header.

.github/workflows/ubuntu.yml, CMakeLists.txt, cmake/version.cmake
This PR adds back `version.cmake` to the repository, so `rnp` may be built offline.
See issue #1410
=> Keep version.cmake in the repository.

src/lib/misc.cpp, src/rnp/fficli.cpp, src/tests/cli_common.py, src/tests/cli_tests.py
Here are some key generation and encryption tests for weird userids (Issue #1014)
special characters (without \0) generation and encryption
unicode generation and encryption (without icase search)
`-r` (recipient) parameter accepts regex. In order to correctly quote all imaginable characters, I changed mode to `std::regex_constants::ECMAScript`, so that special characters are escaped this way: `-r [\x7D][\x7B][\x5D][\x5B][\x29][\x5E][\x2A][\x2E][\x2B][\x28][\x09][\x0A][\x7C][\x24]@rnp`
allowing begin `^` and end `$` anchors `^[\x7D][\x7B][\x5D][\x5B][\x29][\x5E][\x2A][\x2E][\x2B][\x28][\x09][\x0A][\x7C][\x24]@rnp$`
=> #1014 weird userids

src/lib/CMakeLists.txt, src/lib/crypto/ec.cpp, src/lib/crypto/ecdh.cpp, src/lib/crypto/mem.cpp, src/lib/crypto/mem.h, src/lib/crypto/mpi.cpp, src/lib/ffi-priv-types.h, src/lib/misc.cpp, src/lib/pgp-key.cpp, src/lib/rnp.cpp, src/lib/utils.h, src/librekey/key_store_g10.cpp, src/librepgp/stream-ctx.cpp, src/librepgp/stream-ctx.h, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/tests/CMakeLists.txt
This PR adds secure_array type, which will be automatically cleared in the destructor, and replaces pgp_forget function with secure_clear. Also it moves all these functions to the crypto folder.
=> Move secure memory handling to the crypto folder.

cmake/info.cmake, src/lib/librnp.3.adoc, src/rnp/rnp.1.adoc, src/rnpkeys/rnpkeys.1.adoc
We forgot to update rnp version in man pages, as well as packaging email in v0.15.0 release.
This PR is aimed to fix it (and probably we should then cherry pick it to the release branch/re-push tag?).
=> Update man pages and packaging/bugreport email for the version 15.0

include/repgp/repgp_def.h, src/lib/crypto/hash.cpp, src/lib/crypto/hash.h, src/lib/rnp.cpp, src/librepgp/stream-armor.cpp
As it is used only for armoring/dearmoring.
=> Separate CRC24 from the hashes.

.github/workflows/centos8.yml, ci/lib/install_functions.inc.sh
It seems cmake3 has been renamed to cmake in the dnf repo.
GHA has been failing for CentOS 8 workflows.
See: https://github.com/rnpgp/rnp/runs/2743297015?check_suite_focus=true#step:6:1208
=> Fix installation of cmake for CentOS 8

.github/workflows/windows.yml
Not sure whether this is correct solution, as we leave tests unbuildable on latest msys2/cmake combination without manual googletest sources download. However, this error seems to be on the CMake side and we'll just need to wait till they fix it.
=> Workaround MSYS2 CI issue, failing to checkout googletest via CMake

include/rnp/rnp.h, src/lib/rnp.cpp, src/rnp/fficli.cpp
`rnp_op_encrypt_add_recipient()` did not check return value from `find_suitable_key()` so in some cases NULL pointer could have been added to recipients lists, which caused failures on later stages.
Let's discuss if we need to print rejection reason for each key, primary and subkeys.
=> Fix adding recipients. Fixes #1500.

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi.cpp
Default hash algorithm will be used in this case.
Closes #1530.
=> Allow NULL as a hash argument in rnp_key_add_uid().

.github/workflows/debian9.yml, src/rnp/fficli.cpp, src/rnp/rnpcfg.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli.cpp, src/tests/rnp_tests.h
Closes #1388 
1) `--expiration` flag for `rnpkeys --gen-key` sets expiration for both primary and sub- generated keys.
2) `grabdate()` is fixed and tested with absolute values like '2022-12-31' and relative like '1', '1m', '1y' etc.
3) absolute date in past results in error
=> Added --expiration flag to rnpkeys

src/rnp/rnp.1.adoc, src/rnp/rnpcfg.cpp, src/rnpkeys/rnpkeys.1.adoc, src/tests/cli.cpp, src/tests/utils-rnpcfg.cpp
This PR fixes possible issues with key expiration calculations when timezone is different from UTC (and fixes some incorrect types usage as well).
I got those issues locally, and this was not covered by tests as it looks like all CI runners are in UTC.
Will file a separate issue to run some tests in non-UTC timezone.
P.S. Also it updates man page for rnpkeys, and fixes minor issue in rnp.1.adoc.
=> Respect timezone in key expiration time calculations, used in CLI.

src/rnp/rnp.cpp, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp, src/tests/cli_tests.py
=> CLI: return non-zero exit code on unrecognized command line options.

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.1.adoc, src/rnpkeys/rnpkeys.1.adoc, src/rnpkeys/rnpkeys.cpp, src/tests/cli_tests.py
This PR extends CLI with possibility to read data (key, signature, or any other sort of input) via the path specifiers: `-` for the stdin, `env:VAR_NAME` for env variable.
Fixes #1562 
Fixes #1561
=> Add input specifiers to read data from stdin or env variable.

.github/workflows/centos7.yml, .github/workflows/centos8.yml, .github/workflows/coverity.yml, .github/workflows/debian9.yml, .github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-msvc.yml, .github/workflows/windows.yml, ci/lib/cacheable_install_functions.inc.sh, ci/main.sh
- Removed unnecessary python build for debian:9 job                                       [significant effect for debian9]
- Changed fetch depth from 0 (aka 'all') to 1                                                       [marginal effect for all jobs]
- Removed "debug", "trace", "verbose" for different commands and actions     [noticable effect for all affected jobs]
- Changed custom checkout to actions/checkout@v1 for debian:9 job             [marginal effect for  debian9]
- Added PIC ('position independed code') compilation flag                               
This PR shall bring total CI time down to something in between [1h 5m - 1h 10m]. Under "normal" load, of course.
#1571
=> CI performance improvements

README.adoc, docs/signing-keys.adoc
=> doc: Add link to rnpgp.org for hosted signing key

.cirrus.yml
The doc at https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution
says that it would skip CI if 'skip ci' is on the first line of the
commit message, but this behaviour would not match configs found in
GitHub workflows.  GitHub workflows would skip if 'skip ci' is found in any part of the commit message, not just the first line / last line / whatever.
This commit tries to match their behaviours.
It would also skip Cirrus CI if the only changes are in .github
workflows.
=> ci: Make Cirrus CI skip CI also when 'skip ci' occurs elsewhere in the body of the commit message [skip ci]

src/tests/cli_tests.py
Looks like it was added by mistake to the cli_tests.py
=> Avoid warning 'gpgconf: invalid option "--display-charset"'

src/lib/CMakeLists.txt
Policy CMP0115 is not set: Source file extensions must be explicit.
@ni4 fixes #1550
=> Fix cmake warning with sm2, fixes 7923ede

src/tests/cli_tests.py
Such massive test runs were needed initially to check random failures against GnuPG, now this is overkill.
=> Run less redundant cli_tests

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.cpp, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp, src/tests/cli_tests.py, src/tests/exportkey.cpp, src/tests/generatekey.cpp, src/tests/issues/1030.cpp, src/tests/key-unlock.cpp, src/tests/load-pgp.cpp, src/tests/streams.cpp, src/tests/support.cpp
Previous behaviour was to fail if keyrings are not found or they are empty.
This PR relaxes this approach by allowing absence of keys when ones are not required for the operation (say, symmetric decryption).
Fixes #974
=> Allow empty keyrings for operations which do not require keys.

src/lib/crypto.cpp, src/lib/rnp.cpp, src/librepgp/stream-sig.cpp, src/rnp/rnp.cpp
Fix one implicit fallthrough warning, and consistent attribute. `[[fallthrough]]` is supported in clang, gcc since their C++11
implementations which we require. It is standard since C++17.
Fixes c177ea6c7568d5aa1a191cdee953b40b1d0178e5 from #1393
=> Fix one implicit fallthrough warning, and consistent attribute.

CHANGELOG.md
0.15.1 changelog contained markdown that did not format well in vim
=> Fix Changelog formatting for vim

src/tests/utils-rnpcfg.cpp
Make tests pass after 2024
Tested on i586 and x86_64
Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +15 years, because that is how long I expect some software will be used in some places.
This showed up 1 failing test in our `rnp` package build.
See https://reproducible-builds.org/ for why this matters.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Make tests pass after 2024

ci/env-linux.inc.sh, ci/lib/install_functions.inc.sh
Fixes #1613
Related to #1599 
[See here for test results](https://github.com/ribose-jeffreylau/rnp/runs/3398161264?check_suite_focus=true) (focusing on GnuPG 2.3.1 on CentOS 8) after rebasing on https://github.com/rnpgp/rnp/tree/ni4-1583-tests-support-gnupg-2.3 (https://github.com/rnpgp/rnp/commit/52cbb433e3a62908e627be283020b58694694d05).
=> ci: Fix `is_version_at_least()` to compare patch number

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.1.adoc, src/rnp/rnp.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.1.adoc, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/gnupg.py, src/tests/rnp.py
This PR updates CLI with the following changes:
- allows to use `-` as stdout output marker
- adds `--notty` option to read/write data from stdin/stdout only (useful in batch processing and tests)
- adds option `--overwrite` and changes behaviour of key/revocation export to use it instead of `--force` in case file already exists.
- partially refactors cli_tests to use `self.assertEqual()` and so on.
Fixes #1314
=> CLI: allow to use dash as stdout output specifier

.cirrus.yml
sudo 1.9.8 has an issue, which isn't yet fixed in FreeBSD 12.2 packages collection, so this PR works around by using preinstalled 1.9.3p1.
With 1.9.8 CI gets the following:
```
sudo: (null): option "passprompt_override" does not take a value
sudo: error initializing audit plugin sudoers_audit
```
=> Workaround sudo 1.9.8 issue on Cirrus FreeBSD 12.2 runner.

ci/lib/install_functions.inc.sh
Fixes the following error for macOS runner:
```
==> Upgrading curl
7.79.1 -> 7.79.1_1 
==> Installing dependencies for curl: libnghttp2
==> Installing curl dependency: libnghttp2
==> Pouring libnghttp2--1.45.1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/nghttp2/nghttp2.h
Target /usr/local/include/nghttp2/nghttp2.h
is a symlink belonging to nghttp2. You can unlink it:
brew unlink nghttp2
To force the link and overwrite all conflicting files:
brew link --overwrite libnghttp2
To list all files that would be deleted:
brew link --overwrite --dry-run libnghttp2
```
=> Workaround macOS CI issue related to homebrew and OpenSSL update.

src/tests/cli_tests.py
In draft-ietf-openpgp-crypto-refresh-04, AEAD chunk size is capped at
16.  We don't need to test more than that, and it looks like tests of
chunk size 30 fail on 32-bit platforms like armel and armhf (though
they don't fail on i386 for some reason i don't understand).
Closes: #1664
=> Avoid testing AEAD chunk sizes greater than 16

src/lib/crypto/hash.cpp, src/lib/crypto/hash_common.cpp, src/lib/crypto/hash_ossl.cpp
Reported by Coverity via CID 1465736.
=> Deallocate handle instead of calling Hash::finish() in the destructor.

.github/workflows/centos7.yml, .github/workflows/centos8.yml, .github/workflows/macos.yml, ci/lib/cacheable_install_functions.inc.sh, src/common/str-utils.cpp, src/common/str-utils.h, src/lib/crypto/hash.cpp, src/lib/crypto/hash_common.cpp, src/lib/crypto/hash_ossl.cpp, src/lib/ffi-priv-types.h, src/lib/rnp.cpp, src/lib/utils.h, src/librepgp/stream-common.cpp, src/rnp/fficli.cpp, src/tests/streams.cpp, src/tests/support.cpp
Clang build and test for the following workflows:
- centos7
- centos8-ossl
- centos8
- debian9
- macos
- ubuntu
- windows (msys) 
Fixed:
- Build with clang-cl #1129
- clang/rnp build issue (CentOS 7 workflow) clang/rnp build issue (CentOS 7 workflow) #1670
- clang/GnuPG v2.3.0-beta983 issue (CentOS 8 workflow) clang/GnuPG v2.3.0-beta983 issue (CentOS 8 workflow) #1669
- clang/libgcrypt v1.9.3 issue (CentOS 8 workflow) clang/libgcrypt v1.9.3 issue (CentOS 8 workflow) #1668
Changes previously reviewd but not included in this PR:
- Fix to 'centos8 / pkgconfig-cmake-target' job which was disabled in the upstream version. I have a fix for it, if you need it pls. create separate issue. It may go to another PR if so.
- All convinience changes that helped to run/debug CI scripts outside GHA …
=> Added Clang builds to Ubuntu, CentOS7, CentOS8 (+ ossl), MacOS, Debian9 and Windows-msys2 workflows

.github/workflows/centos8-ossl.yml, src/lib/crypto/backend_version.cpp, src/tests/cli_tests.py
This PR fixes (and slightly refactors) OpenSSL version detection code, which didn't work with dev/beta versions.
Now it should handle all possible cases as from `opensslv.h`.
Also it adds automatic backend detection in `cli_tests.py`.
=> Fix OpenSSL version detection in rnp::backend_version()

src/librepgp/stream-parse.cpp, src/tests/data/test_messages/message.txt.signed-sym-none-z, src/tests/ffi.cpp
While it's a bit awkward to have additional layer of uncompressed compressed stream, this configuration seems to be generated by other implementations.
I believe we had issue for this but cannot find it right now.
=> Support parsing of 'None' algorithm in the compressed packet.

.github/workflows/centos7.yml, .github/workflows/centos8-ossl.yml, .github/workflows/centos8.yml, .github/workflows/coverity.yml
We do not need to download it where we run only rnp_tests/cli_tests.
=> Disable ruby-rnp download where applicable.

cmake/Modules/FindOpenSSLFeatures.cmake, cmake/Modules/findopensslfeatures.c, src/lib/CMakeLists.txt, src/lib/crypto/symmetric_ossl.cpp
This PR adds CMake module which is aimed to check for required OpenSSL features availability.
Currently it doesn't change much, but could be updated later on to be able to enable/disable certain features depending on OpenSSL compile switches.
Fixes #1692
=> Check required OpenSSL features via CMake

.github/workflows/centos7.yml, .github/workflows/centos8.yml, ci/success.sh
As I understand now, codecov uses only latest uploaded report from the PR, i.e. it can go messy for multiple test runs (and different for cli_tests and rnp_tests runs). So this PR changes to run single pass on centos8. Let's see how it goes.
Feel free to correct me if this works in a different way.
=> Upload only single report for all tests to the codecov to avoid mess.

src/lib/pgp-key.cpp, src/tests/ffi.cpp, src/tests/key-validate.cpp
As it can go wrong in cases of dummy secret keys and so on.
This changes behaviour in tests.
Tests cover the case when new certification is generated by secret key which is not marked as valid.
=> Do not prematurely mark secret keys as valid.

src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h
Fixes Coverity issues 1764240 and 1764241.
=> Make pgp_signature_t::keyid() and pgp_signature_t::keyfp() noexcept.

src/tests/CMakeLists.txt, src/tests/rng-randomness.cpp, src/tests/rnp_tests.h
This test recommended by NIST SP 800-90B is intended to detect catastrophic failures of RNG, possibly caused by misconfiguration. It can fail with some low probability on a good random data provided by RNG.
=> Add simple repetition count test for RNG output.

.cirrus.yml, .github/workflows/centos7.yml, .github/workflows/centos8-ossl.yml, .github/workflows/centos8.yml, .github/workflows/debian9.yml, .github/workflows/fuzzing.yml, .github/workflows/lint.yml, .github/workflows/macos.yml, .github/workflows/nix.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-msvc.yml, .github/workflows/windows-msys2.yml, .gitignore, README.adoc, default.nix, docs/installation.adoc, flake.lock, flake.nix
With Nix installed, the following are enabled:
- Build `rnp`:
```console
> nix-build        # if in rnp source dir
> ls result/bin
rnp  rnpkeys
```
You can then directly run the built binaries:
```console
> result/bin/rnp --version
...
> result/bin/rnpkeys --version
...
```
- Install `rnp` imperatively:
```console
> nix-env -i -f .  # if in rnp source dir
```
or
```console
> nix-env -i rnp  # This is actually provided by the rnp Nix files in github:nixos/nixpkgs.
```
- Drop into `rnp` development shell (with all build dependencies installed for you):
```console
> nix-shell       # if in rnp source dir
```
or
```console
> nix-shell '<nixpkgs>' -A rnp   # This is actually provided by the rnp Nix files in github:nixos/nixpkgs.
```
Assuming Nix Flake (https://nixos.wiki/wiki/Flakes) support …
=> nix: Add initial Nix support

.github/workflows/centos8-ossl.yml, src/lib/crypto/elgamal_ossl.cpp, src/lib/crypto/rng_ossl.cpp, src/tests/data/test_cli_rnpkeys/test_stream_key_load_keys_no_bp, src/tests/streams.cpp
OpenSSL crypto backend was accidentally deleted from the workflow, so for a while we didn't actually run OpenSSL tests.
This PR should fix this and accummulated errors, and make workflow file a bit less redundant.
=> Fix broken OpenSSL CI runs and corresponding undetected errors.

src/lib/CMakeLists.txt
=> Force aligned access for sha1cd if it is compiled with sanitizers.

.cirrus.yml, ci/lib/cacheable_install_functions.inc.sh
This PR:
- fixes CI run which was failing due to forced GnuPG gcc requirement. However, since cache key was based only on install.sh and ruby-rnp repository this did not appear for 3 or 4 months.
- updates cache key calculation
- update stable GnuPG and it's component versions to the LTS ones.
=> Fix Cirrus CI run

src/tests/CMakeLists.txt
=> Bump ruby ffi gem version, used by ruby-rnp tests, to 1.15.5

.github/workflows/windows-msvc.yml
Windows-latest now uses Windows 2022 with corresponding Visual Studiom which is not handled well by CI scripts.
=> Use windows-2019 instead of windows-latest for the Github workflows.

include/rnp/rnp.h, src/lib/rnp.cpp, src/rnp/fficli.cpp, src/tests/data/test_cli_rnpkeys/g10_list_keys, src/tests/data/test_cli_rnpkeys/g10_list_keys_no_bp, src/tests/data/test_cli_rnpkeys/g10_list_keys_sec, src/tests/data/test_cli_rnpkeys/g10_list_keys_sec_no_bp, src/tests/data/test_cli_rnpkeys/getkey_2fcadf05ffa501bb_sig, src/tests/data/test_cli_rnpkeys/getkey_2fcadf05ffa501bb_sig_y2k38, src/tests/data/test_cli_rnpkeys/keyring_1_list_sigs, src/tests/data/test_cli_rnpkeys/keyring_1_list_sigs_sec, src/tests/data/test_cli_rnpkeys/keyring_1_list_sigs_sec_y2k38, src/tests/data/test_cli_rnpkeys/keyring_1_list_sigs_y2k38, src/tests/data/test_cli_rnpkeys/keyring_3_list_sigs, src/tests/data/test_cli_rnpkeys/keyring_3_list_sigs_y2k38, src/tests/data/test_cli_rnpkeys/keyring_5_list_sigs, src/tests/data/test_cli_rnpkeys/pubring-malf-cert-permissive-import.txt, src/tests/data/test_cli_rnpkeys/pubring-malf-cert-permissive-import.txt_y2k38, src/tests/data/test_cli_rnpkeys/test_stream_key_load_keys, src/tests/data/test_cli_rnpkeys/test_stream_key_load_keys_no_bp, src/tests/data/test_cli_rnpkeys/test_stream_key_load_sigs, src/tests/data/test_cli_rnpkeys/test_stream_key_load_sigs_no_bp, src/tests/ffi-key-sig.cpp
This PR:
- fixes #1528 by displaying whether uid/key/sig is valid
- prints information about the all signatures (binding, direct-key, etc), not just uid certifications
- adds FFI function `rnp_signature_get_key_fprint()`.
Should be merged only after the #1755
=> Display key/sig validity status in key listing.

.github/workflows/centos7.yml, src/tests/CMakeLists.txt
Fixes #1185 
As there is some issue, most likely with old v7.0.1 CLang compiler/sanitizers, CMake define is disabled for this and older CLang versions. They also do not have "Warning: direct access".
=> Fix Warning: direct access ... to global weak symbol when building rnp_tests.

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.cpp, src/rnpkeys/main.cpp, src/rnpkeys/rnpkeys.cpp, src/tests/cli_common.py, src/tests/cli_tests.py
This PR:
- removes redundant NULL checks for CLI arguments which has `required_argument`.
- refactors duplicate code for settings hash/cipher algorithm.
=> CLI: do not double-check absence of arguments.

src/examples/sign.c
possible alternative "execute sign process was fail"
=> Fix mistype

src/lib/logging.cpp, src/lib/logging.h, src/tests/log-switch.cpp
This PR is a proposed solution for the discussion at https://github.com/rnpgp/rnp/pull/1792#pullrequestreview-933360473 , and allows to temporary disable logging. C++ wrapper should be handy for the cases with mixed C/C++ code.
=> Add functions and C++ wrapper to temporary disable logging in certain cases

include/rnp/rnp.h, src/lib/rnp.cpp, src/librepgp/stream-ctx.h, src/librepgp/stream-write.cpp, src/librepgp/stream-write.h, src/rnp/fficli.cpp, src/rnp/rnp.1.adoc, src/rnp/rnp.cpp, src/rnp/rnpcfg.h, src/tests/cli_tests.py, src/tests/ffi-enc.cpp
This would allow encryption of the already signed message via FFI and CLI.
Fixes #1795
=> Add option to allow raw encryption.

src/librepgp/stream-parse.cpp, src/tests/cli_tests.py
As title says, could confuse users (so did to me once spotted).
=> Fix incorrectly displayed warning message for non-x25519 ECC keys.

src/rnp/fficli.cpp, src/rnp/fficli.h, src/tests/cli_tests.py
addresses p. 1 of #1518 
example output
```
Generating a new key...
Enter password for key 0x2D601CFF57E3C017 to perform the following operation: protect.
Password: 
Repeat password for key 0x2D601CFF57E3C017: 
Enter password for key 0x48A431A8DC901889 to perform the following operation: protect.
Password: 
Repeat password for key 0x48A431A8DC901889: 
sec   2048/RSA (Encrypt or Sign) 2d601cff57e3c017 2021-08-08 [SC]
2b3a807bda7c0ea3ff1d19642d601cff57e3c017
uid           RSA (Encrypt or Sign) 2048-bit key <user@localhost>
ssb   2048/RSA (Encrypt or Sign) 48a431a8dc901889 2021-08-08 [E]
fe11e06b6b55312b154dff9a48a431a8dc901889
```
=> CLI: make password request more verbose.

include/rnp/rnp.h
this is not a substantive change, just a clarification.
=> rnp_key_get_primary_fprint: describe what happens if not a subkey.

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.1.adoc, src/tests/cli.cpp, src/tests/cli_tests.py
While issue #1805 was mostly about the incorrect man page, it ended up in correcting CLI behaviour as it would be more convenient for the user to get `data.txt` from `data.txt.pgp`.
Fixes #1805
=> CLI: strip known extensions from the processed data.

include/rnp/rnp.h
rnp_buffer_free was removed back in f0f338971ee4938dfac4d5a1a3b7794915fa8e7b
=> Replace legacy rnp_buffer_free documentation with rnp_buffer_destroy

.codespellrc, LICENSE-OCB.md, cmake/Modules/FindWindowsSDK.cmake, cmake/Modules/findopensslfeatures.c, src/lib/pgp-key.cpp, src/librekey/key_store_g10.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/tests/CMakeLists.txt, src/tests/cli_tests.py, src/tests/streams.cpp
This also prepare for using codespell to help avoid trivial orthographic issues going forward, with:
```
codespell *
```
=> Trivial spelling cleanup

include/rnp/rnp.h
=> Add missing documentation for the password parameter of the rnp_generate_key_ex.

cmake/librnp.pc.in, src/lib/CMakeLists.txt
Notably, NixOS supplies absolute paths in these.
Bug: https://github.com/rnpgp/rnp/issues/1835
=> Support absolute libdir, includedir in librnp.pc

include/rnp/rnp.h, src/lib/crypto.cpp, src/lib/generate-key.cpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/sec_profile.cpp, src/lib/sec_profile.hpp, src/librekey/g10_sexp.hpp, src/librekey/key_store_g10.cpp, src/librekey/key_store_g10.h, src/librekey/key_store_kbx.cpp, src/librepgp/stream-write.cpp, src/rnp/fficli.cpp, src/rnp/rnp.1.adoc, src/rnp/rnp.cpp, src/rnp/rnpcfg.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.1.adoc, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/key-protect.cpp
This PR changes code to redirect all time request calls into the security context, allowing to override the current time. This would be useful for debugging and for test artifact creation.
=> Add FFI API and CLI options to override current time.

src/common/file-utils.cpp, src/common/file-utils.h, src/lib/rnp.cpp, src/rnp/fficli.cpp, src/rnpkeys/tui.cpp, src/tests/ffi.cpp, src/tests/rnp_tests.cpp
=> Add and use function rnp_fdopen which would not cause AV with wrong fd on Windows.

include/rnp/rnp.h, src/common/file-utils.cpp, src/common/file-utils.h, src/lib/rnp.cpp, src/rnp/fficli.cpp, src/rnpkeys/rnpkeys.1.adoc, src/tests/cli_tests.py
This PR changes CLI behaviour on non-existent keyrings to the following:
- do not display `warning: keyring at path '/Users/user/.rnp/pubring.gpg' doesn't exist.` message on empty homedir
- do not parse GnuPG conf, extracting the default key as it may not exist in RNP's keyring
- if homedir is empty then display message about key generation/import from the GnuPG.
Fixes #1558 
Fixes #1559
=> CLI: do not confuse user with 'no keyring file' messages and default gnupg key.

include/rnp/rnp.h, src/lib/rnp.cpp, src/rnp/fficli.cpp, src/tests/cli_tests.py, src/tests/ffi-key-sig.cpp
This addresses #1612.
No extra tests introduced so far, because this is a low-risk change and there are already existing tests for both
- FFI used to generate non-armored revocation signatures;
- CLI used to generate armored ones.
I guess we could introduce tests which compare the results with reference results, because currently the FFI tests discard the output without any checks due to `rnp_output_to_null()`.
=> [#1612] FFI: add option to export armored revocation

.github/workflows/centos8.yml, ci/main.sh, src/lib/crypto/hash.cpp
This changeset aims to make the codebase conformant to tests' expectations that any SMx operation fails when `ENABLE_SM2=Off`. It also adds CI coverage for this case.
The new CI run fails without the code patches: https://github.com/rnpgp/rnp/runs/6796644858
The new CI run passes with the patches: https://github.com/rnpgp/rnp/runs/6794059647
Bug: https://github.com/rnpgp/rnp/issues/1836
=> [#1836] fail operations on SM{2,3,4} if configured disabled

src/tests/cli_common.py
Before, after a CLI test fails, all you saw was
cli_common.CLIError: <unprintable CLIError object>
It was due to a runtime error during __str__() method execution.
=> Make CLIError printable

src/rnp/rnp.cpp
>  "Sign, verify, encrypt, decrypt, investigate OpenPGP data.\n"
investigate -> inspect
Just feels a more proper choice of a word here.
=> Improve wording in help message

src/tests/CMakeLists.txt
Fixes #1726 
Using latest commit from the master branch is recommended by Google.
=> Use latest commit of GoogleTest.

.github/workflows/fedora35-lean.yml, ci/docker/Makefile, ci/docker/fedora35.Dockerfile, ci/docker/fedora35.test-locally
This changeset introduces the first custom Docker container intended for RNP's CI.
This Fedora 35 CI config intends to replace the existing config fedora35-ossl.yml (which is currently broken due to riboseinc repo signature issue).
There seems to be no way to trigger GHA to run this CI configuration before it is merged to master.
There is also a script ci/docker/fedora35.test-locally which shows how to use this container for local testing.
=> Custom Docker images to speed up CI

include/rnp/rnp.h, src/lib/ffi-priv-types.h, src/lib/rnp.cpp, src/librepgp/stream-ctx.h, src/librepgp/stream-parse.cpp, src/rnp/fficli.cpp, src/tests/ffi.cpp, src/tests/streams.cpp
This PR changes previous a bit inconsistent behaviour of the `rnp_op_verify_execute()`.
Now by default it will succeed if there is at least one valid signature (if data is signed).
However, as CLI is stick to another rules, function `rnp_op_verify_set_flags()` was added to be able to handle following scenarios:
- decrypt data even if there are no valid signatures
- require all signatures to be valid for successfull processing.
=> Require single valid signature for successfull return of  rnp_op_verify_execute() by default.

ci/lib/install_functions.inc.sh
Fixes #1904 
Still leaves behind BOTAN_INSTALL and some other traces which pollute logs.
=> CI: Do not install botan with OpenSSL backend runners.

include/rnp/rnp.h, src/tests/ffi-key.cpp
Fixes #1909, adds "fingerprint" to documentation and tests. 
Also seemingly duplicated code is removed from `test_ffi_key_iter`. Code blocks marked by comments "// test with both rings empty" and "// test empty rings" are bit confusing, the same actions are repeated and nothing is changed in testing state between them.
=> Add missing "fingerprint" identifier

ci/lib/install_functions.inc.sh, src/rnp/fficli.cpp, src/rnp/rnp.1.adoc, src/rnp/rnp.cpp, src/rnp/rnpcfg.h, src/tests/cli_tests.py
- fixes #1843 
- adds `--set-filename` command to override file name in the literal data packet.
=> CLI: add command --set-filename and do not store env/stdin filename in message

.github/workflows/centos7.yml, .github/workflows/centos8-ossl.yml, .github/workflows/centos8.yml, .github/workflows/centos9-ossl.yml, .github/workflows/coverity.yml, .github/workflows/disabled/centos9.yml, .github/workflows/fedora35-lean.yml, .github/workflows/fedora35-ossl.yml, .github/workflows/fedora36-ossl.yml, .github/workflows/fedora36.yml, .github/workflows/lint.yml, .github/workflows/macos.yml, .github/workflows/nix.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-msvc.yml, .github/workflows/windows-msys2.yml
This PR is partial solution to the issue #1923 
However it cannot be fully resolved due to problems of v2-v3 actions running with the non-host architecture (see https://github.com/actions/checkout/issues/334 and https://github.com/actions/runner/issues/1011).
=> CI: Update actions/checkout and actions/cache to v3 where applicable.

ci/env-common.inc.sh, src/tests/cli_tests.py, src/tests/ffi.cpp, src/tests/issues/1030.cpp, src/tests/rnp_tests.cpp, src/tests/support.cpp, src/tests/support.h
A lot of temporary directories are always left around after the tests even when all they all pass. There are a few sources of that, and this patchset addresses them all.
Bug: https://github.com/rnpgp/rnp/issues/1498
=> [#1498] Fix tmpdir cleanup

include/rnp/rnp.h, src/lib/rnp.cpp, src/tests/ffi-key-sig.cpp
This changeset adds an FFI API function to export specifically a signature, in binary or armored form.
=> [#1783] FFI: Add rnp_signature_export()

src/lib/defaults.h, src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.1.adoc, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/rnpkeys/tui.cpp, src/tests/cli_tests.py
Implements new feature in `rnpkeys`, now more subkeys can be generated and added to existing primary keys using `--edit-key` `--add-subkey` options.
=> CLI: support for adding more subkeys. Closes #1784.

.github/workflows/lint.yml, .github/workflows/macos.yml, src/lib/crypto/backend_version.cpp, src/rnp/rnpcfg.cpp
Commit 793e5b38 updates lint.yml for clang-format action, which started to use version 11.1.0 instead 11.0.0 by default, so this PR reverts this back to 11.0.0.
Also it updates macOS version runners.
@maxirmx  Was this done by intension, i.e. are there any benefits of switching to 11.1.0? I'm not against it but just want to get aligned/update work setup.
Fixes #1975 
Fixes #1976
=> Update CI to use clang-format 11.0.0.

src/lib/crypto/symmetric_ossl.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/tests/ffi-enc.cpp
There were two problems:
- AEAD always used the same algorithm for both CEK and KEK (which is not common but still acceptable)
- because of this it was not able to decrypt data in case of different CEK/KEK algorithms
This applies to the symmetric (password-based) encryption only.
Fixes #1939
=> AEAD: fix incorrect behaviour in case of different algos used for CEK/KEK

src/rnp/fficli.cpp, src/rnp/fficli.h, src/rnp/rnp.cpp, src/rnp/rnpcfg.h, src/rnpkeys/rnpkeys.cpp, src/rnpkeys/rnpkeys.h, src/tests/cli_tests.py, src/tests/generatekey.cpp
Introduces new CLI option `--force-weak`. From now, using cryptographically weak hashes for key and data signatures is prohibited unless `--force-weak` is present.
This PR reimplements CLI related part of #1524 using `rnp_get_security_rule()`.
Closes #1524
=> Add CLI option --force-weak for weak hashes.

src/rnp/rnp.cpp, src/rnpkeys/main.cpp, src/tests/cli_tests.py
This PR adds new error message to `rnp` and `rnpkeys` when multiple conflicting commands are passed on a command line.
Closes #1982
=> CLI: check for conflicting commands.

src/common/file-utils.cpp
=> Fix nullptr, which could be passed as non-null parameter of closedir.

src/tests/cli.cpp, src/tests/generatekey.cpp
Addresses #1277 
Fixes two places where `malloc()/calloc()` return values were not checked for NULL.
=> Check return value of malloc/calloc in tests.

cmake/Modules/findopensslfeatures.c, src/lib/crypto/bn.h, src/lib/crypto/dl_ossl.cpp, src/lib/crypto/dsa_ossl.cpp, src/lib/crypto/ec_ossl.cpp, src/lib/crypto/ecdh_ossl.cpp, src/lib/crypto/elgamal_ossl.cpp, src/lib/crypto/rsa_ossl.cpp
And do some refactoring for less gotos.
=> OpenSSL backend: replace functions, deprecated in OpenSSL 3.0

src/lib/crypto/elgamal_ossl.cpp
Noticed via https://github.com/rnpgp/rnp/pull/2087
=> Fix possible memory leak during ElGamal key generation with OpenSSL 3.0 backend.

src/tests/utils-rnpcfg.cpp
=> Fix test_rnpcfg_get_expiration.

README.adoc
README.adoc: note support for openSUSE.
rnp / sexp are now packaged for openSUSE and SLE.
* https://build.opensuse.org/package/show/openSUSE:Factory/rnp 
* https://build.opensuse.org/package/show/security:privacy/rnp
=> Update README.adoc for openSUSE

README.adoc, docs/installation.adoc
Close #1461 
RNP can be installed from an official Gentoo repository now
https://packages.gentoo.org/packages/dev-util/librnp
=> Update Gentoo support status.

.github/workflows/nix.yml
=> Fix macOS nix CI

src/tests/cli_tests.py
Fixes #2100, #2059
Test build: https://build.opensuse.org/package/show/security:privacy/rnp
=> test_set_expire: increase short expiry time from 10s to 60s

.github/workflows/nix.yml, src/lib/crypto/backend_version.cpp
=> RIPEMD160 is now available by default since OpenSSL 3.0.7.

.github/workflows/windows-native.yml, src/tests/cli_common.py
=> Use setuptools instead of distutils for Python > 3.8.

src/lib/crypto/ecdsa.cpp
The botan strings in `ecdsa_padding_str_for()` were wrong for SHA3-256/512 (see https://github.com/randombit/botan/blob/master/src/lib/hash/sha3/sha3.cpp#L118)
Note: In `botan_alg_map` in hash.cpp the strings are correctly written. T `ecdsa_padding_str_for` could also make use of the mapping if it's made non-static.
=> fix ecdsa padding strings for sha3

src/rnp/fficli.cpp, src/rnpkeys/rnpkeys.cpp, src/tests/cli_tests.py
Closes #1606
`rnpkeys --export-key` will export all keys when no filter/search pattern is specified, instead of "No key specified" error message.
=> CLI: export all keys when no filter is specified.

src/lib/crypto/symmetric.cpp
As this may cause issues with the latest botan.
=> Do not double-destroy botan's crypto object.

.github/workflows/centos-and-fedora.yml, ci/lib/cacheable_install_functions.inc.sh
One of gnupg tags used for testing pints to 2.3.0 beta version of 2021. 
I do not think there is any value to test against it -- 2.3 line is at 2.3.8 know.
=> Removed tests against gpg 2.3.0 beta

src/lib/ffi-priv-types.h, src/lib/rnp.cpp
=> Refactor rnp_op_verify_st to use C++ types instead of raw pointers.

include/rnp/rnp.h, src/lib/CMakeLists.txt, src/lib/rnp.cpp, src/librepgp/stream-parse.cpp
Among other minor issues this PR adds RNP_EXPERIMENTAL_* defines to the rnp_export.h header, allowing to cut-off by default yet experimental features. Probably better solution would be to remove those function calls from the header at all, however don't see good solution for that at the moment.
=> FIx some PQC issues.

src/fuzzing/keyring_g10.cpp, src/lib/rnp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-armor.cpp, src/librepgp/stream-armor.h, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-packet.cpp, src/librepgp/stream-packet.h, src/librepgp/stream-parse.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-write.cpp, src/tests/cipher.cpp, src/tests/cli.cpp, src/tests/cli_tests.py, src/tests/data/test_key_validity/case5/generate.cpp, src/tests/data/test_stream_armor/misc_headers.asc, src/tests/ffi-key-sig.cpp, src/tests/ffi.cpp, src/tests/key-add-userid.cpp, src/tests/key-protect.cpp, src/tests/key-validate.cpp, src/tests/large-mpi.cpp, src/tests/load-pgp.cpp, src/tests/partial-length.cpp, src/tests/streams.cpp
This PR fixes incorrect detection of cleartext-signed stream. In addition it refactors pgp_source_t to be more C++ (still a lot of work left).
Fixes #2154
=> Fix armored stream detection and refactor pgp_source_t.

src/common/uniwin.h
=> Use typedef for Windows ssize_t. Fixes #2144.

src/tests/cli_tests.py, src/tests/ffi.cpp, src/tests/key-add-userid.cpp
=> Update tests to match SHA1 cutoff date for key signatures.

include/rnp/rnp.h
=> Minor documentation update.

src/lib/key-provider.h, src/lib/pgp-key.cpp, src/librekey/key_store_g10.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-key.h, src/rnp/fficli.cpp, src/tests/ffi.cpp
...and remove some unused/redundant code.
=> Fix bunch of issues, reported by coverity.

.github/workflows/centos-and-fedora.yml, src/lib/crypto/ecdh.cpp, src/lib/crypto/elgamal.cpp, src/lib/crypto/elgamal_ossl.cpp, src/lib/pgp-key.cpp, src/rnp/fficli.cpp, src/tests/generatekey.cpp, src/tests/streams.cpp
=> Fix a bunch of warnings, issued by GCC.

include/rekey/rnp_key_store.h, include/repgp/repgp_def.h, src/lib/crypto/mem.h, src/lib/crypto/mem_ossl.cpp, src/lib/ffi-priv-types.h, src/lib/key-provider.cpp, src/lib/key-provider.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/lib/types.h, src/librekey/key_store_g10.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-parse.cpp, src/tests/ffi.cpp, src/tests/support.cpp
Another one on the C++-transition way.Thought it would be faster...
=> Refactor pgp_key_search_t

.github/workflows/centos-and-fedora.yml, src/lib/crypto/symmetric.cpp
=> CI: fix accidentally broken centos-fedora workflow

codecov.yml, src/lib/crypto/dl_ossl.cpp, src/lib/crypto/dsa_ossl.cpp, src/lib/crypto/ec_ossl.cpp, src/lib/crypto/ecdh_ossl.cpp, src/lib/crypto/elgamal_ossl.cpp, src/lib/crypto/rsa_ossl.cpp, src/lib/crypto/symmetric_ossl.cpp, src/lib/rnp.cpp, src/librekey/key_store_g10.cpp, src/librekey/key_store_kbx.cpp, src/librekey/key_store_pgp.cpp, src/librekey/rnp_key_store.cpp, src/librepgp/stream-dump.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/tests/ffi-enc.cpp, src/tests/ffi-key-sig.cpp, src/tests/ffi-key.cpp, src/tests/ffi.cpp, src/tests/pipe.cpp
...to make codecov happy. Most of those code lines could never hit (like allocation failure) and are left only to gently handle unexpected conditions.
=> Remove tests, sexpp and certain code lines from the Coverage report.

ci/build_tarball.sh
It could be automated/refactored in some way (like for tag push), however let's have at least manual one for now.
Related to #2227
=> Add CI script to manually build tarballs for the releases.

.github/workflows/macos.yml, src/lib/types.h, src/lib/utils.cpp, src/librekey/key_store_g10.cpp
=> libsexpp updated to 0.8.8

src/librepgp/stream-parse.cpp
...and no extra pgp_fingerprint() call.
=> Refactor encrypted_try_key() for better parameter handling.

.github/workflows/windows-native.yml
Due to update from Botan 3.3.0 to 3.5.0 windows-2019 runner started causing problems (https://github.com/microsoft/vcpkg/issues/40276).
So it's time to update to windows-2022, another point is that windows-2025 would become available soon.
=> Update windows-native runner to windows-2022

src/lib/rnp.cpp
=> Refactor rnp.cpp for less code duplication/reuse of ret_str_value().

include/rnp/rnp.h
=> Improve documentation on a bunch of rnp_op_verify_t calls.

.github/workflows/lint.yml, .github/workflows/windows-native.yml, src/lib/key_material.cpp, src/lib/key_material.hpp, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/tests/issues/1171.cpp, src/tests/key-protect.cpp, src/tests/key-unlock.cpp, src/tests/streams.cpp
...also return key material from pgp_key_t by pointer instead of references.
=> Refactor pgp_key_t methods for noexcept and fix few coverity issues.

src/lib/rnp.cpp, src/tests/ffi-enc.cpp
=> Allow zero-length input in rnp_input_from_memory()

src/lib/CMakeLists.txt, src/lib/crypto/dsa.cpp, src/lib/crypto/dsa_common.cpp, src/lib/crypto/dsa_common.h, src/lib/crypto/dsa_ossl.cpp, src/lib/crypto/ecdsa.cpp, src/lib/crypto/ecdsa_ossl.cpp
=> Remove duplicate implementations of some DSA/ECDSA functions

include/rnp/rnp.h, src/lib/pgp-key.cpp, src/lib/pgp-key.h, src/lib/rnp.cpp, src/librepgp/stream-ctx.h, src/librepgp/stream-packet.cpp, src/tests/cli_tests.py, src/tests/ffi-enc.cpp
Fix for ML-KEM PKESK decryption failure.
Added PQC CLI tests that are executed only for RNP build that supports PQC.
=> Fix for ML-KEM PKESK and adding PQC CLI tests

src/lib/fingerprint.cpp, src/librepgp/stream-sig.cpp, src/librepgp/stream-sig.h
Justus pointed out that the hashing of keys is implemented incorrectly for RNP and some other implementations, see https://mailarchive.ietf.org/arch/msg/openpgp/PyP-XDv0VM5bYPX1Iq41-Oyytds/
This concerns computing v5 and v6 signatures over keys.
This PR fixes that. I separated signature and fingerprint computation logically, but the same code is used in the background. I also added a check that we don't accidently hash too large a key.
=> fix key hashing for v5 / v6 signatures

.github/workflows/windows-msys2.yml, ci/utf8-manifest
Details on why this happened: https://github.com/msys2/MINGW-packages/issues/22462#issuecomment-2465927832
=> CI: Set codepage to utf-8 for msys2 tests run.

src/tests/cipher.cpp
=> Reduce default s2k tuning test ratio to 4.

src/lib/rnp.cpp
=> Fix CID 1565414, 1565415: use std::move() instead of copying.

src/lib/ffi-priv-types.h, src/lib/rnp.cpp
=> Make rnp_signature_handle_st C++ object

include/rnp/rnp.h
See https://github.com/rnpgp/rnp/issues/2262#issuecomment-2525244075
=> Fix wrong function name mentioned in rnp.h

src/common/str-utils.cpp
I need to use std::codecvt_utf8_utf16<wchar_t> instead of std::codecvt_utf8<wchar_t> for the conversion between utf-8 and utf-16 for Windows build.
Is there a flag or switch I need to set to make it work without this change?
I am using MinGW 8.1
gcc (x86_64-posix-seh-rev0, created by the MinGW-W64 project) 8.1.0
=> Fixed conversion between utf-8 and utf-16 for Windows build

CMakeLists.txt, include/rekey/rnp_key_store.h, src/lib/logging.h, src/tests/cli_tests.py
=> Remove path prefix in RNP_LOG

.github/workflows/codeql.yml, .github/workflows/coverity.yml, .github/workflows/ubuntu.yml, src/lib/crypto/mem.h, src/lib/ffi-priv-types.h, src/lib/logging.h, src/lib/rnp.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-ctx.cpp, src/librepgp/stream-ctx.h, src/librepgp/stream-packet.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/librepgp/stream-write.h
- for better code quality
- closer to c++ style
- workaround GnuPG multiple SKESKs handling, causing random CI failures for us.
=> Refactor encrypted_add_password().

.github/workflows/centos-and-fedora.yml, ci/tests/ci-tests.sh, src/lib/crypto/dsa.h, src/lib/crypto/ec.h, src/lib/crypto/elgamal.h, src/lib/crypto/rsa.h, src/lib/rnp.cpp, src/librepgp/stream-ctx.cpp, src/librepgp/stream-parse.cpp, src/librepgp/stream-write.cpp, src/rnp/fficli.cpp, src/rnp/fficli.h
Newly reported and one older one.
=> Fix bunch of coverity issues.

src/lib/CMakeLists.txt
Since 3.7.0 Botan has separate module for each curve, which may be disabled, so we should check for them.
=> Add curve module checks for 3.7.0+ Botan

src/lib/rnp.cpp, src/librekey/key_store_kbx.cpp, src/librepgp/stream-key.cpp, src/librepgp/stream-packet.cpp
Fix build errors on some platforms which need `__STDC_FORMAT_MACROS` before `inttypes` for PRI macros. Also use standard C++ header.
=> Define `__STDC_FORMAT_MACROS` before including inttypes

.github/workflows/macos.yml, cmake/Modules/FindBotan.cmake, src/lib/CMakeLists.txt, src/tests/CMakeLists.txt
It appears we didn't have best support for added via https://github.com/randombit/botan/pull/3722 botan-config.cmake, so this PR fixes that.
Since we still need to support Botan-2 I didn't delete builtin FindBotan.cmake
This should (or could) be a reason for issues @defnax experienced in #2307
Fixes #2121
=> Support use of botan-config.cmake

src/librepgp/stream-armor.cpp, src/tests/cli_tests.py, src/tests/data/test_messages/message.txt.gpg-armored
...and refactor some surrounding dearmoring code.
Fixes #1049
=> Support dearmoring of gpg-armored files

.github/workflows/macos.yml, .github/workflows/ubuntu.yml
A bit weird but seems to work.
The issue is that macOS clang adds /usr/local/include to search path with higher priority then OpenSSL 1.1.1 headers, causing FindOpenSSLFeatures malfunction (compiling with 3.0 headers from /usr/local/include, but attempting to link with 1.1.1. libraries).
=> Fix macOS OpenSSL 1.1.1 tests failure.

src/lib/rnp.cpp, src/librepgp/stream-common.cpp, src/librepgp/stream-common.h, src/librepgp/stream-dump.cpp, src/librepgp/stream-dump.h, src/tests/streams.cpp
=> Refactor stream-dump to C++.

include/rnp/rnp.h, src/common/file-utils.cpp, src/common/file-utils.h, src/lib/CMakeLists.txt, src/lib/config.h.in, src/lib/crypto/mpi.hpp, src/lib/rnp.cpp, src/rnp/rnp.1.adoc, src/tests/cli_tests.py
=> Discourage usage of EAX AEAD mode.
