rnpgp/rnp

include/netpgp.h
src/lib/netpgp.c

Initialise netpgp structure; include missing header

---

src/cmocka/rnp_tests.c

- Updated pass-fd function to use base 10

- Modified hash function length from 2048 to 1024

---

src/lib/rnp.c
src/rnpkeys/rnpkeys.c

Small bugfix for https://github.com/riboseinc/rnp/issues/88

Don't try to execute regex from NULL memory

---

src/cmocka/rnp_tests.c
src/lib/crypto.h
src/lib/rnp.c
src/lib/rsa.c
src/lib/signature.c
src/lib/validate.c
src/rnpv/digest.c
src/rnpv/digest.h
src/rnpv/libverify.c

Completing #50. This probably shouldn't be merged quite yet - it relies on an unmerged Botan PR (https://github.com/randombit/botan/pull/1051), still waiting on CI there, but it should be merged to master today or tomorrow.
But, otherwise ready for review.

Use Botan for PKCS signature formatting

---

include/rnp.h
src/lib/librnp.3
src/lib/rnp.c
src/rnp/rnp.c
src/rnpkeys/rnpkeys.c

Revert "Introduced `rnp_set_keyring_format` to specified a keyring format for #33"

---

src/cmocka/rnp_tests.c
src/lib/crypto.h
src/lib/hash.c
src/lib/misc.c
src/lib/packet-show.c
src/lib/packet.h
src/lib/rsa.c

GH #55. Currently uses a hash id in the private range (105).

Add support for SM3 hash function

---

src/lib/rnp.c

I think this is right, though it's a bit confusing.
rnp_init can now determine the following and act accordingly:
* Core dumps are possibly enabled
* Core dumps are definitely disabled
* Core dumps are possibly enabled because we failed to disable them
* because we were compiled without sys/resource.h
* because calls to setrlimit/getrlimit failed
Previously the error messages "cannot turn off core dumps" and "core dumps enabled" were always printed in tandem.
Now, they are distinct conditions.
Normal case:
```
$ rnpkeys --generate-key
[...] no messages about coredumps
```
Explicitly enabled coredumps:
```
$ rnpkeys --generate-key --coredumps
rnp: warning: core dumps enabled, sensitive data may be leaked to disk
```
Compiled without sys/resource.h, or setrlimit/getrlimit fail:
```
$ …
```

Rework the logic surrounding coredumps a bit.

---

ax_check_botan.m4
configure.ac

Check for required features in Botan library at configure time

---

src/lib/create.c
src/lib/rnp.c

No change in logic, just removal of whitespaces and converts few places from spaces to tabs in order to make merges easier

Removes not needed whitespaces and converts spaces to tabs. No logical change

---

README.md

Adds a list of officially supported platforms to README.
This is for #120.

Add list of officially supported platforms

---

src/lib/misc.c
src/lib/rnpsdk.h

No actual logic change, just dead code removal

remove pgp_asprintf function definition, fixes #126

---

src/lib/key_store.c
src/lib/misc.c
src/lib/packet-key.c
src/lib/packet-key.h
src/lib/reader.c
src/lib/rnp.c
src/lib/rnpdefs.h
src/lib/signature.c
src/rnp/rnp.1

Upstream netpgp changes until 2017/05/26

---

src/lib/create.c
src/lib/create.h

Noticed these will doing the EdDSA work, none of these are used and don't seem worth keeping.

Remove several unused functions

---

src/lib/bn.c
src/lib/bufgap.c
src/lib/create.c
src/lib/crypto.c
src/lib/key_store_ssh.c
src/lib/misc.c
src/lib/packet-print.c
src/lib/reader.c
src/lib/s2k.c

Fixed a lot of coverity resource leaks.

Coverity Fixes 

---

src/lib/bn.c
src/lib/bufgap.c
src/lib/create.c
src/lib/crypto.c
src/lib/key_store_ssh.c
src/lib/misc.c
src/lib/packet-print.c
src/lib/reader.c
src/lib/s2k.c

Revert "Coverity Fixes "

---

src/lib/bn.c
src/lib/bufgap.c
src/lib/create.c
src/lib/crypto.c
src/lib/key_store_ssh.c
src/lib/misc.c
src/lib/packet-print.c
src/lib/reader.c
src/lib/s2k.c

Retrying #199 and reverting #208 . Fixed broken merge in `src/lib/bn.c`.

Retrying #199 Coverity Fixes

---

ci/install.sh
ci/main.sh
packaging/redhat/extra/prepare_build.sh

Use all processor cores when building most things.

---

Developers Guide.md

Update Developers Guide to clarify static variables.

---

src/lib/crypto.c

Basically, just one-line fix. Or in such cases it is safe to commit directly to master?

Randomized iv right after the generation.

---

src/lib/create.c
src/lib/eddsa.c
src/lib/packet-parse.c
src/lib/packet-print.c
src/lib/packet.h
src/lib/rnp.c

Tested interop with gpg 2.1.21

Simplify Ed25519 code by sharing logic with ECDSA

---

.travis.yml
ci/install.sh
ci/main.sh
ci/style-check.sh

ci: Add code style check.

---

src/cmocka/rnp_tests.c
src/cmocka/rnp_tests.h
src/cmocka/rnp_tests_cipher.c
src/lib/ecdsa.c
src/lib/eddsa.c
src/lib/writer.c

I needed to reformat eddsa.c before commiting a fix, so in order to see what was really changed in EdDSA see commit, 9036fb0
#249

Fixes a bug in ECDSA and EDDSA signature verification  

---

src/lib/rnp.c
src/rnpkeys/tui.c

Fixes coverity issues introduced in recent commits
CID 1447250
CID 1447251

CID: 1447250 and CID 1447251

---

src/cmocka/rnp_tests.c
src/cmocka/rnp_tests.h
src/cmocka/rnp_tests_cipher.c
src/cmocka/rnp_tests_exportkey.c
src/cmocka/rnp_tests_generatekey.c
src/cmocka/rnp_tests_support.c
src/cmocka/rnp_tests_support.h
src/lib/bn.c
src/lib/create.c
src/lib/crypto.c
src/lib/ecdsa.c
src/lib/elgamal.c
src/lib/key_store_pgp.c
src/lib/key_store_ssh.c
src/lib/memory.h
src/lib/misc.c
src/lib/packet-key.c
src/lib/packet-parse.c
src/lib/packet-print.c
src/lib/reader.c
src/lib/readerwriter.h
src/lib/rnp.c
src/lib/s2k.c
src/lib/s2k.h
src/lib/signature.c
src/lib/validate.c
src/lib/writer.c

First step to run rnp with retrace's memory fuzzing.

Memory fuzzying

---

Developers Guide.md

Add Responsibility Areas to Dev Guide

---

src/lib/bn.c
src/lib/rnp.c
src/lib/signature.c
src/lib/validate.c

- Fixed some minor resource leak.
- Fixed the initialization of the alloc and free routines.

Code review fixes

---

src/lib/crypto.h
src/lib/misc.c
src/lib/packet-parse.c
src/lib/packet-parse.h
src/lib/packet-show.c
src/lib/reader.c
src/lib/signature.c
src/lib/writer.c
src/lib/writer.h

I found and fix few memory leaks, meanwhile my tests shown that it isn't all :(

Memory leaks

---

src/lib/packet-parse.c

Closes https://github.com/riboseinc/rnp/issues/282

Fix ElGamal seckey leak in pgp_seckey_free

---

.gitignore
build_common.inc.sh
ci/main.sh
configure.ac
m4/ax_check_cmocka.m4
src/cmocka/Makefile.am
src/lib/Makefile.am

Create and use `ax_check_cmocka.m4` #290

---

Developers Guide.md

Low priority update to make source file naming convention clear, since I noticed we now have a mixture, and it would be good to eventually be consistent.

Update Developers Guide.md

---

Developers Guide.md

This PR updates Developers Guide with sample doxygen comment as it was discussed in #192.
All comments, including related to English language usage, are welcome.
@flowher I saw you like lines of stars/dashes in comments, imho they are not visually appealing. However if you insist on them we can run a voting.

Added example for doxygen comment

---

src/lib/packet-create.c
src/lib/pgp-key.c
src/lib/signature.c
src/lib/signature.h

These are just some supporting functions, this PR doesn't add anything that actually uses them.
I have a few thousand lines of code that add subkey loading+generation, better key flag support, and some user preferences support. At this point it's probably easiest to just pick it apart and add the supporting pieces first, since it certainly won't merge.
(And I'm not planning to add any docs at this time, but will when time permits)

Add some supporting signature functions.

---

include/rekey/rnp_key_store.h
src/lib/crypto.h
src/lib/errors.h
src/lib/packet-parse.c
src/lib/packet-parse.h
src/lib/packet.h
src/lib/pgp-key.c
src/librekey/key_store_g10.c
src/librekey/key_store_pgp.c
src/librekey/rnp_key_store.c

This is *mostly* fixes for stuff inherited from netpgp, nothing too controversial.

Misc keyring fixes

---

src/lib/defs.h
src/lib/packet-parse.c
src/lib/packet-print.c
src/lib/packet.h
src/lib/pgp-key.c
src/lib/pgp-key.h
src/lib/signature.c
src/librekey/key_store_pgp.c

These are just some minor fixes and additions I'm cherry-picking from the dewyatt-subkey-generation branch to reduce the size of the coming PR.

Random fixes

---

src/lib/eddsa.c

Fixes #300 
@flowher I think you were looking at this but I ran into it while looking at this other thing, so I just went ahead. Can you double check the logic here? It looks like it's just the same issue as that r/s BN<->array conversion.

Fix EDDSA random failures.

---

src/lib/ecdsa.c

Fixes #364 (see ticket for more details)

ECDSA Reduce message size to base point order before signing

---

src/lib/pgp-key.c
src/lib/signature.c

This should fail in CI as it depends on https://github.com/riboseinc/rnp/issues/364 being fixed first.

Check return value of pgp_sig_write.

---

src/lib/pgp-key.c
src/lib/rnp.c

350 pgp decrypt seckey bugs

---

.gitignore
ci/install.sh

`ci` scripts now run on macOS.

Make ci/{install,main}.sh run on macOS

---

include/rnp/rnp.h
src/lib/compress.c
src/lib/compress.h
src/lib/packet-parse.h
src/lib/rnp.c
src/lib/writer.c
src/tests/pgp-parse.c
src/tests/rnp_tests.c
src/tests/rnp_tests.h

* Adds header file for compress.h
* Cleans up compress.c to remove memory leaks
* Adds test which checks received packets after decompression

Removes memory leaks from compress.c

---

include/rnp/rnp_sdk.h
src/lib/crypto.c
src/lib/misc.c
src/lib/packet.h
src/lib/pgp-key.c
src/lib/pgp-key.h
src/lib/validate.c
src/lib/validate.h
src/librekey/key_store_g10.c
src/librekey/key_store_pgp.c
src/librekey/rnp_key_store.c

Hey,
Here I finish implementing decoding and encoding protected private key with default settings of GnuPG.
In TODO list:
- "openpgp-native".

Third step of librekey with G10

---

src/librekey/key_store_pgp.c
src/tests/load-pgp.c
src/tests/rnp_tests.c
src/tests/rnp_tests.h

Fix secret subkey loading and add a simple test.

---

include/repgp/repgp_def.h
src/lib/crypto.c
src/lib/crypto/ec.c
src/lib/generate-key.c
src/lib/packet-create.c
src/lib/pgp-key.c
src/librekey/rnp_key_store.c
src/librepgp/packet-parse.c
src/librepgp/packet-print.c
src/librepgp/packet-show.c
src/rnpkeys/tui.c
src/tests/cipher.c

Use a single ID for SM2 encryption+signatures

---

src/librekey/key_store_kbx.c

I missed this in https://github.com/riboseinc/rnp/pull/354.
Also fixes the keyid offset in KBX, which was off by a bit.
I did notice that we don't really support V3 keys in KBX right now. They require a bit of extra work (see [here](https://github.com/gpg/gnupg/blob/5c8fe5480964c282540c051b538e812851988422/kbx/keybox-blob.c#L598)). We should probably reject them somewhere in the save functions for kbx.

Fix up KBX keystore format for subkeys.

---

src/librekey/key_store_pgp.c

(Pulling some things out of another branch here to minimize PR sizes)
This is just a tiny improvement that takes care of the TODO I added here previously.

Make pgp keyring packet loading more efficient.

---

src/lib/misc.c
src/lib/packet-create.c
src/lib/packet-create.h
src/librepgp/reader.c
src/librepgp/reader.h

This is just some slight improvements from void returns to bool, so at least there's some indication something went wrong.

Misc return value adjustments

---

src/librepgp/packet-print.c

Noticed this wasn't supported, so just a quick little update here.

Add secret subkey printing to list-packets.

---

src/lib/Makefile.am
src/lib/key-provider.c
src/lib/key-provider.h

While moving PK encryption to the streamed approach I got to the point where I need the key provider, similar to the password provider. So decided to add it in separate PR for easier discussion and updates.
Please review it and tell if you have any suggestions regarding the interface. Implementation is just basic and probably will be updated later on.

Key provider interface

---

src/tests/rnp_tests.c
src/tests/support.c
src/tests/support.h

I needed this for some tests I was writing.
Closes https://github.com/riboseinc/rnp/issues/338 but leaves room for improvement as noted here and there.

tests: Copy test data to each individual test home.

---

src/librepgp/stream-armor.c

Found small bug during work on moving CRC24 to botan.

(core) Fix CRC24: Was finlizing wrong CRC state

---

src/librepgp/stream-armor.c
src/librepgp/stream-common.c
src/rnp/rnp.c

Fixes some uninitalized variables and memory leaks.

Fixes for coverity-detected issues

---

Developers Guide.md

docs: Update dev guide with info on commits.

---

src/lib/utils.h

I know macros are pretty much the devil's work, but I'm currently using this in 10 places in some code I have locally, so I figure it's worth consideration at least.

Add ARRAY_LOOKUP_BY_STRCASE macro util.

---

src/librepgp/stream-armor.c
src/librepgp/stream-common.c
src/librepgp/stream-common.h
src/librepgp/stream-write.c

Because of the needs of signing stream I divided functionality of dst_close() to two methods:
- `dst_finish()`, which should be called when all data is written, and process this case, writing mdc, signatures, armor trailer, whatever else
- `dst_close()`, which will just close stream itself. It may also call dst_finish() if it wasn't called before.

Add dst_finish() and corresponding functionality

---

src/lib/crypto.c
src/lib/crypto/bn.c
src/lib/crypto/bn.h
src/lib/crypto/ec.c
src/lib/crypto/ecdsa.c
src/lib/crypto/eddsa.c
src/lib/crypto/sm2.c
src/lib/fingerprint.c
src/lib/hash.c
src/lib/hash.h
src/lib/packet-create.c
src/lib/rnp.c
src/lib/signature.c
src/lib/types.h
src/lib/writer.c
src/librekey/key_store_g10.c
src/librekey/rnp_key_store.c
src/librepgp/packet-print.c
src/librepgp/stream-write.c
src/tests/cipher.c

* Changes interface of BN_num_bytes and BN_num_bits: function now returns ``bool`` and number of bits/bytes as an argument
* Some cleanup in bn.c
* Introduces ``BN_hash`` for hashing bingums and moves already existing implementation
Closes #544

Better checks for results from BN_num_bits/bytes

---

src/lib/crypto/bn.c
src/lib/crypto/bn.h
src/lib/crypto/dsa.c
src/lib/crypto/dsa.h

Apparently a lot of BN functions are not needed anymore.

#543 step1: Removes dead code from bn.c

---

include/rekey/rnp_key_store.h
include/rnp/rnp.h
src/lib/generate-key.c
src/lib/key-provider.c
src/lib/list.c
src/lib/list.h
src/lib/rnp.c
src/lib/rnp2.c
src/librekey/key_store_kbx.c
src/librekey/key_store_pgp.c
src/librekey/key_store_ssh.c
src/librekey/rnp_key_store.c
src/librepgp/packet-print.c
src/librepgp/repgp.c
src/librepgp/validate.c
src/rnp/rnp.c
src/tests/Makefile.am
src/tests/key-store-search.c
src/tests/load-pgp.c
src/tests/rnp_tests.c
src/tests/rnp_tests.h
src/tests/utils-list.c

This is to resolve a number of issues with passing around pointers into dynarrays (see #358, but I would say this doesn't close it).
There's a few approaches we could take here but I think the list seems to work well (it makes the search interfaces a bit easier too).
I also removed an unused function and added some tests.

Convert key store keys from dynarray to list

---

ci/install.sh
ci/main.sh
src/tests/cli_tests.py

*    (tests) Clear keyrings only when finishing tests suite
*    (tests) Use gpgconf instead of kill -9
*    (tests) Update GPG to 2.2.4

CI stabilization

---

src/lib/rnp2.c

This is pretty minor, mostly addressing some TODOs I left here.

Allow NULL results for rnp_generate_key_json and improve error handling.

---

src/lib/rnp.c
src/librepgp/stream-write.c
src/librepgp/stream-write.h
src/rnp/rnp.c
src/rnp/rnpcfg.h
src/tests/cli_tests.py

This PR adds encrypt-and-sign support to CLI and streams.
Also it adds some improvements/refactoring to CLI tests and encrypt-and-sign test as well.
Fixes #582

Encrypt-and-sign support

---

src/lib/symmetric.c
src/lib/symmetric.h
src/librepgp/stream-parse.c
src/librepgp/stream-write.c
src/tests/cli_tests.py

This PR fixes found corner cases in rnp which didn't work properly.
Now it is finally 100% compatible with latest GnuPG master.
Enables AEAD CLI tests as well.

Fix AEAD corner cases

---

ci/install.sh

Right now they're all the same as before, but we have the option of picking known-good commits in case we need to in the future.
This is just something minor I did earlier, ref: https://github.com/riboseinc/rnp/pull/652#issuecomment-372684295

ci: Allow setting specific commits for GPG beta and deps.

---

include/rnp/rnp2.h
include/rnp/rnp_types.h
src/lib/rnp2.c
src/librepgp/stream-write.c
src/tests/ffi.c
src/tests/rnp_tests.c
src/tests/rnp_tests.h

This PR adds encrypt-and-sign functionality to FFI.
Also it reorganizes some internal functions for better code reuse.

FFI: encrypt and sign

---

src/lib/key-provider.c
src/lib/key-provider.h
src/lib/pgp-key.c
src/lib/rnp2.c
src/librepgp/stream-parse.c
src/librepgp/stream-write.c

Nothing ground breaking here, but it should make some other work I'm doing a bit easier. I'll likely have another PR in the next 3 days or so, and then I'm planning to switch to the ruby side (already have some local work there).

Split out key search criteria, reduce some duplication

---

include/rnp/rnp2.h
src/lib/pgp-key.c
src/lib/pgp-key.h
src/lib/rnp.c
src/lib/rnp2.c
src/librepgp/stream-common.c
src/librepgp/stream-common.h
src/librepgp/stream-parse.c
src/librepgp/stream-write.c
src/tests/ffi.c
src/tests/key-protect.c

This is a bit of a mixture of changes I've made while working on ruby-rnp. I can split things out into multiple PRs if desired, was just trying to get things done quickly here.

Various tweaks and fixes

---

include/repgp/repgp_def.h
include/rnp/rnp2.h
include/rnp/rnp_types.h
src/lib/defaults.h
src/lib/pgp-key.c
src/lib/rnp2.c
src/librekey/key_store_pgp.c
src/librepgp/stream-parse.c
src/tests/ffi.c

Here's a few more tweaks and fixes I've made while working on the Ruby side.
Not all of these are in the FFI.

Misc ffi fixes

---

include/rnp/rnp2.h
src/lib/rnp2.c

Minor thing here but I think this might be clearer.

Change take_ownership parameter name to "do_copy".

---

cmake/Modules/Findcmocka.cmake
src/tests/CMakeLists.txt

Minor little thing but it isolates things a little better.

Add a cmocka cmake find wrapper.

---

include/rnp/rnp_sdk.h
src/lib/misc.cpp
src/lib/rnp2.cpp
src/librekey/key_store_pgp.cpp
src/rnp/rnpcfg.cpp

Remove rnp_strdup and replace it with strdup.

---

include/rnp/rnp_sdk.h
src/lib/misc.cpp
src/lib/rnp2.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h

Fixes #710 
Also added a test.

Fix ffi key search by fpr

---

.gitignore
include/rnp/rnp2.h
src/lib/CMakeLists.txt
src/lib/rnp2.cpp
src/lib/version.h.in
src/tests/ffi.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h
src/tests/support.cpp
src/tests/support.h

We probably should have added this from the start, but better late than never.

ffi: Add library version retrieval.

---

include/rnp/rnp2.h
src/lib/packet-create.cpp
src/lib/packet-create.h
src/lib/pgp-key.cpp
src/lib/rnp2.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h

I dropped the old partial export function and created a new one using the input/output concepts and such.

ffi: Add rnp_key_export.

---

include/rekey/rnp_key_store.h
include/rnp/rnp.h
src/lib/generate-key.cpp
src/lib/packet-create.cpp
src/lib/packet-create.h
src/lib/pgp-key.cpp
src/lib/pgp-key.h
src/lib/rnp.cpp
src/lib/rnp2.cpp
src/librekey/key_store_kbx.cpp
src/librekey/key_store_pgp.cpp
src/librekey/rnp_key_store.cpp
src/librepgp/repgp.cpp
src/librepgp/stream-write.cpp
src/rnpkeys/rnpkeys.cpp
src/tests/exportkey.cpp
src/tests/generatekey.cpp
src/tests/key-validate.cpp
src/tests/load-pgp.cpp
src/tests/streams.cpp

This PR includes commits from closed #775, which generally improves some functions interface/usage.
Also it fixes #628

Some code refactoring and improvements

---

ci/install.sh

Local CI was failing (and Travis would have too, if cache were cleared). I think it may be best to pin all these commits and occasionally update them.

ci: Update GnuPG stable and pin HEAD commits.

---

ci/before_install.sh
ci/env-freebsd.sh
ci/install.sh
ci/main.sh

* Add some missing pkg installs
* Set `GPG_VERSION`. This is set to `stable` because `beta` failed to build, which IIRC means some AEAD tests will not be run. Maybe someone else can look into that issue.
* Fix some shebang lines to play nice.
* Install bundler as root. There are other ways to solve this, but this is quick and easy.

ci: Fix FreeBSD build.

---

.travis.yml
Brewfile
ci/before_install.sh
ci/install.sh
ci/utils.inc.sh

I ran into a few issues but in the end I've reduced it down to this.
I ran into some linker errors w/botan master, so I set it to use 2.9.0, which seems reasonable to me.

ci: Add MacOS

---

src/apps/packet-dumper/redumper.cpp
src/tests/cli.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h

This PR fixes #813 and adds corresponding test.

Fix redumper crash

---

include/rnp/rnp.h
src/lib/rnp.cpp
src/tests/ffi.cpp

FFI: add functions rnp_key_get_creation and rnp_key_get_expiration

---

include/repgp/repgp_def.h
src/lib/crypto/ec.cpp
src/lib/rnp.cpp

This PR just refactors some code, mostly for less duplication and later reusage.

Minor refactorings

---

include/rnp/rnp.h
src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h

This functionality I also needed for CLI - to check whether we support certain algorithms (mostly by name), curves, whatever else.

FFI: add rnp_supports_feature()/rnp_supported_features()

---

src/lib/rnp.cpp

This way it should be correct.

FFI: fix error message.

---

.travis.yml
Brewfile
ci/install.sh
ci/main.sh

I encountered a few different issues when looking into the CI failures in https://github.com/riboseinc/rnp/pull/865.
I can't say that these changes will fix that particular issue but I think they are a step in the right direction.
If/when these are merged we can restart that build and go from there.

ci: Various fixes.

---

src/librepgp/stream-dump.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.cpp
src/tests/rnp_tests.h

Some minor dumping fixes and test for them.

Fix RSA algorithm name and dump fingerprint for v3 keys.

---

src/tests/ffi.cpp
src/tests/streams.cpp

This PR just fixes some warnings which I missed in previous commits.

Fix some warnings in tests.

---

src/lib/crypto/elgamal.cpp

This PR fixes issue #881 by retrying key generation if resulting public key has too few bits.
Also it slightly refactors ElGamal key generation code with less FFI calls and local variables.
Unfortunately it is impossible to create test case specific for this situation - due to randomness of the generated key reproducing of this case may take up to 30-40 minutes.

Retry ElGamal key generation if resulting key has less bits than expected.

---

src/lib/misc.cpp
src/lib/pass-provider.cpp
src/lib/rnp.cpp
src/lib/utils.h
src/librekey/rnp_key_store.cpp
src/librepgp/stream-parse.cpp
src/librepgp/stream-write.cpp
src/rnp/fficli.cpp
src/rnp/fficli.h
src/rnp/rnp.cpp
src/rnp/rnpcfg.cpp
src/rnp/rnpcli.cpp
src/rnpkeys/main.cpp
src/rnpkeys/rnpkeys.cpp
src/rnpkeys/rnpkeys.h
src/tests/rnp_tests.cpp

Replacement pull request for https://github.com/riboseinc/rnp/pull/883

Allow cross-compiling for Windows with MinGW

---

src/rnp/fficli.cpp

Just minor refactoring for less duplicate code.

Remove duplicate stdout_writer() code.

---

src/lib/rnp.cpp
src/librepgp/stream-ctx.h
src/rnp/fficli.cpp
src/rnp/fficli.h
src/rnp/rnp.cpp
src/rnp/rnpcli.cpp
src/rnp/rnpcli.h
src/tests/cli_tests.py

This PR continues transition to FFI-only library usage.
Also within it I started to write new code in C++ where applicable instead of C.

Use FFI for rnp --enarmor/--dearmor commands.

---

src/rnp/rnp.cpp
src/rnp/rnpcli.cpp
src/rnp/rnpcli.h

Remove --show-keys command from rnp.

---

src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h

These were not implemented for a while so time has come.

FFI: implement rnp_op_set_file_name/rnp_op_set_file_mtime functions.

---

src/rnp/rnpcfg.cpp
src/rnp/rnpcfg.h
src/tests/utils-rnpcfg.cpp

This PR moves a bit forward to C++ code, and code will be used in CLI to FFI transition PR #920

Update rnpcfg with some std::string based functions.

---

src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h

FFI: check for NULL in rnp_op_set_compression()

---

src/examples/CMakeLists.txt
src/lib/crypto/hash.cpp

Converted pgp_hash_t to use Botan's C++ interface

Hash uses Botan's C++ interface

---

include/rnp/rnp.h
include/rnp/rnp_err.h
src/lib/CMakeLists.txt

Added an installed header containing RNP_SUCCESS

---

src/lib/CMakeLists.txt
src/lib/config.h.in
src/librepgp/stream-common.cpp
src/rnp/rnp.cpp
src/tests/cli.cpp
src/tests/cli_common.py
src/tests/cli_tests.py
src/tests/data/cli_EncryptSign/regenerate_keys
src/tests/data/test_list_packets/list_all.txt
src/tests/data/test_list_packets/list_grips.txt
src/tests/data/test_list_packets/list_mpi.txt
src/tests/data/test_list_packets/list_raw.txt
src/tests/data/test_list_packets/list_standard.txt
src/tests/ffi.cpp
src/tests/generatekey.cpp
src/tests/gnupg.py
src/tests/load-pgp.cpp
src/tests/rnp.py
src/tests/rnp_tests.cpp
src/tests/streams.cpp
src/tests/support.cpp
src/tests/support.h

This is a draft PR at the moment and created to make sure nothing is broken/be able later on to configure GHA for Windows.

Fix windows compatibility issues for tests.

---

.github/workflows/centos7.yml
.github/workflows/macos.yml
README.adoc

And add badges for them in README.

Split GitHub Actions into different platforms

---

src/lib/generate-key.cpp
src/lib/utils.h
src/tests/cli.cpp
src/tests/exportkey.cpp
src/tests/generatekey.cpp

If $LOGNAME is unavailable then $USER is used instead

---

src/rnp/fficli.cpp
src/rnp/rnpcfg.cpp
src/rnp/rnpcfg.h
src/rnpkeys/rnpkeys.cpp
src/tests/generatekey.cpp
src/tests/rnp_tests.h

Generating keys with multiple userids is unsupported.

---

src/lib/crypto/symmetric.cpp
src/lib/crypto/symmetric.h

Found this out during review of PR #973, and it was faster to create PR then file an issue :)

Remove unused code from symmetric.h/symmetric.cpp

---

src/librepgp/stream-parse.cpp

Fix incorrect format modifier warning introduced in be6b88c3

---

src/rnp/rnp.cpp

Add missing -c, --symmetric command to rnp help message.

---

include/rnp/rnp.h
src/examples/encrypt.c
src/examples/sign.c
src/lib/defaults.h
src/lib/rnp.cpp
src/rnp/fficli.h
src/rnpkeys/tui.cpp
src/tests/ffi.cpp
src/tests/generatekey.cpp
src/tests/rnp_tests.h

Defines unified names of algorithms

---

src/examples/dump.c
src/lib/crypto/ec.cpp
src/lib/crypto/symmetric.cpp
src/librekey/rnp_key_store.cpp
src/librepgp/stream-armor.cpp
src/librepgp/stream-ctx.cpp
src/librepgp/stream-dump.cpp
src/librepgp/stream-packet.cpp
src/rnp/fficli.cpp
src/tests/support.cpp

Fixes GCC compile warnings.

---

docs/develop.adoc
git-hooks/pre-commit.sh

Update development documentation to use clang-format version 9.0

---

src/tests/ffi.cpp
src/tests/rnp_tests.h

Add test for checking key pkt length while importing

---

src/rnp/fficli.cpp
src/tests/CMakeLists.txt
src/tests/cli_tests.py
src/tests/issues/1030.cpp

@ni4 Can you take a look and also add some `cli_tests`?

Fix rnpkeys secret key protection

---

src/lib/crypto/hash.cpp
src/lib/crypto/symmetric.cpp
src/lib/pgp-key.cpp
src/lib/rnp.cpp
src/librekey/rnp_key_store.cpp
src/librepgp/stream-armor.cpp
src/librepgp/stream-parse.cpp
src/rnpkeys/rnpkeys.cpp

I didn't fix all of the currently reported issues, but at least most of them.
Other looks like false positives.

Fix issues, reported by coverity.

---

.github/workflows/centos7.yml
.github/workflows/lint.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

ci: Support [skip ci] for github workflows.

---

.github/workflows/coverity.yml
.github/workflows/windows.yml
ci/env-common.inc.sh
ci/gha/setup-env.inc.sh
ci/install.sh
ci/main.sh

@ronaldtse Can you add the `COVERITY_SCAN_TOKEN` secret from [here](https://scan.coverity.com/projects/riboseinc-rnp?tab=project_settings)?

ci: Add scheduled coverity scans

---

src/rnp/fficli.cpp
src/rnp/fficli.h

Keeps user inputs/outputs tied up with terminal.

---

src/rnp/rnp.cpp
src/tests/cli_tests.py

Cancel implicit loading of pubring.

---

include/rnp/rnp_sdk.h
src/lib/misc.cpp
src/rnp/fficli.cpp
src/rnp/fficli.h
src/rnpkeys/rnpkeys.cpp
src/tests/exportkey.cpp
src/tests/generatekey.cpp
src/tests/issues/1030.cpp
src/tests/support.cpp

We had some mess in CLI key search functions, so this PR is aimed to fix it (and make code a bit more C++).

Use single key search function in CLI

---

src/rnp/fficli.cpp
src/rnp/rnp.cpp

#1082 use CFG_KEYSTORE_DISABLED as bool

---

src/librepgp/stream-common.cpp

Avoid potentially incoherent reads #1090

---

Brewfile
CMakeLists.txt
ci/before_install.sh
docs/installation.adoc
src/tests/CMakeLists.txt
src/tests/cli_common.py
src/tests/cli_perf.py
src/tests/cli_tests.py
src/tests/data/cli_EncryptSign/regenerate_keys

Migration to Python 3

---

README.adoc

What about to have Windows badge as well (and utilizing the fact that it passes tests :) ) ?

Add Windows workflow badge.

---

ci/before_install.sh
src/lib/crypto/ec.cpp

These were missing a leading 0, which `hex2bin` apparently handled correctly but it has other bugs that I'm doing another PR for.

Fix secp521r1 b & n fields.

---

src/lib/misc.cpp
src/librepgp/stream-dump.cpp
src/librepgp/stream-packet.cpp
src/librepgp/stream-parse.cpp
src/rnp/fficli.cpp

These are just a few issues found with clang's static analyzers (since coverity is/was down).

Address a few static analysis issues.

---

src/tests/key-store-search.cpp

I'm not really sure on the last line here, could probably use another set of eyes on that

tests: Fix up test_key_store_search_by_name.

---

src/tests/cli_tests.py

Fix for issue https://github.com/rnpgp/rnp/issues/1201

Fix duplicated CLI test func name, closes #1201

---

CMakeLists.txt
docs/develop.adoc
src/fuzzing/CMakeLists.txt
src/fuzzing/dump.c
src/fuzzing/keyring.c

Also take care of TODOs from #1199

Improve fuzzing configuration to support more fuzzers

---

ci/before_install.sh

As title said.
Issue reference: https://github.com/Homebrew/homebrew-bundle/issues/751

Fix homebrew CI problem for macOS.

---

.github/workflows/windows.yml

Update windows workflow to use msys2/setup-msys2@v2

---

include/repgp/repgp_def.h
src/lib/generate-key.cpp
src/lib/types.h
src/librepgp/stream-key.cpp
src/librepgp/stream-key.h
src/librepgp/stream-sig.cpp

This PR is about fulfilling initialization list in constructors and some refactoring.
Fixes #1236 
Fixes #1237 
Fixes #1240

Fix bunch of issues reported by Coverity.

---

include/rekey/rnp_key_store.h
include/repgp/repgp_def.h
src/fuzzing/CMakeLists.txt
src/fuzzing/keyring.c
src/fuzzing/keyring_g10.cpp
src/fuzzing/keyring_kbx.c
src/fuzzing/verify.c
src/fuzzing/verify_detached.c
src/lib/pgp-key.h
src/lib/rnp.cpp
src/librekey/key_store_g10.cpp
src/librekey/key_store_kbx.cpp
src/librekey/rnp_key_store.cpp
src/librepgp/stream-packet.cpp
src/librepgp/stream-parse.cpp
src/tests/ffi.cpp

This PR adds new fuzzers and fixes issue found during quick-running them.
Also it fixes fuzz_keyring, which used incorrect input object.
Fixes partially #1261

Add more fuzzers

---

.github/workflows/windows.yml
src/tests/data/.gitattributes

don't adjust line endings in test files

---

src/lib/rnp.cpp
src/librepgp/stream-common.cpp
src/rnp/fficli.cpp
src/rnp/rnpcfg.cpp
src/rnp/rnpcfg.h
src/tests/ffi.cpp
src/tests/generatekey.cpp
src/tests/key-add-userid.cpp

Refactor usage of strcpy.

---

src/rnp/fficli.cpp
src/tests/cli_tests.py

Fix possible crash of CLI utilities when HOME is not set.

---

src/lib/rnp.cpp

Fix barely possible memory leak in rnp_input_from_memory().

---

ci/before_install.sh

Use secondary mirror if main MSYS2 packages server is down.

---

.cirrus.yml
ci/before_install.sh

Fix Cirrus CI failures

---

src/librepgp/stream-write.cpp

Use correct type for wrlen variable in partial_dst_write().

---

src/lib/rnp.cpp
src/librepgp/stream-common.cpp
src/librepgp/stream-common.h
src/tests/streams.cpp

Also do not allow NULL parameter in init_mem_src().

Check for possible NULL returned from mem_dest_own_memory()

---

.github/workflows/centos7.yml
.github/workflows/cifuzz.yml
.github/workflows/coverity.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-msvc.yml
ci/before_install.sh
ci/gha/setup-env.inc.sh
ci/install.sh

Github Actions: Update some sub-actions to v2, and do not use deprecated ::set-env.

---

src/lib/pgp-key.h
src/lib/types.h
src/librepgp/stream-packet.cpp

Fix a bunch of coverity issues.

---

src/lib/pgp-key.cpp
src/lib/pgp-key.h
src/lib/rnp.cpp

With old architecture retrieval of the single signature would cost O(N), making it quite slow for the large keys.
This PR adds fields which allows to enumerate direct-key/per-userid signatures much faster, giving ~15x performance improvement with huge test keyring.

Improve performance of the signatures access.

---

src/lib/rnp.cpp
src/rnp/fficli.cpp
src/rnpkeys/main.cpp
src/rnpkeys/rnpkeys.cpp
src/rnpkeys/rnpkeys.h
src/tests/cli_tests.py

Added --password option to rnpkeys

---

include/repgp/repgp_def.h
src/lib/pgp-key.cpp
src/lib/pgp-key.h
src/lib/rnp.cpp
src/lib/types.h
src/librekey/key_store_kbx.cpp
src/librekey/key_store_pgp.cpp
src/librekey/rnp_key_store.cpp
src/tests/key-add-userid.cpp
src/tests/key-protect.cpp
src/tests/key-unlock.cpp
src/tests/load-g10.cpp
src/tests/load-pgp.cpp
src/tests/streams.cpp

This PR continues pgp_key_t C++ refactoring, and is based on PR #1364

Refactor pgp_key_t lock/protect/write.

---

.github/workflows/centos7.yml
include/rnp/rnp_sdk.h
src/common/file-utils.cpp
src/common/file-utils.h
src/common/str-utils.cpp
src/common/str-utils.h
src/lib/misc.cpp
src/lib/rnp.cpp
src/lib/utils.h
src/librekey/rnp_key_store.cpp
src/librepgp/stream-common.cpp
src/rnp/fficli.cpp
src/rnp/fficli.h
src/rnp/rnp.cpp
src/rnpkeys/main.cpp
src/tests/cli.cpp
src/tests/cli_common.py
src/tests/cli_tests.py
src/tests/ffi.cpp
src/tests/file-utils.cpp
src/tests/generatekey.cpp
src/tests/key-unlock.cpp
src/tests/log-switch.cpp
src/tests/rnp_tests.h
src/tests/streams.cpp
src/tests/support.cpp
src/tests/support.h

Closes #1312 
Detailed description in the conversation.

UTF-8 on Windows

---

src/lib/generate-key.cpp
src/lib/pgp-key.cpp
src/lib/pgp-key.h
src/lib/rnp.cpp
src/librekey/key_store_pgp.cpp
src/librekey/rnp_key_store.cpp
src/librepgp/stream-sig.cpp
src/librepgp/stream-write.cpp
src/tests/ffi.cpp
src/tests/generatekey.cpp
src/tests/key-add-userid.cpp
src/tests/key-validate.cpp
src/tests/load-pgp.cpp
src/tests/streams.cpp

This PR follows PR #1364 and PR #1367 with pgp_key_t refactoring.

Refactor pgp_key_t validation/refreshing.

---

include/rnp/rnp.h

Fix rnp_key_unlock() and some other FFI documentation.

---

.github/workflows/windows-msvc.yml
ci/env-windows.inc.sh
ci/test.msvc.sh

enable CTEST_PARALLEL for MSVC build

---

docs/installation.adoc

This docs update is only in release branch yet, so let's merge it to the master as well.

docs: Update for release 0.14.0

---

include/rnp/rnp.h
src/lib/pgp-key.cpp
src/lib/pgp-key.h
src/lib/rnp.cpp
src/tests/ffi-enc.cpp
src/tests/ffi-key-sig.cpp
src/tests/ffi-uid.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h
src/tests/support.cpp
src/tests/support.h

This PR is part of the work on issue #1006.

Add FFI functions to remove signatures/userids.

---

include/rnp/rnp.h
src/examples/verify.c
src/lib/crypto/mpi.cpp
src/lib/crypto/mpi.h
src/lib/crypto/symmetric.h
src/lib/pgp-key.h
src/lib/types.h
src/librepgp/stream-packet.h
src/rnp/fficli.h
src/tests/support.cpp

I didn't force-push fixes from the PR #1382, so pushing those as another PR.
Also it removes some discovered unused code, which is too few for the separate PR.

Fix issues discussed in the PR #1382

---

src/tests/cipher.cpp
src/tests/rnp_tests.h

PR #1419 was merged into release, so we need it in master too.

Update master with commits from PR 1419.

---

src/librepgp/stream-armor.cpp
src/tests/streams.cpp

Make CRC failures non-fatal on dearmoring

---

src/lib/librnp.3.adoc
src/rnp/rnp.1.adoc
src/rnpkeys/rnpkeys.1.adoc

Fix some typos in the man pages.

---

src/lib/crypto/hash.cpp
src/lib/crypto/hash.h
src/lib/utils.h

Some minor cleanup.

---

.github/workflows/centos7.yml
cmake/librnp.pc.in
docs/installation.adoc
src/lib/CMakeLists.txt

Continued from https://github.com/rnpgp/rnp/pull/1417

Avoid embedding major version number in library name

---

src/lib/crypto/bn.cpp
src/lib/crypto/bn.h
src/tests/cipher.cpp

Remove unused function bn_print_fp()

---

README.adoc
cmake/info.cmake
docs/c-usage.adoc
docs/cli-usage.adoc
docs/develop.adoc
docs/develop/packaging.adoc
docs/installation.adoc
git-hooks/pre-commit.sh
src/examples/README.md
src/lib/pgp-key.cpp

This PR incorporates @dkg's #1411 and some additional documentation cleanup.

Spelling and documentation cleanup

---

LICENSE.md
src/lib/librnp.3.adoc
src/rnp/rnp.1.adoc
src/rnpkeys/rnpkeys.1.adoc

Add security feedback link to man pages

---

src/lib/crypto/s2k.cpp
src/lib/crypto/s2k.h

Remove unused S2K functions.

---

.github/workflows/lint.yml
src/lib/crypto/dsa.cpp

Use version 11 of clang-format in the CI.

---

src/lib/crypto/mem.cpp
src/lib/crypto/mem.h
src/lib/crypto/mpi.cpp
src/lib/crypto/mpi.h
src/lib/logging.h
src/lib/misc.cpp
src/lib/pgp-key.cpp
src/lib/rnp.cpp
src/lib/utils.h
src/librekey/key_store_pgp.cpp
src/librekey/rnp_key_store.cpp
src/tests/cipher.cpp
src/tests/key-grip.cpp
src/tests/key-store-search.cpp
src/tests/key-validate.cpp
src/tests/load-g10.cpp
src/tests/load-pgp.cpp
src/tests/support.cpp
src/tests/support.h
src/tests/utils-hex2bin.cpp

We had some mess with hex encoding/decoding, so this PR cleans it up.

Cleanup and move hex-encoding/decoding functions to crypto.

---

cmake/Modules/AdocMan.cmake
src/lib/CMakeLists.txt
src/lib/librnp.3.adoc
src/rnp/CMakeLists.txt
src/rnp/rnp.1.adoc
src/rnpkeys/CMakeLists.txt
src/rnpkeys/rnpkeys.1.adoc

Cherry-picked from #1477 as suggested in https://github.com/rnpgp/rnp/pull/1477#issuecomment-817770721

Use CMake to generate version numbers in man pages

---

ci/before_install.sh

Fixes https://github.com/rnpgp/rnp/issues/1487

ci: Use ruby26 in Cirrus CI.

---

docs/installation.adoc

I just attempted this on a fresh install and had to modify it a bit.

docs: Fix MSYS installation docs.

---

src/librepgp/stream-armor.cpp

Remove unused variables in stream-armor.cpp

---

.github/workflows/debian9.yml
ci/before_install.sh
ci/main.sh
ci/utils.inc.sh

Build automake-1.16 for Debian9

---

CMakeLists.txt
cmake/Modules/AdocMan.cmake
src/lib/CMakeLists.txt
src/rnp/CMakeLists.txt
src/rnpkeys/CMakeLists.txt

Make building man pages optional through option ENABLE_DOC.

---

ci/lib/install_functions.inc.sh
ci/main.sh

Fix GHA build failures

---

.cirrus.yml
.github/workflows/centos7.yml
.github/workflows/centos8.yml
.github/workflows/coverity.yml
.github/workflows/debian9.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
ci/build_package_rpm.sh
ci/env-linux.inc.sh
ci/install_cacheable_dependencies.sh
ci/install_noncacheable_dependencies.sh
ci/lib/cacheable_install_functions.inc.sh
ci/lib/install_functions.inc.sh
ci/main.sh

Try to fix CI build cache issues

---

CHANGELOG.md

Copy CHANGELOG to the master branch.

---

src/lib/rnp.cpp

Refactor FFI internals to not do excessive hex encoding/decoding.

---

include/rnp/rnp.h
src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h

Add new FFI function rnp_key_get_default_key().

---

src/tests/cli.cpp

Fix comments in cli tests.

---

src/lib/rnp.cpp

Refactor rnp_key_get_default_key() to avoid code duplication.

---

.github/workflows/debian9.yml
.github/workflows/windows-msvc.yml

Improved GHA msvc performance
x64: from ~  1h 10m   to   ~ 30m
win32:   from ~2h 5m  to ~ 40m
Overall time shall drop to ~1h 10m   (debian9 job duration)

Improved GHA msvc performance

---

cmake/version.cmake

Update version.cmake to not require Git.

---

ci/lib/install_functions.inc.sh

ci: Make ensure_automake() install 1.16.4 when GnuPG version is 2.3+

---

.github/workflows/centos8.yml
ci/lib/cacheable_install_functions.inc.sh
src/tests/cli_tests.py

Support GnuPG 2.3.1 in cli_tests.

---

include/rnp/rnp.h
src/lib/CMakeLists.txt
src/lib/crypto/backend_version.cpp
src/lib/crypto/backend_version.h
src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h

Add new FFI functions rnp_backend_string() and rnp_backend_version().

---

src/librekey/kbx_blob.hpp
src/librekey/key_store_kbx.cpp

Those doesn't seem to be critical, but still let's have a shorter list on coverity.
- related PR #1629

Fix minor coverity issues introduced with PR 1629

---

src/lib/crypto/mem.h

Add basic secure_vector for OpenSSL backend.

---

src/tests/cipher.cpp

Some platforms or some specific machiens (e.g. the s390x and sparc64
debian build daemons) don't appear to consume a linearly-proportional
amount of wall clock time as the S2K iteration count increases.
This patch changes nothing substantive about the s2k_iteration_tuning
test, but enables specific machines or architectures to override the
expectation with a simple #define (e.g. by adding
-DS2K_MINIMUM_TUNING_RATIO=1.5 to CXXFLAGS).
I'm generally of the opinion that this kind of tuning is misleading or
even counterproductive when your threat model is modern hardware (the
iterated S2K count octet should probably just always be maxed out to
0xff, and even better would be to stop using this S2K mechanism and
adopt the upcoming argon feature).  So the right thing overall might
be to stop …

Enable loosening the s2k_iteration_tuning test

---

ci/env-freebsd.inc.sh
ci/lib/install_functions.inc.sh

Disable SC2295.

---

.github/workflows/centos7.yml
.github/workflows/centos8-ossl.yml
.github/workflows/centos8.yml
.github/workflows/debian9.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-msvc.yml
.github/workflows/windows.yml
.gitignore
ci/env-msys.inc.sh
ci/lib/cacheable_install_functions.inc.sh
ci/lib/install_functions.inc.sh
ci/main.sh

Revert "Added Clang builds to Ubuntu, CentOS7, CentOS8 (+ ossl),  MacOS, Debian9 and Windows-msys2 workflows"

---

src/lib/ffi-priv-types.h
src/lib/rnp.cpp
src/lib/utils.h

...for more clean code with less defines.

Use define + static_assert instead of nested MAX macro usage.

---

.github/workflows/centos7.yml
.github/workflows/centos8.yml
.github/workflows/macos.yml

As title says. Will not pass until #1671 is merged.

Update CI exported symbols check.

---

src/common/str-utils.cpp
src/common/str-utils.h
src/librepgp/stream-common.cpp
src/rnp/fficli.cpp
src/tests/streams.cpp
src/tests/support.cpp

Define PATH_MAX on systems where it is not available (Gnu/Hurd).

---

ci/success.sh

Fix codecov integration.

---

src/tests/cli_tests.py

This started as attempt to quick-fix sonarlint comments, making code look scary in VS Code, and went too wild.
There are still some things to refactor, but that could be done in further PRs.
Fixes #1610

Refactor cli_tests to use unittest.TestCase assert methods.

---

src/rnp/rnp.cpp
src/rnp/rnpcfg.h
src/rnpkeys/rnpkeys.cpp
src/rnpkeys/rnpkeys.h
src/tests/cli_tests.py

Improve CLI tests coverage.

---

src/lib/rnp.cpp
src/librepgp/stream-parse.cpp
src/librepgp/stream-parse.h
src/tests/ffi-enc.cpp
src/tests/ffi.cpp

Increase FFI code coverage and fix issues found.

---

include/rnp/rnp.h

As suggested at https://bugzilla.mozilla.org/show_bug.cgi?id=1713621#c17

FFI: Update documentation of the rnp_key_25519_bits_tweaked

---

src/tests/ffi.cpp
src/tests/s2k-iterations.cpp

Fix few GCC warnings to not distract when looking at CI logs.

---

src/librepgp/stream-armor.cpp
src/tests/data/test_messages/message.txt.cleartext-signed-nonewline
src/tests/ffi.cpp
src/tests/streams.cpp

Accept armored messages without empty line after headers

---

.github/workflows/centos8-ossl.yml
.github/workflows/centos8.yml
ci/lib/install_functions.inc.sh

Use container tgagor/centos:stream8 instead of EOLed centos:8

---

src/tests/cli_tests.py

This should fix coverage degraded via PR #1749

Fix packet dumping cases which are not covered by tests.

---

include/rnp/rnp.h
src/lib/rnp.cpp
src/tests/ffi-key-prop.cpp
src/tests/ffi.cpp
src/tests/support.cpp
src/tests/support.h

FFI: Add function rnp_key_is_expired().

---

src/common/str-utils.cpp
src/common/str-utils.h
src/lib/defaults.h
src/lib/rnp.cpp
src/librepgp/stream-parse.cpp
src/librepgp/stream-write.cpp
src/rnp/rnp.1.adoc
src/rnp/rnp.cpp
src/rnpkeys/rnpkeys.cpp
src/tests/cli_tests.py

Fixes #1676 
Also slightly refactors CLI code and extends test coverage.

Limit AEAD chunk size bits to 16

---

src/librepgp/stream-armor.cpp
src/tests/cli_tests.py

Fix edge case with missing crc24 and 3-byte last block.

---

src/lib/generate-key.cpp
src/lib/pgp-key.cpp
src/lib/rnp.cpp
src/librekey/key_store_g10.cpp
src/librekey/key_store_kbx.cpp
src/librekey/key_store_pgp.cpp
src/librekey/key_store_pgp.h
src/librepgp/stream-armor.cpp
src/librepgp/stream-armor.h
src/librepgp/stream-common.h
src/librepgp/stream-key.cpp
src/librepgp/stream-key.h
src/librepgp/stream-parse.cpp
src/librepgp/stream-sig.cpp
src/librepgp/stream-sig.h
src/tests/data/test_key_validity/case5/generate.cpp
src/tests/ffi-key.cpp
src/tests/key-validate.cpp
src/tests/large-mpi.cpp
src/tests/load-pgp.cpp
src/tests/streams.cpp

This PR is aimed to partially refactor src/dst code to be more C++. Currently it brings a lot of complexities/redundant code and so on.
Still work in progress, pushed to detect possible leaks/problems as early as possible.

Refactor goto/streams usage to be more C++.

---

.github/workflows/windows-msys2.yml
ci/lib/install_functions.inc.sh

Fix "windows-msys2 / CC clang; GnuPG stable: build

---

include/rnp/rnp.h

Fix documentation mistype

---

src/librepgp/stream-common.cpp
src/tests/cli_tests.py

Hopefully this would end up a mess with failing Codecov CI test :)
Fixes #1764

Add test for some AEAD edge cases, causing random coverage changes.

---

src/tests/ffi-key.cpp

This PR update tests, and adds some code snippet displaying how to check for the weak key signatures. At some point it should be added to the FFI API, once it will be finalized how the API should look like.

Update tests with weak signature checks code snippet.

---

include/rnp/rnp.h

Fix description for rnp_op_generate_destroy().

---

include/rnp/rnp.h
src/lib/rnp.cpp
src/rnp/fficli.cpp
src/tests/ffi.cpp

FFI: add function rnp_output_to_stdout and use it in the CLI.

---

src/lib/rnp.cpp
src/tests/ffi.cpp
src/tests/rnp_tests.h

Add missing codes to rnp_result_to_string().

---

ci/lib/install_functions.inc.sh
docs/develop/packaging.adoc
docs/installation.adoc

Update Ribose's RPM signing key to the actual one.

---

include/rnp/rnp.h
src/lib/defaults.h
src/lib/rnp.cpp
src/rnp/rnp.cpp
src/tests/cli_tests.py
src/tests/ffi.cpp

Use AEAD-OCB by default.

---

src/common/str-utils.cpp
src/common/str-utils.h
src/rnp/fficli.cpp
src/tests/support.cpp

Move hex-check functions to the str-utils to avoid code duplication.

---

src/rnp/fficli.cpp
src/tests/cli_tests.py

...and update tests coverage to avoid regression in the future.

CLI: fix key location failure with 0x prefix/spaces/tabs.

---

docs/installation.adoc

Minor documenation update as per issue #1927

Update installation.adoc for Windows/MSVC instructions.

---

README.adoc

Match what is listed in https://github.com/rnpgp/rnp/tree/master/.github/workflows

Update supported platforms

---

LICENSE.md

Fixes #1932.
Thank you @remicollet for reporting this!

Add MIT license for sha1 collision detection code

---

LICENSE-OCB.md

Fixes #1935.
cc: @remicollet @bkmgit @richardfontana

Clarify status of OCB license

---

docs/installation.adoc

Update windows installation instructions.

---

src/lib/rnp.cpp

Less code duplication = better (in almost all cases).

Refactor duplicated flag check/update code with a single function call.

---

src/lib/pgp-key.cpp
src/tests/cli_tests.py

Correct detection of the subkey expiration when primary key is expired.

---

ci/lib/install_functions.inc.sh

Fix shellcheck's SC2086 warnings.

---

src/tests/cli_common.py
src/tests/cli_tests.py
src/tests/data/cli_EncryptSign/regenerate_keys

This PR fixes Python errors, reported by CodeQL in https://github.com/ni4/rnp/pull/24
This is done via separate PR (which will be followed by C++ fixes) to make easier CodeQL workflow addition.

Fix bunch of CodeQL Python warnings.

---

src/common/time-utils.cpp
src/common/time-utils.h
src/librekey/key_store_g10.cpp
src/librepgp/stream-dump.cpp
src/rnp/fficli.cpp
src/rnp/rnpcfg.cpp
src/tests/cli.cpp
src/tests/streams.cpp
src/tests/utils-rnpcfg.cpp

Refactor time handling functions to use thread-safe system calls.

---

.github/workflows/codeql.yml
ci/lib/install_functions.inc.sh
src/lib/rnp.cpp
src/librekey/key_store_kbx.cpp

...and fix reported errors. Obsoletes PR #1948 as there is no permission to push to the original branch.

Add CodeQL workflow

---

ci/lib/install_functions.inc.sh
src/lib/rnp.cpp

This would allow easier disabling/enabling them via ifdefs in case backend doesn't support certain algos.

FFI: refactor supported algorithms checks

---

ci/lib/install_functions.inc.sh

CI: Bump used ruby version to 3.0

---

src/rnp/fficli.cpp
src/rnp/rnp.cpp
src/tests/cli_tests.py

CLI: add --s2k-iterations --s2k-msec options to rnp.

---

src/lib/crypto/symmetric.cpp
src/lib/crypto/symmetric.h
src/lib/crypto/symmetric_ossl.cpp
src/lib/rnp.cpp
src/librepgp/stream-parse.cpp
src/tests/cli_tests.py

As title says, just some minor refactor for less code duplication/better readability.

Refactor and remove redundant logging for pgp_is_sa_supported().

---

src/lib/crypto/symmetric.cpp
src/lib/crypto/symmetric.h
src/lib/crypto/symmetric_ossl.cpp
src/lib/rnp.cpp
src/librepgp/stream-parse.cpp
src/tests/cli_tests.py

Fixes undesired behaviour introduced via the PR #1977

Do not display error messages while listing supported algorithms

---

src/rnp/fficli.cpp
src/tests/cli_tests.py

Allow single --edit-key subcommand only.

---

src/lib/crypto/dsa_ossl.cpp

Use EVP_PKEY_CTX_ctrl for OpenSSL < 1.1.1e

---

.github/workflows/centos-and-fedora.yml
ci/lib/cacheable_install_functions.inc.sh
ci/lib/install_functions.inc.sh
src/tests/cli_tests.py

...and bump checked GnuPG versions.
Fixes #1999

Update cli_tests to correctly support GnuPG 2.4.0 OCB-only AEAD.

---

.github/workflows/centos-and-fedora.yml
src/tests/utils-hex2bin.cpp

Add coverage run for OpenSSL backend.

---

src/rnp/rnp.cpp
src/rnpkeys/main.cpp
src/rnpkeys/rnpkeys.cpp
src/tests/cli_tests.py

Fix argument processing issues in CLI tools

---

src/common/str-utils.cpp
src/tests/cli_tests.py

Handle std::out_of_range exception.

---

src/tests/ffi-enc.cpp
src/tests/ffi.cpp
src/tests/support.cpp
src/tests/support.h

Needed to re-check it, so let's update tests as well.

Add test_ffi_decrypt_pk_unlocked

---

src/librekey/key_store_pgp.cpp
src/librepgp/stream-key.cpp
src/librepgp/stream-packet.cpp
src/librepgp/stream-packet.h
src/librepgp/stream-parse.cpp
src/librepgp/stream-sig.cpp

Some refactoring for better code readability and coverage.

Refactor streamed packets header parsing.

---

src/librepgp/stream-parse.cpp

Add some more checks during PKESK/SKESK parsing.

---

src/librepgp/stream-write.cpp
src/tests/ffi-enc.cpp

Fix typo with unnamed variable in stream-parse.

---

include/rnp/rnp.h
src/examples/encrypt.c
src/examples/sign.c
src/lib/types.h
src/librepgp/stream-parse.cpp
src/rnp/fficli.cpp

Just minor fixes to keep the Coverity list empty.

Fix minor coverity issues.

---

.cirrus.yml
ci/tests/pkg-tests.sh

Refactor FreeBSD Cirrus-CI workflow

---

src/rnpkeys/rnpkeys.cpp
src/tests/cli_tests.py

Closes #1777 
Now CLI output looks like this:
```
$ rnpkeys --homedir testkr/ --import src/tests/data/test_key_validity/alice-sub-pub.pgp
Keyring directory 'testkr/' is empty.
Use "rnpkeys" command to generate a new key or import existing keys from the file or GnuPG keyrings.
pub   255/EdDSA 0451409669ffde3c 2019-12-26 [SC]
73edcc9119afc8e2dbbdcde50451409669ffde3c
uid           Alice <alice@rnp>
sub   256/ECDH dd23ceb7febeff17 2019-12-27 [E]
a4bbb77370217bca2307ad0ddd23ceb7febeff17
Import finished: 2 keys processed, 2 new public keys, 0 new secret keys, 0 updated, 0 unchanged.
$ rnpkeys --homedir testkr/ --import src/tests/data/test_key_validity/alice-sub-pub.pgp
Warning: no keys were loaded from the keyring 'testkr/secring.gpg'.
Import finished: 2 keys processed, 0 new public keys, 0 new …
```

CLI: print stats for imported keys.

---

.github/workflows/macos.yml

Temporary workaround for #2062

Added manual setup of botan2 on MacOS

---

.github/workflows/windows-native.yml
ci/tests/ci-tests.sh
src/lib/crypto/mem.h

- Close #2056 
- Fix failing CI test
- Remove redundant workflow runs on Windows

Fixed msvc/clang-cl debug builds 

---

src/fuzzing/keyring.c
src/fuzzing/keyring_kbx.c
src/fuzzing/sigimport.c
src/fuzzing/verify.c
src/fuzzing/verify_detached.c
src/lib/crypto/cipher_botan.cpp
src/lib/crypto/ecdh.cpp

...for less noise from compilers.

Fix Botan3 and fuzzers warnings

---

docs/develop.adoc
git-hooks/pre-commit.sh

Fix mentioned clang-format version to 11.0.0

---

include/rnp/rnp.h

Fix nonexisting functions in documentation.

---

src/rnpkeys/rnpkeys.cpp
src/rnpkeys/rnpkeys.h
src/tests/cli_tests.py

CLI: add --keyfile option to rnpkeys.

---

src/lib/rnp.cpp
src/tests/ffi-key.cpp

Allow signing subkeys in rnp_generate_key_ex().

---

src/lib/crypto/hash_common.cpp
src/lib/crypto/hash_crc24.cpp
src/lib/crypto/signatures.cpp
src/lib/utils.h
src/librekey/key_store_kbx.cpp
src/librepgp/stream-packet.cpp
src/librepgp/stream-packet.h
src/librepgp/stream-parse.cpp
src/librepgp/stream-sig.cpp
src/librepgp/stream-write.cpp

Remove duplicate uint-to-buf and buf-to-uint code.

---

src/rnpkeys/tui.cpp
src/tests/cli_tests.py

CLI: prevent endless loop in rnpkeys expert mode.

---

src/lib/crypto/mpi.cpp
src/lib/crypto/mpi.h
src/lib/json-utils.cpp
src/lib/json-utils.h
src/lib/rnp.cpp
src/librepgp/stream-dump.cpp

This PR refactors json-c calls for better clarity and code reusability.

Refactor JSON calls for better clarity.

---

.github/workflows/windows-native.yml
CMakeLists.txt
src/lib/crypto.cpp
src/lib/crypto/symmetric.cpp
src/lib/crypto/symmetric_ossl.cpp
src/lib/rnp.cpp
src/librepgp/stream-sig.cpp
src/rnp/rnp.cpp
src/rnpkeys/main.cpp
src/rnpkeys/rnpkeys.cpp
src/tests/ffi-enc.cpp
src/tests/ffi-key.cpp
src/tests/ffi.cpp
src/tests/support.cpp

Fixed warnings reported by MSVC compiler

---

src/common/str-utils.h
src/lib/crypto/mem.cpp
src/lib/crypto/mem.h
src/lib/crypto/mem_ossl.cpp
src/lib/json-utils.cpp
src/lib/logging.h
src/lib/pgp-key.cpp
src/lib/rnp.cpp
src/librepgp/stream-key.cpp
src/tests/key-validate.cpp
src/tests/utils-hex2bin.cpp

Fix some more coverity issues.

---

.cirrus.yml
.github/workflows/centos-and-fedora.yml
.github/workflows/debian.yml
.github/workflows/fuzzing.yml
.github/workflows/lint.yml
.github/workflows/macos.yml
.github/workflows/opensuse.yml
.github/workflows/time-machine.yml
.github/workflows/windows-msys2.yml
.github/workflows/windows-native.yml

And check version.txt contents if it is changed.
Fixes #2226

Ignore pushes to version.txt for most of the CI

---

src/rnp/rnp.1.adoc

These are minor textual cleanups.

Clarify text in rnp(1)

---

CHANGELOG.md

Fix mistake in the changelog.

---

docs/develop.adoc

With sample from clang-format-lint-action

Update docs about the clang-format usage.

---

.github/workflows/centos-and-fedora.yml
README.adoc

Remove EOLed centos 7 from the CI.

---

.github/workflows/lint.yml
_typos.toml
ci-legacy/lib/install_functions.inc.sh
ci/build_tarball.sh
cmake/CTestCostData.txt
cmake/rnp_tests_discover.cmake
docs/Doxyfile
docs/installation.adoc
include/rekey/rnp_key_store.h
include/rnp/rnp.h
src/lib/crypto/elgamal.cpp
src/lib/rnp.cpp
src/librekey/key_store_g10.cpp
src/librepgp/stream-parse.cpp
src/librepgp/stream-parse.h
src/librepgp/stream-sig.h
src/librepgp/stream-write.cpp
src/librepgp/stream-write.h
src/rnp/rnpcfg.h
src/tests/cli_perf.py
src/tests/cli_tests.py
src/tests/ffi-key-prop.cpp
src/tests/ffi-key.cpp
src/tests/generatekey.cpp

Fix typos in the codebase and add typos checking action.

---

src/tests/cli_tests.py

CI: update test cases with more date parsing cases

---

.github/workflows/windows-native.yml
src/lib/types.h

Fix vcpkg download failure.

---

src/common/file-utils.cpp
src/common/file-utils.h

Fixes https://github.com/rnpgp/rnp/issues/2318

Windows: Handle big files

---

ci/tests/pk-tests.sh
src/lib/CMakeLists.txt
src/lib/version.h.in

Generate and install rnp_ver.h header with version and features information
